{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An authenticated user can mute alert rules from arbitrary organizations and projects given a known given rule ID. The user does not need to be a member of the organization or have permissions on the project. </p>\n<p>In our review, we have identified no instances where alerts have been muted by unauthorized parties. </p>\n<h3 id=\"patches\">Patches</h3>\n<p>A patch was issued to ensure authorization checks are properly scoped on requests to mute alert rules. Authenticated users who do not have the necessary permissions are no longer able to mute alerts. </p>\n<p>Sentry SaaS users do not need to take any action. <a href=\"https://github.com/getsentry/self-hosted\">Self-Hosted Sentry</a> users should upgrade to version <strong>24.9.0</strong> or higher.</p>\n<h3 id=\"affected-versions\">Affected Versions</h3>\n<p>The rule mute feature was generally available as of 23.6.0 but users with early access may have had the feature as of 23.4.0. </p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/getsentry/sentry/pull/77016\">Prevent muting alerts</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/getsentry/sentry/security/advisories/GHSA-v345-w9f2-mpm5\">https://github.com/getsentry/sentry/security/advisories/GHSA-v345-w9f2-mpm5</a></li>\n<li><a href=\"https://github.com/getsentry/sentry/pull/77016\">https://github.com/getsentry/sentry/pull/77016</a></li>\n<li><a href=\"https://github.com/getsentry/sentry/commit/e8e71708758e1f9f56ce815ace73fe60d9e608dc\">https://github.com/getsentry/sentry/commit/e8e71708758e1f9f56ce815ace73fe60d9e608dc</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v345-w9f2-mpm5\">https://github.com/advisories/GHSA-v345-w9f2-mpm5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v345-w9f2-mpm5",
            "title": "[sentry] Sentry improperly authorizes muting of alert rules",
            "date_modified": "2024-09-17T17:55:38.000Z",
            "date_published": "2024-09-17T17:55:38.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v345-w9f2-mpm5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>An authenticated user may delete user issue alert notifications for arbitrary users given a known alert ID. </p>\n<h3 id=\"patches\">Patches</h3>\n<p>A patch was issued to ensure authorization checks are properly scoped on requests to delete user alert notifications.</p>\n<p>Sentry SaaS users do not need to take any action. <a href=\"https://github.com/getsentry/self-hosted\">Self-Hosted Sentry</a> users should upgrade to version <strong>24.9.0</strong> or higher.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/getsentry/sentry/pull/77093/\">Prevent muting user alerts</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/getsentry/sentry/security/advisories/GHSA-54m3-95j9-v89j\">https://github.com/getsentry/sentry/security/advisories/GHSA-54m3-95j9-v89j</a></li>\n<li><a href=\"https://github.com/getsentry/sentry/pull/77093\">https://github.com/getsentry/sentry/pull/77093</a></li>\n<li><a href=\"https://github.com/getsentry/sentry/commit/590258255bcb3a5fa4c56f21297b6c99131cfb9d\">https://github.com/getsentry/sentry/commit/590258255bcb3a5fa4c56f21297b6c99131cfb9d</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-54m3-95j9-v89j\">https://github.com/advisories/GHSA-54m3-95j9-v89j</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-54m3-95j9-v89j",
            "title": "[sentry] Sentry improperly authorizes deletion of user issue alert notifications",
            "date_modified": "2024-09-17T17:55:31.000Z",
            "date_published": "2024-09-17T17:55:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-54m3-95j9-v89j"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A vulnerability in corydolphin/flask-cors version 4.0.1 allows the <code>Access-Control-Allow-Private-Network</code> CORS header to be set to true by default, without any configuration option. This behavior can expose private network resources to unauthorized external access, leading to significant security risks such as data breaches, unauthorized access to sensitive information, and potential network intrusions.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-6221\">https://nvd.nist.gov/vuln/detail/CVE-2024-6221</a></li>\n<li><a href=\"https://huntr.com/bounties/a42935fc-6f57-4818-bca4-3d528235df4d\">https://huntr.com/bounties/a42935fc-6f57-4818-bca4-3d528235df4d</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/flask-cors/PYSEC-2024-71.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/flask-cors/PYSEC-2024-71.yaml</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/issues/362\">https://github.com/corydolphin/flask-cors/issues/362</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/pull/363\">https://github.com/corydolphin/flask-cors/pull/363</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/pull/368\">https://github.com/corydolphin/flask-cors/pull/368</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/commit/c8514760cf03fcce16d77f6db7007aad429c4548\">https://github.com/corydolphin/flask-cors/commit/c8514760cf03fcce16d77f6db7007aad429c4548</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/releases\">https://github.com/corydolphin/flask-cors/releases</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/commit/7ae310c56ac30e0b94fb42129aa377bf633256ec\">https://github.com/corydolphin/flask-cors/commit/7ae310c56ac30e0b94fb42129aa377bf633256ec</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-hxwh-jpp2-84pm\">https://github.com/advisories/GHSA-hxwh-jpp2-84pm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-hxwh-jpp2-84pm",
            "title": "[Flask-Cors] Flask-CORS allows the `Access-Control-Allow-Private-Network` CORS header to be set to true by default",
            "date_modified": "2024-09-17T17:51:40.000Z",
            "date_published": "2024-08-18T21:31:07.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-hxwh-jpp2-84pm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>django.forms.ImageField</code> class in the form system in Django before 1.3.2 and 1.4.x before 1.4.1 completely decompresses image data during image validation, which allows remote attackers to cause a denial of service (memory consumption) by uploading an image file.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2012-3443\">https://nvd.nist.gov/vuln/detail/CVE-2012-3443</a></li>\n<li><a href=\"https://github.com/django/django/commit/9ca0ff6268eeff92d0d0ac2c315d4b6a8e229155\">https://github.com/django/django/commit/9ca0ff6268eeff92d0d0ac2c315d4b6a8e229155</a></li>\n<li><a href=\"https://github.com/django/django/commit/da33d67181b53fe6cc737ac1220153814a1509f6\">https://github.com/django/django/commit/da33d67181b53fe6cc737ac1220153814a1509f6</a></li>\n<li><a href=\"https://www.debian.org/security/2012/dsa-2529\">https://www.debian.org/security/2012/dsa-2529</a></li>\n<li><a href=\"https://www.mandriva.com/security/advisories?name=MDVSA-2012:143\">https://www.mandriva.com/security/advisories?name=MDVSA-2012:143</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2012/07/31/1\">https://www.openwall.com/lists/oss-security/2012/07/31/1</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2012/07/31/2\">https://www.openwall.com/lists/oss-security/2012/07/31/2</a></li>\n<li><a href=\"https://www.ubuntu.com/usn/USN-1560-1\">https://www.ubuntu.com/usn/USN-1560-1</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2012-3.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2012-3.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2012/jul/30/security-releases-issued\">https://www.djangoproject.com/weblog/2012/jul/30/security-releases-issued</a></li>\n<li><a href=\"http://www.debian.org/security/2012/dsa-2529\">http://www.debian.org/security/2012/dsa-2529</a></li>\n<li><a href=\"http://www.mandriva.com/security/advisories?name=MDVSA-2012:143\">http://www.mandriva.com/security/advisories?name=MDVSA-2012:143</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2012/07/31/1\">http://www.openwall.com/lists/oss-security/2012/07/31/1</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2012/07/31/2\">http://www.openwall.com/lists/oss-security/2012/07/31/2</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-1560-1\">http://www.ubuntu.com/usn/USN-1560-1</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-59w8-4wm2-4xw8\">https://github.com/advisories/GHSA-59w8-4wm2-4xw8</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-59w8-4wm2-4xw8",
            "title": "[Django] Django Image Field Vulnerable to Image Decompression Bombs",
            "date_modified": "2024-09-17T15:14:47.000Z",
            "date_published": "2022-05-17T05:12:01.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-59w8-4wm2-4xw8"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><code>contrib.sessions.middleware.SessionMiddleware</code> in Django 1.8.x before 1.8.4, 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions allows remote attackers to cause a denial of service (session store consumption or session record removal) via a large number of requests to <code>contrib.auth.views.logout</code>, which triggers the creation of an empty session record.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-5963\">https://nvd.nist.gov/vuln/detail/CVE-2015-5963</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2015:1876\">https://access.redhat.com/errata/RHSA-2015:1876</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-09/msg00026.html\">http://lists.opensuse.org/opensuse-updates/2015-09/msg00026.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html\">http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2015-1766.html\">http://rhn.redhat.com/errata/RHSA-2015-1766.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2015-1767.html\">http://rhn.redhat.com/errata/RHSA-2015-1767.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2015-1894.html\">http://rhn.redhat.com/errata/RHSA-2015-1894.html</a></li>\n<li><a href=\"http://www.debian.org/security/2015/dsa-3338\">http://www.debian.org/security/2015/dsa-3338</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html\">http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2720-1\">http://www.ubuntu.com/usn/USN-2720-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/2f5485346ee6f84b4e52068c04e043092daf55f7\">https://github.com/django/django/commit/2f5485346ee6f84b4e52068c04e043092daf55f7</a></li>\n<li><a href=\"https://github.com/django/django/commit/575f59f9bc7c59a5e41a081d1f5f55fc859c5012\">https://github.com/django/django/commit/575f59f9bc7c59a5e41a081d1f5f55fc859c5012</a></li>\n<li><a href=\"https://github.com/django/django/commit/8cc41ce7a7a8f6bebfdd89d5ab276cd0109f4fc5\">https://github.com/django/django/commit/8cc41ce7a7a8f6bebfdd89d5ab276cd0109f4fc5</a></li>\n<li><a href=\"https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.8.4.txt#L9-L21\">https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.8.4.txt#L9-L21</a></li>\n<li><a href=\"https://web.archive.org/web/20150904151934/http://www.securitytracker.com/id/1033318\">https://web.archive.org/web/20150904151934/http://www.securitytracker.com/id/1033318</a></li>\n<li><a href=\"https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/76428\">https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/76428</a></li>\n<li><a href=\"https://github.com/django/django/commit/2eb86b01d7b59be06076f6179a454d0fd0afaff6\">https://github.com/django/django/commit/2eb86b01d7b59be06076f6179a454d0fd0afaff6</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2015/aug/18/security-releases\">https://www.djangoproject.com/weblog/2015/aug/18/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-22.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-22.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pgxh-wfw4-jx2v\">https://github.com/advisories/GHSA-pgxh-wfw4-jx2v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pgxh-wfw4-jx2v",
            "title": "[Django] Django denial of service via empty session record creation",
            "date_modified": "2024-09-17T15:08:39.000Z",
            "date_published": "2022-05-17T00:36:02.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pgxh-wfw4-jx2v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><code>contrib.sessions.middleware.SessionMiddleware</code> in Django 1.8.x before 1.8.4, 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions allows remote attackers to cause a denial of service (session store consumption or session record removal) via a large number of requests to <code>contrib.auth.views.logout</code>, which triggers the creation of an empty session record.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-5963\">https://nvd.nist.gov/vuln/detail/CVE-2015-5963</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2015:1876\">https://access.redhat.com/errata/RHSA-2015:1876</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-09/msg00026.html\">http://lists.opensuse.org/opensuse-updates/2015-09/msg00026.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html\">http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2015-1766.html\">http://rhn.redhat.com/errata/RHSA-2015-1766.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2015-1767.html\">http://rhn.redhat.com/errata/RHSA-2015-1767.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2015-1894.html\">http://rhn.redhat.com/errata/RHSA-2015-1894.html</a></li>\n<li><a href=\"http://www.debian.org/security/2015/dsa-3338\">http://www.debian.org/security/2015/dsa-3338</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html\">http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2720-1\">http://www.ubuntu.com/usn/USN-2720-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/2f5485346ee6f84b4e52068c04e043092daf55f7\">https://github.com/django/django/commit/2f5485346ee6f84b4e52068c04e043092daf55f7</a></li>\n<li><a href=\"https://github.com/django/django/commit/575f59f9bc7c59a5e41a081d1f5f55fc859c5012\">https://github.com/django/django/commit/575f59f9bc7c59a5e41a081d1f5f55fc859c5012</a></li>\n<li><a href=\"https://github.com/django/django/commit/8cc41ce7a7a8f6bebfdd89d5ab276cd0109f4fc5\">https://github.com/django/django/commit/8cc41ce7a7a8f6bebfdd89d5ab276cd0109f4fc5</a></li>\n<li><a href=\"https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.8.4.txt#L9-L21\">https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.8.4.txt#L9-L21</a></li>\n<li><a href=\"https://web.archive.org/web/20150904151934/http://www.securitytracker.com/id/1033318\">https://web.archive.org/web/20150904151934/http://www.securitytracker.com/id/1033318</a></li>\n<li><a href=\"https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/76428\">https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/76428</a></li>\n<li><a href=\"https://github.com/django/django/commit/2eb86b01d7b59be06076f6179a454d0fd0afaff6\">https://github.com/django/django/commit/2eb86b01d7b59be06076f6179a454d0fd0afaff6</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2015/aug/18/security-releases\">https://www.djangoproject.com/weblog/2015/aug/18/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-22.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-22.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pgxh-wfw4-jx2v\">https://github.com/advisories/GHSA-pgxh-wfw4-jx2v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pgxh-wfw4-jx2v",
            "title": "[Django] Django denial of service via empty session record creation",
            "date_modified": "2024-09-17T15:08:39.000Z",
            "date_published": "2022-05-17T00:36:02.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pgxh-wfw4-jx2v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><code>contrib.sessions.middleware.SessionMiddleware</code> in Django 1.8.x before 1.8.4, 1.7.x before 1.7.10, 1.4.x before 1.4.22, and possibly other versions allows remote attackers to cause a denial of service (session store consumption or session record removal) via a large number of requests to <code>contrib.auth.views.logout</code>, which triggers the creation of an empty session record.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2015-5963\">https://nvd.nist.gov/vuln/detail/CVE-2015-5963</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2015:1876\">https://access.redhat.com/errata/RHSA-2015:1876</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html\">http://lists.fedoraproject.org/pipermail/package-announce/2015-November/172084.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-09/msg00026.html\">http://lists.opensuse.org/opensuse-updates/2015-09/msg00026.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html\">http://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2015-1766.html\">http://rhn.redhat.com/errata/RHSA-2015-1766.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2015-1767.html\">http://rhn.redhat.com/errata/RHSA-2015-1767.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2015-1894.html\">http://rhn.redhat.com/errata/RHSA-2015-1894.html</a></li>\n<li><a href=\"http://www.debian.org/security/2015/dsa-3338\">http://www.debian.org/security/2015/dsa-3338</a></li>\n<li><a href=\"http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html\">http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2720-1\">http://www.ubuntu.com/usn/USN-2720-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/2f5485346ee6f84b4e52068c04e043092daf55f7\">https://github.com/django/django/commit/2f5485346ee6f84b4e52068c04e043092daf55f7</a></li>\n<li><a href=\"https://github.com/django/django/commit/575f59f9bc7c59a5e41a081d1f5f55fc859c5012\">https://github.com/django/django/commit/575f59f9bc7c59a5e41a081d1f5f55fc859c5012</a></li>\n<li><a href=\"https://github.com/django/django/commit/8cc41ce7a7a8f6bebfdd89d5ab276cd0109f4fc5\">https://github.com/django/django/commit/8cc41ce7a7a8f6bebfdd89d5ab276cd0109f4fc5</a></li>\n<li><a href=\"https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.8.4.txt#L9-L21\">https://github.com/django/django/blob/4555a823fd57e261e1b19c778429473256c8ea08/docs/releases/1.8.4.txt#L9-L21</a></li>\n<li><a href=\"https://web.archive.org/web/20150904151934/http://www.securitytracker.com/id/1033318\">https://web.archive.org/web/20150904151934/http://www.securitytracker.com/id/1033318</a></li>\n<li><a href=\"https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/76428\">https://web.archive.org/web/20200228050526/http://www.securityfocus.com/bid/76428</a></li>\n<li><a href=\"https://github.com/django/django/commit/2eb86b01d7b59be06076f6179a454d0fd0afaff6\">https://github.com/django/django/commit/2eb86b01d7b59be06076f6179a454d0fd0afaff6</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2015/aug/18/security-releases\">https://www.djangoproject.com/weblog/2015/aug/18/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-22.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2015-22.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pgxh-wfw4-jx2v\">https://github.com/advisories/GHSA-pgxh-wfw4-jx2v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pgxh-wfw4-jx2v",
            "title": "[Django] Django denial of service via empty session record creation",
            "date_modified": "2024-09-17T15:08:39.000Z",
            "date_published": "2022-05-17T00:36:02.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pgxh-wfw4-jx2v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><code>django.middleware.common.CommonMiddleware</code> in Django 1.11.x before 1.11.15 and 2.0.x before 2.0.8 has an Open Redirect.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-14574\">https://nvd.nist.gov/vuln/detail/CVE-2018-14574</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2019:0265\">https://access.redhat.com/errata/RHSA-2019:0265</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5hg3-6c2f-f3wr\">https://github.com/advisories/GHSA-5hg3-6c2f-f3wr</a></li>\n<li><a href=\"https://www.debian.org/security/2018/dsa-4264\">https://www.debian.org/security/2018/dsa-4264</a></li>\n<li><a href=\"https://web.archive.org/web/20190901075632/http://www.securitytracker.com/id/1041403\">https://web.archive.org/web/20190901075632/http://www.securitytracker.com/id/1041403</a></li>\n<li><a href=\"https://web.archive.org/web/20200227115315/http://www.securityfocus.com/bid/104970\">https://web.archive.org/web/20200227115315/http://www.securityfocus.com/bid/104970</a></li>\n<li><a href=\"https://github.com/django/django/commit/6fffc3c6d420e44f4029d5643f38d00a39b08525\">https://github.com/django/django/commit/6fffc3c6d420e44f4029d5643f38d00a39b08525</a></li>\n<li><a href=\"https://github.com/django/django/commit/c4e5ff7fdb5fce447675e90291fd33fddd052b3c\">https://github.com/django/django/commit/c4e5ff7fdb5fce447675e90291fd33fddd052b3c</a></li>\n<li><a href=\"https://github.com/django/django/commit/d6eaee092709aad477a9894598496c6deec532ff\">https://github.com/django/django/commit/d6eaee092709aad477a9894598496c6deec532ff</a></li>\n<li><a href=\"https://usn.ubuntu.com/3726-1\">https://usn.ubuntu.com/3726-1</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2018/aug/01/security-releases\">https://www.djangoproject.com/weblog/2018/aug/01/security-releases</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2018-2.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2018-2.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5hg3-6c2f-f3wr",
            "title": "[Django] Django open redirect",
            "date_modified": "2024-09-17T15:06:32.000Z",
            "date_published": "2018-10-04T21:58:46.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5hg3-6c2f-f3wr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The password reset functionality in django.contrib.auth in Django before 1.1.3, 1.2.x before 1.2.4, and 1.3.x before 1.3 beta 1 does not validate the length of a string representing a base36 timestamp, which allows remote attackers to cause a denial of service (resource consumption) via a URL that specifies a large base36 integer.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2010-4535\">https://nvd.nist.gov/vuln/detail/CVE-2010-4535</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=665373\">https://bugzilla.redhat.com/show_bug.cgi?id=665373</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-7wph-fc4w-wqp2\">https://github.com/advisories/GHSA-7wph-fc4w-wqp2</a></li>\n<li><a href=\"http://code.djangoproject.com/changeset/15032\">http://code.djangoproject.com/changeset/15032</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053041.html\">http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053041.html</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053072.html\">http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053072.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2010/12/23/4\">http://www.openwall.com/lists/oss-security/2010/12/23/4</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2011/01/03/5\">http://www.openwall.com/lists/oss-security/2011/01/03/5</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-1040-1\">http://www.ubuntu.com/usn/USN-1040-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/7f8dd9cbac074389af8d8fd235bf2cb657227b9a\">https://github.com/django/django/commit/7f8dd9cbac074389af8d8fd235bf2cb657227b9a</a></li>\n<li><a href=\"https://github.com/django/django/commit/d5d8942a160685c403d381a279e72e09de5489a9\">https://github.com/django/django/commit/d5d8942a160685c403d381a279e72e09de5489a9</a></li>\n<li><a href=\"http://www.djangoproject.com/weblog/2010/dec/22/security\">http://www.djangoproject.com/weblog/2010/dec/22/security</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-9.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-9.yaml</a></li>\n<li><a href=\"https://web.archive.org/web/20200228193349/http://www.securityfocus.com/bid/45563\">https://web.archive.org/web/20200228193349/http://www.securityfocus.com/bid/45563</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-7wph-fc4w-wqp2",
            "title": "[Django] Improper date handling in Django",
            "date_modified": "2024-09-17T15:03:58.000Z",
            "date_published": "2018-07-23T19:51:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-7wph-fc4w-wqp2"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>django.contrib.sessions in Django before 1.2.7 and 1.3.x before 1.3.1, when session data is stored in the cache, uses the root namespace for both session identifiers and application-data keys, which allows remote attackers to modify a session by triggering use of a key that is equal to that session's identifier.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4136\">https://nvd.nist.gov/vuln/detail/CVE-2011-4136</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-x88j-93vc-wpmp\">https://github.com/advisories/GHSA-x88j-93vc-wpmp</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/ac7c3a110f906e4dfed3a17451bf7fd9fcb81296\">https://github.com/django/django/commit/ac7c3a110f906e4dfed3a17451bf7fd9fcb81296</a></li>\n<li><a href=\"https://github.com/django/django/commit/fbe2eead2fa9d808658ca582241bcacb02618840\">https://github.com/django/django/commit/fbe2eead2fa9d808658ca582241bcacb02618840</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-1.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-1.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-x88j-93vc-wpmp",
            "title": "[Django] Session manipulation in Django",
            "date_modified": "2024-09-16T23:04:00.000Z",
            "date_published": "2018-07-23T19:52:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-x88j-93vc-wpmp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>django.contrib.sessions in Django before 1.2.7 and 1.3.x before 1.3.1, when session data is stored in the cache, uses the root namespace for both session identifiers and application-data keys, which allows remote attackers to modify a session by triggering use of a key that is equal to that session's identifier.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4136\">https://nvd.nist.gov/vuln/detail/CVE-2011-4136</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-x88j-93vc-wpmp\">https://github.com/advisories/GHSA-x88j-93vc-wpmp</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/ac7c3a110f906e4dfed3a17451bf7fd9fcb81296\">https://github.com/django/django/commit/ac7c3a110f906e4dfed3a17451bf7fd9fcb81296</a></li>\n<li><a href=\"https://github.com/django/django/commit/fbe2eead2fa9d808658ca582241bcacb02618840\">https://github.com/django/django/commit/fbe2eead2fa9d808658ca582241bcacb02618840</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-1.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-1.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-x88j-93vc-wpmp",
            "title": "[Django] Session manipulation in Django",
            "date_modified": "2024-09-16T23:04:00.000Z",
            "date_published": "2018-07-23T19:52:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-x88j-93vc-wpmp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>emitters.py in Django Piston before 0.2.3 and 0.2.x before 0.2.2.1 does not properly deserialize YAML data, which allows remote attackers to execute arbitrary Python code via vectors related to the yaml.load method.</p>\n<p>Django Tastypie has a very similar vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4103\">https://nvd.nist.gov/vuln/detail/CVE-2011-4103</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=750658\">https://bugzilla.redhat.com/show_bug.cgi?id=750658</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pvhp-v9qp-xf5r\">https://github.com/advisories/GHSA-pvhp-v9qp-xf5r</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2344\">http://www.debian.org/security/2011/dsa-2344</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2011/11/01/10\">http://www.openwall.com/lists/oss-security/2011/11/01/10</a></li>\n<li><a href=\"https://bitbucket.org/jespern/django-piston/commits/91bdaec89543\">https://bitbucket.org/jespern/django-piston/commits/91bdaec89543</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django-piston/PYSEC-2014-24.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django-piston/PYSEC-2014-24.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/nov/01/piston-and-tastypie-security-releases\">https://www.djangoproject.com/weblog/2011/nov/01/piston-and-tastypie-security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pvhp-v9qp-xf5r",
            "title": "[django-piston] Django-piston and Django-tastypie do not properly deserialize YAML data",
            "date_modified": "2024-09-16T23:00:29.000Z",
            "date_published": "2018-07-23T19:50:48.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pvhp-v9qp-xf5r"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross-site scripting (XSS) vulnerability in Django 1.2.x before 1.2.2 allows remote attackers to inject arbitrary web script or HTML via a csrfmiddlewaretoken (aka csrf_token) cookie.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2010-3082\">https://nvd.nist.gov/vuln/detail/CVE-2010-3082</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=632239\">https://bugzilla.redhat.com/show_bug.cgi?id=632239</a></li>\n<li><a href=\"https://exchange.xforce.ibmcloud.com/vulnerabilities/61729\">https://exchange.xforce.ibmcloud.com/vulnerabilities/61729</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-fxpg-gg9g-76gj\">https://github.com/advisories/GHSA-fxpg-gg9g-76gj</a></li>\n<li><a href=\"http://marc.info/?l=oss-security&amp;m=128403961700444&amp;w=2\">http://marc.info/?l=oss-security&amp;m=128403961700444&amp;w=2</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-1004-1\">http://www.ubuntu.com/usn/USN-1004-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/7f84657b6b2243cc787bdb9f296710c8d13ad0bd\">https://github.com/django/django/commit/7f84657b6b2243cc787bdb9f296710c8d13ad0bd</a></li>\n<li><a href=\"http://www.djangoproject.com/weblog/2010/sep/08/security-release\">http://www.djangoproject.com/weblog/2010/sep/08/security-release</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2010-12.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2010-12.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-fxpg-gg9g-76gj",
            "title": "[Django] Cross-site scripting in django",
            "date_modified": "2024-09-16T22:57:34.000Z",
            "date_published": "2018-07-23T19:52:42.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-fxpg-gg9g-76gj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The administrative interface in django.contrib.admin in Django before 1.1.3, 1.2.x before 1.2.4, and 1.3.x before 1.3 beta 1 does not properly restrict use of the query string to perform certain object filtering, which allows remote authenticated users to obtain sensitive information via a series of requests containing regular expressions, as demonstrated by a created_by__password__regex parameter.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2010-4534\">https://nvd.nist.gov/vuln/detail/CVE-2010-4534</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=665373\">https://bugzilla.redhat.com/show_bug.cgi?id=665373</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-fwr5-q9rx-294f\">https://github.com/advisories/GHSA-fwr5-q9rx-294f</a></li>\n<li><a href=\"http://archives.neohapsis.com/archives/fulldisclosure/2010-12/0580.html\">http://archives.neohapsis.com/archives/fulldisclosure/2010-12/0580.html</a></li>\n<li><a href=\"http://code.djangoproject.com/changeset/15031\">http://code.djangoproject.com/changeset/15031</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053041.html\">http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053041.html</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053072.html\">http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053072.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2010/12/23/4\">http://www.openwall.com/lists/oss-security/2010/12/23/4</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2011/01/03/5\">http://www.openwall.com/lists/oss-security/2011/01/03/5</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-1040-1\">http://www.ubuntu.com/usn/USN-1040-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/17084839fd7e267da5729f2a27753322b9d415a0\">https://github.com/django/django/commit/17084839fd7e267da5729f2a27753322b9d415a0</a></li>\n<li><a href=\"https://github.com/django/django/commit/85207a245bf09fdebe486b4c7bbcb65300f2a693\">https://github.com/django/django/commit/85207a245bf09fdebe486b4c7bbcb65300f2a693</a></li>\n<li><a href=\"http://evilpacket.net/2010/dec/22/information-leakage-django-administrative-interfac\">http://evilpacket.net/2010/dec/22/information-leakage-django-administrative-interfac</a></li>\n<li><a href=\"http://ngenuity-is.com/advisories/2010/dec/22/information-leakage-in-django-administrative-inter\">http://ngenuity-is.com/advisories/2010/dec/22/information-leakage-in-django-administrative-inter</a></li>\n<li><a href=\"http://www.djangoproject.com/weblog/2010/dec/22/security\">http://www.djangoproject.com/weblog/2010/dec/22/security</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-8.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-8.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-fwr5-q9rx-294f",
            "title": "[Django] Improper query string handling in Django",
            "date_modified": "2024-09-16T22:56:44.000Z",
            "date_published": "2018-07-23T19:51:40.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-fwr5-q9rx-294f"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in Ansible, where sensitive information stored in Ansible Vault files can be exposed in plaintext during the execution of a playbook. This occurs when using tasks such as include_vars to load vaulted variables without setting the no_log: true parameter, resulting in sensitive data being printed in the playbook output or logs. This can lead to the unintentional disclosure of secrets like passwords or API keys, compromising security and potentially allowing unauthorized access or actions.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-8775\">https://nvd.nist.gov/vuln/detail/CVE-2024-8775</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/CVE-2024-8775\">https://access.redhat.com/security/cve/CVE-2024-8775</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=2312119\">https://bugzilla.redhat.com/show_bug.cgi?id=2312119</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jpxc-vmjf-9fcj\">https://github.com/advisories/GHSA-jpxc-vmjf-9fcj</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jpxc-vmjf-9fcj",
            "title": "[ansible-core] Ansible vulnerable to Insertion of Sensitive Information into Log File",
            "date_modified": "2024-09-16T22:55:01.000Z",
            "date_published": "2024-09-16T14:37:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jpxc-vmjf-9fcj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django before 1.2.7 and 1.3.x before 1.3.1 uses a request's HTTP Host header to construct a full URL in certain circumstances, which allows remote attackers to conduct cache poisoning attacks via a crafted request.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4139\">https://nvd.nist.gov/vuln/detail/CVE-2011-4139</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/2f7fadc38efa58ac0a8f93f936b82332a199f396\">https://github.com/django/django/commit/2f7fadc38efa58ac0a8f93f936b82332a199f396</a></li>\n<li><a href=\"https://github.com/django/django/commit/c613af4d6485586c79d692b70a9acac429f3ca9d\">https://github.com/django/django/commit/c613af4d6485586c79d692b70a9acac429f3ca9d</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-4.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-4.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rm2j-x595-q9cj\">https://github.com/advisories/GHSA-rm2j-x595-q9cj</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rm2j-x595-q9cj",
            "title": "[Django] Django Vulnerable to Cache Poisoning",
            "date_modified": "2024-09-16T22:35:48.000Z",
            "date_published": "2022-05-14T03:49:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rm2j-x595-q9cj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4137\">https://nvd.nist.gov/vuln/detail/CVE-2011-4137</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3jqw-crqj-w8qw\">https://github.com/advisories/GHSA-3jqw-crqj-w8qw</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/15/5\">http://openwall.com/lists/oss-security/2011/09/15/5</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0\">https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0</a></li>\n<li><a href=\"https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930\">https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-2.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-2.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw",
            "title": "[Django] Denial of service in django",
            "date_modified": "2024-09-16T22:34:23.000Z",
            "date_published": "2018-07-23T19:51:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4137\">https://nvd.nist.gov/vuln/detail/CVE-2011-4137</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3jqw-crqj-w8qw\">https://github.com/advisories/GHSA-3jqw-crqj-w8qw</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/15/5\">http://openwall.com/lists/oss-security/2011/09/15/5</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0\">https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0</a></li>\n<li><a href=\"https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930\">https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-2.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-2.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw",
            "title": "[Django] Denial of service in django",
            "date_modified": "2024-09-16T22:34:23.000Z",
            "date_published": "2018-07-23T19:51:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>verify_exists</code> functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's validity through a HEAD request, but then uses a GET request for the new target URL in the case of a redirect, which might allow remote attackers to trigger arbitrary GET requests with an unintended source IP address via a crafted Location header.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4138\">https://nvd.nist.gov/vuln/detail/CVE-2011-4138</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0\">https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0</a></li>\n<li><a href=\"https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930\">https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-3.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-3.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wxg3-mfph-qg9w\">https://github.com/advisories/GHSA-wxg3-mfph-qg9w</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wxg3-mfph-qg9w",
            "title": "[Django] Django Might Allow CSRF Requests via URL Verification",
            "date_modified": "2024-09-16T22:32:03.000Z",
            "date_published": "2022-05-14T03:49:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wxg3-mfph-qg9w"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\"</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2014-0472\">https://nvd.nist.gov/vuln/detail/CVE-2014-0472</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html\">http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2014-0456.html\">http://rhn.redhat.com/errata/RHSA-2014-0456.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2014-0457.html\">http://rhn.redhat.com/errata/RHSA-2014-0457.html</a></li>\n<li><a href=\"http://www.debian.org/security/2014/dsa-2934\">http://www.debian.org/security/2014/dsa-2934</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2169-1\">http://www.ubuntu.com/usn/USN-2169-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/2a5bcb69f42b84464b24b5c835dca6467b6aa7f1\">https://github.com/django/django/commit/2a5bcb69f42b84464b24b5c835dca6467b6aa7f1</a></li>\n<li><a href=\"https://github.com/django/django/commit/4352a50871e239ebcdf64eee6f0b88e714015c1b\">https://github.com/django/django/commit/4352a50871e239ebcdf64eee6f0b88e714015c1b</a></li>\n<li><a href=\"https://github.com/django/django/commit/c1a8c420fe4b27fb2caf5e46d23b5712fc0ac535\">https://github.com/django/django/commit/c1a8c420fe4b27fb2caf5e46d23b5712fc0ac535</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2014/apr/21/security\">https://www.djangoproject.com/weblog/2014/apr/21/security</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-1.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-1.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rvq6-mrpv-m6rm\">https://github.com/advisories/GHSA-rvq6-mrpv-m6rm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rvq6-mrpv-m6rm",
            "title": "[Django] Code Injection in Django",
            "date_modified": "2024-09-16T22:13:38.000Z",
            "date_published": "2022-05-17T03:07:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rvq6-mrpv-m6rm"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}