{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 37.0.0-43.0.0 are vulnerable to a security issue. More details about the vulnerability itself can be found in <a href=\"https://openssl-library.org/news/secadv/20240903.txt\">https://openssl-library.org/news/secadv/20240903.txt</a>.</p>\n<p>If you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/pyca/cryptography/security/advisories/GHSA-h4gh-qq45-vh27\">https://github.com/pyca/cryptography/security/advisories/GHSA-h4gh-qq45-vh27</a></li>\n<li><a href=\"https://openssl-library.org/news/secadv/20240903.txt\">https://openssl-library.org/news/secadv/20240903.txt</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h4gh-qq45-vh27\">https://github.com/advisories/GHSA-h4gh-qq45-vh27</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h4gh-qq45-vh27",
            "title": "[cryptography] pyca/cryptography has a vulnerable OpenSSL included in cryptography wheels",
            "date_modified": "2024-09-03T21:59:48.000Z",
            "date_published": "2024-09-03T21:59:48.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h4gh-qq45-vh27"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Apache Airflow prior to 2.2.0. This CVE applies to a specific case where a User who has \"can_create\" permissions on DAG Runs can create Dag Runs for dags that they don't have \"edit\" permissions for.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-45230\">https://nvd.nist.gov/vuln/detail/CVE-2021-45230</a></li>\n<li><a href=\"https://lists.apache.org/thread/m778ojn0k595rwco4ht9wjql89mjoxnl\">https://lists.apache.org/thread/m778ojn0k595rwco4ht9wjql89mjoxnl</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/apache-airflow/PYSEC-2022-11.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/apache-airflow/PYSEC-2022-11.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-4jh2-3c85-q67h\">https://github.com/advisories/GHSA-4jh2-3c85-q67h</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-4jh2-3c85-q67h",
            "title": "[apache-airflow] Improper Privilege Management in apache-airflow",
            "date_modified": "2024-09-03T21:38:44.000Z",
            "date_published": "2022-01-28T21:55:34.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-4jh2-3c85-q67h"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Apache Airflow before 1.10.5 when running with the \"classic\" UI, a malicious admin user could edit the state of objects in the Airflow metadata database to execute arbitrary javascript on certain page views. The new \"RBAC\" UI is unaffected.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-12398\">https://nvd.nist.gov/vuln/detail/CVE-2019-12398</a></li>\n<li><a href=\"https://github.com/apache/airflow/blob/1.10.5/CHANGELOG.txt\">https://github.com/apache/airflow/blob/1.10.5/CHANGELOG.txt</a></li>\n<li><a href=\"https://lists.apache.org/thread.html/r72487ad6b23d18689896962782f8c93032afe5c72a6bfd23b253352b%40%3Cusers.airflow.apache.org%3E\">https://lists.apache.org/thread.html/r72487ad6b23d18689896962782f8c93032afe5c72a6bfd23b253352b%40%3Cusers.airflow.apache.org%3E</a></li>\n<li><a href=\"https://lists.apache.org/thread.html/r72487ad6b23d18689896962782f8c93032afe5c72a6bfd23b253352b@%3Cdev.airflow.apache.org%3E\">https://lists.apache.org/thread.html/r72487ad6b23d18689896962782f8c93032afe5c72a6bfd23b253352b@%3Cdev.airflow.apache.org%3E</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2020/01/14/2\">http://www.openwall.com/lists/oss-security/2020/01/14/2</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/apache-airflow/PYSEC-2020-162.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/apache-airflow/PYSEC-2020-162.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rjvg-q57v-mjjc\">https://github.com/advisories/GHSA-rjvg-q57v-mjjc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rjvg-q57v-mjjc",
            "title": "[apache-airflow] XSS in Apache Airflow",
            "date_modified": "2024-09-03T21:36:38.000Z",
            "date_published": "2020-05-06T19:51:02.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rjvg-q57v-mjjc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in Ansible before version 2.2.0.0. The <code>apt_key</code> module does not properly verify key fingerprints, allowing remote adversary to create an OpenPGP key which matches the short key ID and inject this key instead of the correct key.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-8614\">https://nvd.nist.gov/vuln/detail/CVE-2016-8614</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-cmwx-9m2h-x7v4\">https://github.com/advisories/GHSA-cmwx-9m2h-x7v4</a></li>\n<li><a href=\"https://github.com/ansible/ansible-modules-core/issues/5237\">https://github.com/ansible/ansible-modules-core/issues/5237</a></li>\n<li><a href=\"https://github.com/ansible/ansible-modules-core/pull/5353\">https://github.com/ansible/ansible-modules-core/pull/5353</a></li>\n<li><a href=\"https://github.com/ansible/ansible-modules-core/pull/5357\">https://github.com/ansible/ansible-modules-core/pull/5357</a></li>\n<li><a href=\"https://github.com/ansible/ansible-modules-core/commit/1182d1f0b76d56f3667e27987a10b9ec8f03357d\">https://github.com/ansible/ansible-modules-core/commit/1182d1f0b76d56f3667e27987a10b9ec8f03357d</a></li>\n<li><a href=\"https://github.com/ansible/ansible-modules-core/commit/66d47c8149d84e52f64b7c4d1f340d45dca94d9c\">https://github.com/ansible/ansible-modules-core/commit/66d47c8149d84e52f64b7c4d1f340d45dca94d9c</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8614\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8614</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-37.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-37.yaml</a></li>\n<li><a href=\"https://web.archive.org/web/20200227214450/https://www.securityfocus.com/bid/94108\">https://web.archive.org/web/20200227214450/https://www.securityfocus.com/bid/94108</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-cmwx-9m2h-x7v4",
            "title": "[ansible] Ansible apt_key module does not properly verify key fingerprint",
            "date_modified": "2024-09-03T21:31:23.000Z",
            "date_published": "2018-10-10T17:23:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-cmwx-9m2h-x7v4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Ansible before version 2.3 has an input validation vulnerability in the handling of data sent from client systems. An attacker with control over a client system being managed by Ansible, and the ability to send facts back to the Ansible server, could use this flaw to execute arbitrary code on the Ansible server using the Ansible server privileges.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-7466\">https://nvd.nist.gov/vuln/detail/CVE-2017-7466</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1244\">https://access.redhat.com/errata/RHSA-2017:1244</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1334\">https://access.redhat.com/errata/RHSA-2017:1334</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1476\">https://access.redhat.com/errata/RHSA-2017:1476</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1499\">https://access.redhat.com/errata/RHSA-2017:1499</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1599\">https://access.redhat.com/errata/RHSA-2017:1599</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1685\">https://access.redhat.com/errata/RHSA-2017:1685</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-7466\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-7466</a></li>\n<li><a href=\"https://github.com/ansible/ansible/issues/24186\">https://github.com/ansible/ansible/issues/24186</a></li>\n<li><a href=\"https://web.archive.org/web/20170701161323/http://www.securityfocus.com/bid/97595\">https://web.archive.org/web/20170701161323/http://www.securityfocus.com/bid/97595</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/0d418789a298561fded9bce977d34babc9097079\">https://github.com/ansible/ansible/commit/0d418789a298561fded9bce977d34babc9097079</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/7ff9fa52cfcef2065f0db80d85dd94b9b754839c\">https://github.com/ansible/ansible/commit/7ff9fa52cfcef2065f0db80d85dd94b9b754839c</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-40.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-40.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3m8p-xpm6-8ww3\">https://github.com/advisories/GHSA-3m8p-xpm6-8ww3</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3m8p-xpm6-8ww3",
            "title": "[ansible] Ansible Arbitrary Code Execution",
            "date_modified": "2024-09-03T21:27:14.000Z",
            "date_published": "2022-05-13T01:07:33.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3m8p-xpm6-8ww3"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An exploitable vulnerability exists in the yaml loading functionality of ansible-vault before 1.0.5. A specially crafted vault can execute arbitrary python commands resulting in command execution. An attacker can insert python into the vault to trigger this vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-2809\">https://nvd.nist.gov/vuln/detail/CVE-2017-2809</a></li>\n<li><a href=\"https://github.com/tomoh1r/ansible-vault/issues/4\">https://github.com/tomoh1r/ansible-vault/issues/4</a></li>\n<li><a href=\"https://github.com/tomoh1r/ansible-vault/commit/3f8f659ef443ab870bb19f95d43543470168ae04\">https://github.com/tomoh1r/ansible-vault/commit/3f8f659ef443ab870bb19f95d43543470168ae04</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-c2w9-48qc-qpj4\">https://github.com/advisories/GHSA-c2w9-48qc-qpj4</a></li>\n<li><a href=\"https://github.com/tomoh1r/ansible-vault/blob/v1.0.5/CHANGES.txt\">https://github.com/tomoh1r/ansible-vault/blob/v1.0.5/CHANGES.txt</a></li>\n<li><a href=\"https://www.talosintelligence.com/vulnerability_reports/TALOS-2017-0305\">https://www.talosintelligence.com/vulnerability_reports/TALOS-2017-0305</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible-vault/PYSEC-2017-5.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible-vault/PYSEC-2017-5.yaml</a></li>\n<li><a href=\"https://web.archive.org/web/20171206173637/http://www.securityfocus.com/bid/100824\">https://web.archive.org/web/20171206173637/http://www.securityfocus.com/bid/100824</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-c2w9-48qc-qpj4",
            "title": "[ansible-vault] Code injection in ansible",
            "date_modified": "2024-09-03T21:23:15.000Z",
            "date_published": "2018-07-13T15:16:54.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-c2w9-48qc-qpj4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in ansible-runner. An improper escaping of the shell command, while calling the <code>ansible_runner.interface.run_command</code>, can lead to parameters getting executed as host's shell command. A developer could unintentionally write code that gets executed in the host rather than the virtual environment.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-4041\">https://nvd.nist.gov/vuln/detail/CVE-2021-4041</a></li>\n<li><a href=\"https://github.com/ansible/ansible-runner/commit/3533f265f4349a3f2a0283158cd01b59a6bbc7bd\">https://github.com/ansible/ansible-runner/commit/3533f265f4349a3f2a0283158cd01b59a6bbc7bd</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/CVE-2021-4041\">https://access.redhat.com/security/cve/CVE-2021-4041</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=2028074\">https://bugzilla.redhat.com/show_bug.cgi?id=2028074</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible-runner/PYSEC-2022-253.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible-runner/PYSEC-2022-253.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6j58-grhv-2769\">https://github.com/advisories/GHSA-6j58-grhv-2769</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6j58-grhv-2769",
            "title": "[ansible-runner] ansible-runner vulnerable to shell command injection",
            "date_modified": "2024-09-03T21:16:20.000Z",
            "date_published": "2022-08-25T00:00:27.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6j58-grhv-2769"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Background: The optional add-on package <code>Products.PythonScripts</code> adds <code>Script (Python)</code> to the list of content items a user can add to the Zope object database. Inside these scripts users can write Python code that is executed when rendered through the web. The code environment in these script objects is limited, it relies on the <code>RestrictedPython</code> package to provide a \"safe\" subset of Python instructions as well as the <code>AccessControl</code> package that defines security policies for execution in the context of a Zope application.</p>\n<p>Recently the <code>AccessControl</code> package was updated to fix a remote code execution security issue. A link to the security advisory is provided in the References section below. The bug tightens the <code>AccessControl</code> security policies for Zope by blocking access to unsafe classes inside the Python <code>string</code> module.</p>\n<p>You are only affected if the following are true:</p>\n<ul>\n<li>You use Python 3 for your Zope deployment (Zope 4 on Python 2 is not affected)</li>\n<li>You run Zope 4 below version 4.6.3 or Zope 5 below version 5.3</li>\n<li>You have installed the optional <code>Products.PythonScripts</code> add-on package</li>\n</ul>\n<p>By default, you need to have the admin-level Zope \"Manager\" role to add or edit Script (Python) objects through the web. Only sites that allow untrusted users to add/edit these scripts through the web - which would be a very unusual configuration to begin with - are at risk.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem has been fixed in <code>AccessControl</code> versions 4.3 and 5.2. Zope releases 4.6.3 and 5.3 now require these new <code>AccessControl</code> releases.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>A site administrator can restrict adding/editing Script (Python) objects through the web using the standard Zope user/role permission mechanisms. Untrusted users should not be assigned the Zope Manager role and adding/editing these scripts through the web should be restricted to trusted users only. This is the default configuration in Zope.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf\">AccessControl security advisory GHSA-qcx9-j53g-ccgf</a></li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in the <a href=\"https://github.com/zopefoundation/Zope/issues\">Zope issue tracker</a></li>\n<li>Email us at <a href=\"mailto:security@plone.org\">security@plone.org</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/zopefoundation/Zope/security/advisories/GHSA-g4gq-j4p2-j8fr\">https://github.com/zopefoundation/Zope/security/advisories/GHSA-g4gq-j4p2-j8fr</a></li>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf\">https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-32811\">https://nvd.nist.gov/vuln/detail/CVE-2021-32811</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/commit/f72a18dda8e9bf2aedb46168761668464a4be988\">https://github.com/zopefoundation/Zope/commit/f72a18dda8e9bf2aedb46168761668464a4be988</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/commit/869f947e586517566509e0ccdd4d99b60704cc02\">https://github.com/zopefoundation/Zope/commit/869f947e586517566509e0ccdd4d99b60704cc02</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/zope/PYSEC-2021-368.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/zope/PYSEC-2021-368.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-g4gq-j4p2-j8fr\">https://github.com/advisories/GHSA-g4gq-j4p2-j8fr</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-g4gq-j4p2-j8fr",
            "title": "[Zope] Remote Code Execution via Script (Python) objects under Python 3",
            "date_modified": "2024-09-03T21:14:04.000Z",
            "date_published": "2021-08-05T17:00:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-g4gq-j4p2-j8fr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Background: The optional add-on package <code>Products.PythonScripts</code> adds <code>Script (Python)</code> to the list of content items a user can add to the Zope object database. Inside these scripts users can write Python code that is executed when rendered through the web. The code environment in these script objects is limited, it relies on the <code>RestrictedPython</code> package to provide a \"safe\" subset of Python instructions as well as the <code>AccessControl</code> package that defines security policies for execution in the context of a Zope application.</p>\n<p>Recently the <code>AccessControl</code> package was updated to fix a remote code execution security issue. A link to the security advisory is provided in the References section below. The bug tightens the <code>AccessControl</code> security policies for Zope by blocking access to unsafe classes inside the Python <code>string</code> module.</p>\n<p>You are only affected if the following are true:</p>\n<ul>\n<li>You use Python 3 for your Zope deployment (Zope 4 on Python 2 is not affected)</li>\n<li>You run Zope 4 below version 4.6.3 or Zope 5 below version 5.3</li>\n<li>You have installed the optional <code>Products.PythonScripts</code> add-on package</li>\n</ul>\n<p>By default, you need to have the admin-level Zope \"Manager\" role to add or edit Script (Python) objects through the web. Only sites that allow untrusted users to add/edit these scripts through the web - which would be a very unusual configuration to begin with - are at risk.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem has been fixed in <code>AccessControl</code> versions 4.3 and 5.2. Zope releases 4.6.3 and 5.3 now require these new <code>AccessControl</code> releases.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>A site administrator can restrict adding/editing Script (Python) objects through the web using the standard Zope user/role permission mechanisms. Untrusted users should not be assigned the Zope Manager role and adding/editing these scripts through the web should be restricted to trusted users only. This is the default configuration in Zope.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf\">AccessControl security advisory GHSA-qcx9-j53g-ccgf</a></li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in the <a href=\"https://github.com/zopefoundation/Zope/issues\">Zope issue tracker</a></li>\n<li>Email us at <a href=\"mailto:security@plone.org\">security@plone.org</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/zopefoundation/Zope/security/advisories/GHSA-g4gq-j4p2-j8fr\">https://github.com/zopefoundation/Zope/security/advisories/GHSA-g4gq-j4p2-j8fr</a></li>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf\">https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-32811\">https://nvd.nist.gov/vuln/detail/CVE-2021-32811</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/commit/f72a18dda8e9bf2aedb46168761668464a4be988\">https://github.com/zopefoundation/Zope/commit/f72a18dda8e9bf2aedb46168761668464a4be988</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/commit/869f947e586517566509e0ccdd4d99b60704cc02\">https://github.com/zopefoundation/Zope/commit/869f947e586517566509e0ccdd4d99b60704cc02</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/zope/PYSEC-2021-368.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/zope/PYSEC-2021-368.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-g4gq-j4p2-j8fr\">https://github.com/advisories/GHSA-g4gq-j4p2-j8fr</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-g4gq-j4p2-j8fr",
            "title": "[Zope] Remote Code Execution via Script (Python) objects under Python 3",
            "date_modified": "2024-09-03T21:14:04.000Z",
            "date_published": "2021-08-05T17:00:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-g4gq-j4p2-j8fr"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>The module <code>AccessControl</code> defines security policies for Python code used in restricted code within Zope applications. Restricted code is any code that resides in Zope's object database, such as the contents of <code>Script (Python)</code> objects. </p>\n<p>The policies defined in <code>AccessControl</code> severely restrict access to Python modules and only exempt a few that are deemed safe, such as Python's <code>string</code> module. However, full access to the <code>string</code> module also allows access to the class <code>Formatter</code>, which can be overridden and extended within <code>Script (Python)</code> in a way that provides access to other unsafe Python libraries. Those unsafe Python libraries can be used for remote code execution.</p>\n<p>By default, you need to have the admin-level Zope \"Manager\" role to add or edit <code>Script (Python)</code> objects through the web. Only sites that allow untrusted users to add/edit these scripts through the web - which would be a very unusual configuration to begin with - are at risk.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem has been fixed in AccessControl 4.3 and 5.2.\nOnly AccessControl versions 4 and 5 are vulnerable, and only on Python 3, not Python 2.7.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>A site administrator can restrict adding/editing <code>Script (Python)</code> objects through the web using the standard Zope user/role permission mechanisms. Untrusted users should not be assigned the Zope Manager role and adding/editing these scripts through the web should be restricted to trusted users only. This is the default configuration in Zope.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in the <a href=\"https://github.com/zopefoundation/AccessControl/issues\">AccessControl issue tracker</a></li>\n<li>Email us at <a href=\"mailto:security@plone.org\">security@plone.org</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf\">https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-32807\">https://nvd.nist.gov/vuln/detail/CVE-2021-32807</a></li>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/commit/b42dd4badf803bb9fb71ac34cd9cb0c249262f2c\">https://github.com/zopefoundation/AccessControl/commit/b42dd4badf803bb9fb71ac34cd9cb0c249262f2c</a></li>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/blob/master/CHANGES.rst#51-2021-07-30\">https://github.com/zopefoundation/AccessControl/blob/master/CHANGES.rst#51-2021-07-30</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/security/advisories/GHSA-g4gq-j4p2-j8fr\">https://github.com/zopefoundation/Zope/security/advisories/GHSA-g4gq-j4p2-j8fr</a></li>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/commit/ae2dab0cc34e6dd1561c5b12d4a56cd140f87e1d\">https://github.com/zopefoundation/AccessControl/commit/ae2dab0cc34e6dd1561c5b12d4a56cd140f87e1d</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/commit/869f947e586517566509e0ccdd4d99b60704cc02\">https://github.com/zopefoundation/Zope/commit/869f947e586517566509e0ccdd4d99b60704cc02</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/commit/f72a18dda8e9bf2aedb46168761668464a4be988\">https://github.com/zopefoundation/Zope/commit/f72a18dda8e9bf2aedb46168761668464a4be988</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/accesscontrol/PYSEC-2021-335.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/accesscontrol/PYSEC-2021-335.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/accesscontrol/PYSEC-2021-370.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/accesscontrol/PYSEC-2021-370.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/zope/PYSEC-2021-368.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/zope/PYSEC-2021-368.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qcx9-j53g-ccgf\">https://github.com/advisories/GHSA-qcx9-j53g-ccgf</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qcx9-j53g-ccgf",
            "title": "[AccessControl] Remote Code Execution via unsafe classes in otherwise permitted modules",
            "date_modified": "2024-09-03T21:13:36.000Z",
            "date_published": "2021-08-05T17:01:30.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qcx9-j53g-ccgf"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>The module <code>AccessControl</code> defines security policies for Python code used in restricted code within Zope applications. Restricted code is any code that resides in Zope's object database, such as the contents of <code>Script (Python)</code> objects. </p>\n<p>The policies defined in <code>AccessControl</code> severely restrict access to Python modules and only exempt a few that are deemed safe, such as Python's <code>string</code> module. However, full access to the <code>string</code> module also allows access to the class <code>Formatter</code>, which can be overridden and extended within <code>Script (Python)</code> in a way that provides access to other unsafe Python libraries. Those unsafe Python libraries can be used for remote code execution.</p>\n<p>By default, you need to have the admin-level Zope \"Manager\" role to add or edit <code>Script (Python)</code> objects through the web. Only sites that allow untrusted users to add/edit these scripts through the web - which would be a very unusual configuration to begin with - are at risk.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The problem has been fixed in AccessControl 4.3 and 5.2.\nOnly AccessControl versions 4 and 5 are vulnerable, and only on Python 3, not Python 2.7.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>A site administrator can restrict adding/editing <code>Script (Python)</code> objects through the web using the standard Zope user/role permission mechanisms. Untrusted users should not be assigned the Zope Manager role and adding/editing these scripts through the web should be restricted to trusted users only. This is the default configuration in Zope.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in the <a href=\"https://github.com/zopefoundation/AccessControl/issues\">AccessControl issue tracker</a></li>\n<li>Email us at <a href=\"mailto:security@plone.org\">security@plone.org</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf\">https://github.com/zopefoundation/AccessControl/security/advisories/GHSA-qcx9-j53g-ccgf</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-32807\">https://nvd.nist.gov/vuln/detail/CVE-2021-32807</a></li>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/commit/b42dd4badf803bb9fb71ac34cd9cb0c249262f2c\">https://github.com/zopefoundation/AccessControl/commit/b42dd4badf803bb9fb71ac34cd9cb0c249262f2c</a></li>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/blob/master/CHANGES.rst#51-2021-07-30\">https://github.com/zopefoundation/AccessControl/blob/master/CHANGES.rst#51-2021-07-30</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/security/advisories/GHSA-g4gq-j4p2-j8fr\">https://github.com/zopefoundation/Zope/security/advisories/GHSA-g4gq-j4p2-j8fr</a></li>\n<li><a href=\"https://github.com/zopefoundation/AccessControl/commit/ae2dab0cc34e6dd1561c5b12d4a56cd140f87e1d\">https://github.com/zopefoundation/AccessControl/commit/ae2dab0cc34e6dd1561c5b12d4a56cd140f87e1d</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/commit/869f947e586517566509e0ccdd4d99b60704cc02\">https://github.com/zopefoundation/Zope/commit/869f947e586517566509e0ccdd4d99b60704cc02</a></li>\n<li><a href=\"https://github.com/zopefoundation/Zope/commit/f72a18dda8e9bf2aedb46168761668464a4be988\">https://github.com/zopefoundation/Zope/commit/f72a18dda8e9bf2aedb46168761668464a4be988</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/accesscontrol/PYSEC-2021-335.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/accesscontrol/PYSEC-2021-335.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/accesscontrol/PYSEC-2021-370.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/accesscontrol/PYSEC-2021-370.yaml</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/zope/PYSEC-2021-368.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/zope/PYSEC-2021-368.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qcx9-j53g-ccgf\">https://github.com/advisories/GHSA-qcx9-j53g-ccgf</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qcx9-j53g-ccgf",
            "title": "[AccessControl] Remote Code Execution via unsafe classes in otherwise permitted modules",
            "date_modified": "2024-09-03T21:13:36.000Z",
            "date_published": "2021-08-05T17:01:30.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qcx9-j53g-ccgf"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A data disclosure flaw was found in ansible. Password prompts in ansible-playbook and ansible-cli tools could expose passwords with special characters as they are not properly wrapped. A password with special characters is exposed starting with the first of these special characters. The highest threat from this vulnerability is to data confidentiality.</p>\n<p>This CVE exists due to an incomplete fix for CVE-2019-10206.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-14856\">https://nvd.nist.gov/vuln/detail/CVE-2019-14856</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2020:0756\">https://access.redhat.com/errata/RHSA-2020:0756</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14856\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14856</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html\">http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html\">http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html</a></li>\n<li><a href=\"https://github.com/ansible/ansible/pull/63351\">https://github.com/ansible/ansible/pull/63351</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/7f4befdea77045fa83b5f2b304bd5e16b219f74c\">https://github.com/ansible/ansible/commit/7f4befdea77045fa83b5f2b304bd5e16b219f74c</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/16684f118715a52e1c46d437652add9ca36423de\">https://github.com/ansible/ansible/commit/16684f118715a52e1c46d437652add9ca36423de</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/2cbd8775ca1271195169f62122df1f88b532e74f\">https://github.com/ansible/ansible/commit/2cbd8775ca1271195169f62122df1f88b532e74f</a></li>\n<li><a href=\"https://github.com/ansible/ansible/commit/40618d70e61af1123907a5fb246cc4fd35f1e5c3\">https://github.com/ansible/ansible/commit/40618d70e61af1123907a5fb246cc4fd35f1e5c3</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2019-146.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2019-146.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6fq2-x65v-v9h7\">https://github.com/advisories/GHSA-6fq2-x65v-v9h7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6fq2-x65v-v9h7",
            "title": "[ansible] Ansible password prompts could expose passwords",
            "date_modified": "2024-09-03T21:07:56.000Z",
            "date_published": "2022-05-24T17:02:07.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6fq2-x65v-v9h7"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An input validation vulnerability was found in Ansible's mysql_user module before 2.2.1.0, which may fail to correctly change a password in certain circumstances. Thus the previous password would still be active when it should have been changed.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-8647\">https://nvd.nist.gov/vuln/detail/CVE-2016-8647</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-x4cm-m36h-c6qj\">https://github.com/advisories/GHSA-x4cm-m36h-c6qj</a></li>\n<li><a href=\"https://github.com/ansible/ansible-modules-core/pull/5388\">https://github.com/ansible/ansible-modules-core/pull/5388</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2017:1685\">https://access.redhat.com/errata/RHSA-2017:1685</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/CVE-2016-8647\">https://access.redhat.com/security/cve/CVE-2016-8647</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=1396174\">https://bugzilla.redhat.com/show_bug.cgi?id=1396174</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8647\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8647</a></li>\n<li><a href=\"https://github.com/ansible/ansible-modules-core/commit/30fb384e7fb9a94ac3929e4a650877e45d8834c9\">https://github.com/ansible/ansible-modules-core/commit/30fb384e7fb9a94ac3929e4a650877e45d8834c9</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-58.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2018-58.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-x4cm-m36h-c6qj",
            "title": "[ansible] Improper Input Validation in ansible",
            "date_modified": "2024-09-03T21:00:20.000Z",
            "date_published": "2018-10-10T17:23:33.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-x4cm-m36h-c6qj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in the HTTP FileResponse class in Django 3.2 before 3.2.15 and 4.0 before 4.0.7. An application is vulnerable to a reflected file download (RFD) attack that sets the Content-Disposition header of a FileResponse when the filename is derived from user-supplied input.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-36359\">https://nvd.nist.gov/vuln/detail/CVE-2022-36359</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-245.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-245.yaml</a></li>\n<li><a href=\"https://groups.google.com/g/django-announce/c/8cz--gvaJr4\">https://groups.google.com/g/django-announce/c/8cz--gvaJr4</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2022/08/03/1\">http://www.openwall.com/lists/oss-security/2022/08/03/1</a></li>\n<li><a href=\"https://www.debian.org/security/2022/dsa-5254\">https://www.debian.org/security/2022/dsa-5254</a></li>\n<li><a href=\"https://github.com/django/django/commit/b3e4494d759202a3b6bf247fd34455bf13be5b80\">https://github.com/django/django/commit/b3e4494d759202a3b6bf247fd34455bf13be5b80</a></li>\n<li><a href=\"https://github.com/django/django/commit/b7d9529cbe0af4adabb6ea5d01ed8dcce3668fb3\">https://github.com/django/django/commit/b7d9529cbe0af4adabb6ea5d01ed8dcce3668fb3</a></li>\n<li><a href=\"https://github.com/django/django/commit/bd062445cffd3f6cc6dcd20d13e2abed818fa173\">https://github.com/django/django/commit/bd062445cffd3f6cc6dcd20d13e2abed818fa173</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/4.0/releases/security\">https://docs.djangoproject.com/en/4.0/releases/security</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20220915-0008\">https://security.netapp.com/advisory/ntap-20220915-0008</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2022/aug/03/security-releases\">https://www.djangoproject.com/weblog/2022/aug/03/security-releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8x94-hmjh-97hq\">https://github.com/advisories/GHSA-8x94-hmjh-97hq</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8x94-hmjh-97hq",
            "title": "[Django] Django vulnerable to Reflected File Download attack ",
            "date_modified": "2024-09-03T14:59:11.000Z",
            "date_published": "2022-08-11T14:49:12.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8x94-hmjh-97hq"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A vulnerability in corydolphin/flask-cors version 4.0.1 allows the <code>Access-Control-Allow-Private-Network</code> CORS header to be set to true by default, without any configuration option. This behavior can expose private network resources to unauthorized external access, leading to significant security risks such as data breaches, unauthorized access to sensitive information, and potential network intrusions.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-6221\">https://nvd.nist.gov/vuln/detail/CVE-2024-6221</a></li>\n<li><a href=\"https://huntr.com/bounties/a42935fc-6f57-4818-bca4-3d528235df4d\">https://huntr.com/bounties/a42935fc-6f57-4818-bca4-3d528235df4d</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/flask-cors/PYSEC-2024-71.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/flask-cors/PYSEC-2024-71.yaml</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/issues/362\">https://github.com/corydolphin/flask-cors/issues/362</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/pull/363\">https://github.com/corydolphin/flask-cors/pull/363</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/pull/368\">https://github.com/corydolphin/flask-cors/pull/368</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/commit/c8514760cf03fcce16d77f6db7007aad429c4548\">https://github.com/corydolphin/flask-cors/commit/c8514760cf03fcce16d77f6db7007aad429c4548</a></li>\n<li><a href=\"https://github.com/corydolphin/flask-cors/releases\">https://github.com/corydolphin/flask-cors/releases</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-hxwh-jpp2-84pm\">https://github.com/advisories/GHSA-hxwh-jpp2-84pm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-hxwh-jpp2-84pm",
            "title": "[flask-cors] Flask-CORS allows the `Access-Control-Allow-Private-Network` CORS header to be set to true by default",
            "date_modified": "2024-09-03T14:44:53.000Z",
            "date_published": "2024-08-18T21:31:07.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-hxwh-jpp2-84pm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>spam</code> project on PyPI was taken over via user account compromise via a phishing attack and a new malicious release made which contained code which some environment variables and downloaded and ran malware at install time</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/spam/PYSEC-2022-251.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/spam/PYSEC-2022-251.yaml</a></li>\n<li><a href=\"https://twitter.com/pypi/status/1562442207079976966\">https://twitter.com/pypi/status/1562442207079976966</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-2r6g-7r83-jg72\">https://github.com/advisories/GHSA-2r6g-7r83-jg72</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-2r6g-7r83-jg72",
            "title": "[spam] `spam` project on PyPI compromised, malicious releases made",
            "date_modified": "2024-08-30T23:37:37.000Z",
            "date_published": "2024-08-30T23:37:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-2r6g-7r83-jg72"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>spam</code> project on PyPI was taken over via user account compromise via a phishing attack and a new malicious release made which contained code which some environment variables and downloaded and ran malware at install time</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/spam/PYSEC-2022-251.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/spam/PYSEC-2022-251.yaml</a></li>\n<li><a href=\"https://twitter.com/pypi/status/1562442207079976966\">https://twitter.com/pypi/status/1562442207079976966</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-2r6g-7r83-jg72\">https://github.com/advisories/GHSA-2r6g-7r83-jg72</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-2r6g-7r83-jg72",
            "title": "[spam] `spam` project on PyPI compromised, malicious releases made",
            "date_modified": "2024-08-30T23:37:37.000Z",
            "date_published": "2024-08-30T23:37:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-2r6g-7r83-jg72"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>In Gentoo Portage before 3.0.47, there is missing PGP validation of executed code: the standalone emerge-webrsync downloads a .gpgsig file but does not perform signature verification.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-20021\">https://nvd.nist.gov/vuln/detail/CVE-2016-20021</a></li>\n<li><a href=\"https://bugs.gentoo.org/597800\">https://bugs.gentoo.org/597800</a></li>\n<li><a href=\"https://gitweb.gentoo.org/proj/portage.git/tree/NEWS\">https://gitweb.gentoo.org/proj/portage.git/tree/NEWS</a></li>\n<li><a href=\"https://wiki.gentoo.org/wiki/Portage\">https://wiki.gentoo.org/wiki/Portage</a></li>\n<li><a href=\"https://github.com/gentoo/portage/commit/28cd240fb23d880b8641a058831c6762db71c3e2\">https://github.com/gentoo/portage/commit/28cd240fb23d880b8641a058831c6762db71c3e2</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/portage/PYSEC-2024-10.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/portage/PYSEC-2024-10.yaml</a></li>\n<li><a href=\"https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=5b3c80502e96406b4b175e2ee79eb65f3f3cd9f6\">https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=5b3c80502e96406b4b175e2ee79eb65f3f3cd9f6</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pw5x-x5jw-ccmh\">https://github.com/advisories/GHSA-pw5x-x5jw-ccmh</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pw5x-x5jw-ccmh",
            "title": "[portage] Gentoo Portage missing PGP validation of executed code",
            "date_modified": "2024-08-30T23:37:36.000Z",
            "date_published": "2024-01-12T03:30:49.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pw5x-x5jw-ccmh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A HTTP/2 implementation built using any version of the Python priority library prior to version 1.2.0 could be targeted by a malicious peer by having that peer assign priority information for every possible HTTP/2 stream ID. The priority tree would happily continue to store the priority information for each stream, and would therefore allocate unbounded amounts of memory. Attempting to actually use a tree like this would also cause extremely high CPU usage to maintain the tree.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-6580\">https://nvd.nist.gov/vuln/detail/CVE-2016-6580</a></li>\n<li><a href=\"https://python-hyper.org/priority/en/latest/security/CVE-2016-6580.html\">https://python-hyper.org/priority/en/latest/security/CVE-2016-6580.html</a></li>\n<li><a href=\"https://github.com/python-hyper/priority/commit/7d01a7dc4db83bce50f20d47caf4f37b403a3ecd\">https://github.com/python-hyper/priority/commit/7d01a7dc4db83bce50f20d47caf4f37b403a3ecd</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/priority/PYSEC-2017-93.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/priority/PYSEC-2017-93.yaml</a></li>\n<li><a href=\"https://web.archive.org/web/20160806004329/http://www.securityfocus.com/bid/92311\">https://web.archive.org/web/20160806004329/http://www.securityfocus.com/bid/92311</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h3q4-6j7f-r24c\">https://github.com/advisories/GHSA-h3q4-6j7f-r24c</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h3q4-6j7f-r24c",
            "title": "[priority] priority vulnerable to denial of service",
            "date_modified": "2024-08-30T23:37:26.000Z",
            "date_published": "2022-05-17T03:02:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h3q4-6j7f-r24c"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>opencv-python versions before v4.8.1.78 bundled libwebp binaries in wheels that are vulnerable to CVE-2023-4863. opencv-python v4.8.1.78 upgrades the bundled libwebp binary to v1.3.2.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-4863\">https://nvd.nist.gov/vuln/detail/CVE-2023-4863</a></li>\n<li><a href=\"https://github.com/opencv/opencv/pull/24274\">https://github.com/opencv/opencv/pull/24274</a></li>\n<li><a href=\"https://github.com/opencv/opencv/commit/687fc11626901cff09d2b3b5f331fd59190ad4c7\">https://github.com/opencv/opencv/commit/687fc11626901cff09d2b3b5f331fd59190ad4c7</a></li>\n<li><a href=\"https://github.com/opencv/opencv/wiki/ChangeLog#version481\">https://github.com/opencv/opencv/wiki/ChangeLog#version481</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/opencv-python/PYSEC-2023-183.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/opencv-python/PYSEC-2023-183.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-qr4w-53vh-m672\">https://github.com/advisories/GHSA-qr4w-53vh-m672</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-qr4w-53vh-m672",
            "title": "[opencv-python] opencv-python bundled libwebp binaries in wheels that are vulnerable to CVE-2023-4863",
            "date_modified": "2024-08-30T23:37:22.000Z",
            "date_published": "2024-08-30T23:37:20.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-qr4w-53vh-m672"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}