{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>When provided with a URL containing many <code>@</code> characters in the authority component the authority regular expression exhibits catastrophic backtracking causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The issue has been fixed in urllib3 v1.26.5.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503\">CVE-2021-33503</a></li>\n<li><a href=\"https://jvn.jp/en/vu/JVNVU92413403/\">JVNVU#92413403 (English)</a></li>\n<li><a href=\"https://jvn.jp/vu/JVNVU92413403/\">JVNVU#92413403 (Japanese)</a></li>\n<li><a href=\"https://github.com/urllib3/urllib3/releases/tag/1.26.5\">urllib3 v1.26.5</a></li>\n</ul>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Ask in our <a href=\"https://discord.gg/urllib3\">community Discord</a></li>\n<li>Email <a href=\"mailto:sethmichaellarson@gmail.com\">sethmichaellarson@gmail.com</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/urllib3/urllib3/security/advisories/GHSA-q2q7-5pp4-w6pg\">https://github.com/urllib3/urllib3/security/advisories/GHSA-q2q7-5pp4-w6pg</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-33503\">https://nvd.nist.gov/vuln/detail/CVE-2021-33503</a></li>\n<li><a href=\"https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec\">https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-q2q7-5pp4-w6pg\">https://github.com/advisories/GHSA-q2q7-5pp4-w6pg</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FMUGWEAUYGGHTPPXT6YBD53WYXQGVV73/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FMUGWEAUYGGHTPPXT6YBD53WYXQGVV73/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6SCV7ZNAHS3E6PBFLJGENCDRDRWRZZ6W/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6SCV7ZNAHS3E6PBFLJGENCDRDRWRZZ6W/</a></li>\n<li><a href=\"https://security.gentoo.org/glsa/202107-36\">https://security.gentoo.org/glsa/202107-36</a></li>\n<li><a href=\"https://www.oracle.com/security-alerts/cpuoct2021.html\">https://www.oracle.com/security-alerts/cpuoct2021.html</a></li>\n<li><a href=\"https://github.com/urllib3/urllib3/commit/5b047b645f5f93900d5e2fc31230848c25eb1f5f#diff-52026d639119bf1e0364836b4e8a18bd9ed3c95c6ba39b26534a5057a65e35bbR65\">https://github.com/urllib3/urllib3/commit/5b047b645f5f93900d5e2fc31230848c25eb1f5f#diff-52026d639119bf1e0364836b4e8a18bd9ed3c95c6ba39b26534a5057a65e35bbR65</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-q2q7-5pp4-w6pg",
            "title": "[urllib3] Catastrophic backtracking in URL authority parser when passed URL containing many @ characters",
            "date_modified": "2022-09-20T19:20:15.000Z",
            "date_published": "2021-06-01T21:19:32.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-q2q7-5pp4-w6pg"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The exotel (aka exotel-py) package in PyPI as of 0.1.6 includes a code execution backdoor inserted by a third party. Users should downgrade to version 0.1.5 to avoid the problem.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-38792\">https://nvd.nist.gov/vuln/detail/CVE-2022-38792</a></li>\n<li><a href=\"https://github.com/sarathsp06/exotel-py/issues/10\">https://github.com/sarathsp06/exotel-py/issues/10</a></li>\n<li><a href=\"https://github.com/jertel/elastalert2/pull/931\">https://github.com/jertel/elastalert2/pull/931</a></li>\n<li><a href=\"https://inspector.pypi.io/project/exotel/0.1.6/packages/8b/ed/9ebeb34d4adb9b01151d73ccfde9c1cb2d629c3b146953c8727559a65446/exotel-0.1.6.tar.gz/exotel-0.1.6/setup.py\">https://inspector.pypi.io/project/exotel/0.1.6/packages/8b/ed/9ebeb34d4adb9b01151d73ccfde9c1cb2d629c3b146953c8727559a65446/exotel-0.1.6.tar.gz/exotel-0.1.6/setup.py</a></li>\n<li><a href=\"https://pypi.org/project/exotel/\">https://pypi.org/project/exotel/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-cv6j-9835-p7fh\">https://github.com/advisories/GHSA-cv6j-9835-p7fh</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-cv6j-9835-p7fh",
            "title": "[exotel] exotel-py 0.1.6 includes code execution backdoor inserted by a third party",
            "date_modified": "2022-09-20T17:10:39.000Z",
            "date_published": "2022-08-28T00:00:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-cv6j-9835-p7fh"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>rdiffweb prior to 2.4.3 is vulnerable to Cross-Site Request Forgery (CSRF). While adding SSH public keys to the profile, the server accepts the GET request, which results in adding an SSH public key to the profile and leads to unauthorized access to the system and backups. Version 2.4.3 contains a patch for this issue.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-3221\">https://nvd.nist.gov/vuln/detail/CVE-2022-3221</a></li>\n<li><a href=\"https://github.com/ikus060/rdiffweb/commit/9125f5a2d918fed0f3fc1c86fa94cd1779ed9f73\">https://github.com/ikus060/rdiffweb/commit/9125f5a2d918fed0f3fc1c86fa94cd1779ed9f73</a></li>\n<li><a href=\"https://huntr.dev/bounties/1fa1aac9-b16a-4a70-a7da-960b3908ae1d\">https://huntr.dev/bounties/1fa1aac9-b16a-4a70-a7da-960b3908ae1d</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/rdiffweb/PYSEC-2022-278.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/rdiffweb/PYSEC-2022-278.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vq4h-xrwc-m639\">https://github.com/advisories/GHSA-vq4h-xrwc-m639</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vq4h-xrwc-m639",
            "title": "[rdiffweb] rdiffweb CSRF vulnerability in profile's SSH keys can lead to unauthorized access",
            "date_modified": "2022-09-19T20:24:54.000Z",
            "date_published": "2022-09-16T00:00:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vq4h-xrwc-m639"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Poetry prior to v1.1.9 was discovered to contain an untrusted search path which causes the application to behave in unexpected ways when users execute Poetry commands in a directory containing malicious content. This vulnerability occurs when the application is ran on Windows OS.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-26184\">https://nvd.nist.gov/vuln/detail/CVE-2022-26184</a></li>\n<li><a href=\"https://github.com/python-poetry/poetry-core/pull/205/commits/fa9cb6f358ae840885c700f954317f34838caba7\">https://github.com/python-poetry/poetry-core/pull/205/commits/fa9cb6f358ae840885c700f954317f34838caba7</a></li>\n<li><a href=\"https://github.com/python-poetry/poetry/releases/tag/1.1.9\">https://github.com/python-poetry/poetry/releases/tag/1.1.9</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/poetry/PYSEC-2022-234.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/poetry/PYSEC-2022-234.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xr2c-5w89-63pv\">https://github.com/advisories/GHSA-xr2c-5w89-63pv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xr2c-5w89-63pv",
            "title": "[poetry] Poetry before v1.1.9 contains Untrusted Search Path",
            "date_modified": "2022-09-19T20:18:28.000Z",
            "date_published": "2022-03-23T00:00:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xr2c-5w89-63pv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Matrix Synapse before 1.5.0 mishandles signature checking on some federation APIs. Events sent over /send_join, /send_leave, and /invite may not be correctly signed, or may not come from the expected servers.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-18835\">https://nvd.nist.gov/vuln/detail/CVE-2019-18835</a></li>\n<li><a href=\"https://github.com/matrix-org/synapse/pull/6262\">https://github.com/matrix-org/synapse/pull/6262</a></li>\n<li><a href=\"https://github.com/matrix-org/synapse/releases/tag/v1.5.0\">https://github.com/matrix-org/synapse/releases/tag/v1.5.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-cppw-2mf8-qpm5\">https://github.com/advisories/GHSA-cppw-2mf8-qpm5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-cppw-2mf8-qpm5",
            "title": "[matrix-synapse] Improper Verification of Cryptographic Signature in matrix-synapse",
            "date_modified": "2022-09-19T19:32:11.000Z",
            "date_published": "2022-05-24T22:01:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-cppw-2mf8-qpm5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>If <code>Save</code> or <code>SaveSlices</code> is run over tensors of an unsupported <code>dtype</code>, it results in a <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nfilename = tf.constant(\"\")\ntensor_names = tf.constant(\"\")\n# Save\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=-2021), tf.uint64)\ntf.raw_ops.Save(filename=filename, tensor_names=tensor_names, data=data, )\n# SaveSlices\nshapes_and_slices = tf.constant(\"\")\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=9712), tf.uint32)\ntf.raw_ops.SaveSlices(filename=filename, tensor_names=tensor_names, shapes_and_slices=shapes_and_slices, data=data, )\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4",
            "title": "[tensorflow-gpu] TensorFlow vulnerable to `CHECK` fail in `Save` and `SaveSlices`",
            "date_modified": "2022-09-16T22:31:15.000Z",
            "date_published": "2022-09-16T22:31:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>If <code>Save</code> or <code>SaveSlices</code> is run over tensors of an unsupported <code>dtype</code>, it results in a <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nfilename = tf.constant(\"\")\ntensor_names = tf.constant(\"\")\n# Save\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=-2021), tf.uint64)\ntf.raw_ops.Save(filename=filename, tensor_names=tensor_names, data=data, )\n# SaveSlices\nshapes_and_slices = tf.constant(\"\")\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=9712), tf.uint32)\ntf.raw_ops.SaveSlices(filename=filename, tensor_names=tensor_names, shapes_and_slices=shapes_and_slices, data=data, )\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4",
            "title": "[tensorflow-gpu] TensorFlow vulnerable to `CHECK` fail in `Save` and `SaveSlices`",
            "date_modified": "2022-09-16T22:31:15.000Z",
            "date_published": "2022-09-16T22:31:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>If <code>Save</code> or <code>SaveSlices</code> is run over tensors of an unsupported <code>dtype</code>, it results in a <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nfilename = tf.constant(\"\")\ntensor_names = tf.constant(\"\")\n# Save\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=-2021), tf.uint64)\ntf.raw_ops.Save(filename=filename, tensor_names=tensor_names, data=data, )\n# SaveSlices\nshapes_and_slices = tf.constant(\"\")\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=9712), tf.uint32)\ntf.raw_ops.SaveSlices(filename=filename, tensor_names=tensor_names, shapes_and_slices=shapes_and_slices, data=data, )\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4",
            "title": "[tensorflow-gpu] TensorFlow vulnerable to `CHECK` fail in `Save` and `SaveSlices`",
            "date_modified": "2022-09-16T22:31:15.000Z",
            "date_published": "2022-09-16T22:31:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>If <code>Save</code> or <code>SaveSlices</code> is run over tensors of an unsupported <code>dtype</code>, it results in a <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nfilename = tf.constant(\"\")\ntensor_names = tf.constant(\"\")\n# Save\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=-2021), tf.uint64)\ntf.raw_ops.Save(filename=filename, tensor_names=tensor_names, data=data, )\n# SaveSlices\nshapes_and_slices = tf.constant(\"\")\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=9712), tf.uint32)\ntf.raw_ops.SaveSlices(filename=filename, tensor_names=tensor_names, shapes_and_slices=shapes_and_slices, data=data, )\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4",
            "title": "[tensorflow-cpu] TensorFlow vulnerable to `CHECK` fail in `Save` and `SaveSlices`",
            "date_modified": "2022-09-16T22:31:15.000Z",
            "date_published": "2022-09-16T22:31:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>If <code>Save</code> or <code>SaveSlices</code> is run over tensors of an unsupported <code>dtype</code>, it results in a <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nfilename = tf.constant(\"\")\ntensor_names = tf.constant(\"\")\n# Save\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=-2021), tf.uint64)\ntf.raw_ops.Save(filename=filename, tensor_names=tensor_names, data=data, )\n# SaveSlices\nshapes_and_slices = tf.constant(\"\")\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=9712), tf.uint32)\ntf.raw_ops.SaveSlices(filename=filename, tensor_names=tensor_names, shapes_and_slices=shapes_and_slices, data=data, )\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4",
            "title": "[tensorflow-cpu] TensorFlow vulnerable to `CHECK` fail in `Save` and `SaveSlices`",
            "date_modified": "2022-09-16T22:31:15.000Z",
            "date_published": "2022-09-16T22:31:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>If <code>Save</code> or <code>SaveSlices</code> is run over tensors of an unsupported <code>dtype</code>, it results in a <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nfilename = tf.constant(\"\")\ntensor_names = tf.constant(\"\")\n# Save\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=-2021), tf.uint64)\ntf.raw_ops.Save(filename=filename, tensor_names=tensor_names, data=data, )\n# SaveSlices\nshapes_and_slices = tf.constant(\"\")\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=9712), tf.uint32)\ntf.raw_ops.SaveSlices(filename=filename, tensor_names=tensor_names, shapes_and_slices=shapes_and_slices, data=data, )\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4",
            "title": "[tensorflow-cpu] TensorFlow vulnerable to `CHECK` fail in `Save` and `SaveSlices`",
            "date_modified": "2022-09-16T22:31:15.000Z",
            "date_published": "2022-09-16T22:31:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>If <code>Save</code> or <code>SaveSlices</code> is run over tensors of an unsupported <code>dtype</code>, it results in a <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nfilename = tf.constant(\"\")\ntensor_names = tf.constant(\"\")\n# Save\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=-2021), tf.uint64)\ntf.raw_ops.Save(filename=filename, tensor_names=tensor_names, data=data, )\n# SaveSlices\nshapes_and_slices = tf.constant(\"\")\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=9712), tf.uint32)\ntf.raw_ops.SaveSlices(filename=filename, tensor_names=tensor_names, shapes_and_slices=shapes_and_slices, data=data, )\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4",
            "title": "[tensorflow] TensorFlow vulnerable to `CHECK` fail in `Save` and `SaveSlices`",
            "date_modified": "2022-09-16T22:31:15.000Z",
            "date_published": "2022-09-16T22:31:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>If <code>Save</code> or <code>SaveSlices</code> is run over tensors of an unsupported <code>dtype</code>, it results in a <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nfilename = tf.constant(\"\")\ntensor_names = tf.constant(\"\")\n# Save\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=-2021), tf.uint64)\ntf.raw_ops.Save(filename=filename, tensor_names=tensor_names, data=data, )\n# SaveSlices\nshapes_and_slices = tf.constant(\"\")\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=9712), tf.uint32)\ntf.raw_ops.SaveSlices(filename=filename, tensor_names=tensor_names, shapes_and_slices=shapes_and_slices, data=data, )\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4",
            "title": "[tensorflow] TensorFlow vulnerable to `CHECK` fail in `Save` and `SaveSlices`",
            "date_modified": "2022-09-16T22:31:15.000Z",
            "date_published": "2022-09-16T22:31:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>If <code>Save</code> or <code>SaveSlices</code> is run over tensors of an unsupported <code>dtype</code>, it results in a <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nfilename = tf.constant(\"\")\ntensor_names = tf.constant(\"\")\n# Save\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=-2021), tf.uint64)\ntf.raw_ops.Save(filename=filename, tensor_names=tensor_names, data=data, )\n# SaveSlices\nshapes_and_slices = tf.constant(\"\")\ndata = tf.cast(tf.random.uniform(shape=[1], minval=-10000, maxval=10000, dtype=tf.int64, seed=9712), tf.uint32)\ntf.raw_ops.SaveSlices(filename=filename, tensor_names=tensor_names, shapes_and_slices=shapes_and_slices, data=data, )\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4\">https://github.com/tensorflow/tensorflow/commit/5dd7b86b84a864b834c6fa3d7f9f51c87efa99d4</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-m6vp-8q9j-whx4\">https://github.com/advisories/GHSA-m6vp-8q9j-whx4</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4",
            "title": "[tensorflow] TensorFlow vulnerable to `CHECK` fail in `Save` and `SaveSlices`",
            "date_modified": "2022-09-16T22:31:15.000Z",
            "date_published": "2022-09-16T22:31:14.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-m6vp-8q9j-whx4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>ParameterizedTruncatedNormal</code> assumes <code>shape</code> is of type <code>int32</code>. A valid <code>shape</code> of type <code>int64</code> results in a mismatched type <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nseed = 1618\nseed2 = 0\nshape = tf.random.uniform(shape=[3], minval=-10000, maxval=10000, dtype=tf.int64, seed=4894)\nmeans = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nstdevs = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nminvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nmaxvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\ntf.raw_ops.ParameterizedTruncatedNormal(shape=shape, means=means, stdevs=stdevs, minvals=minvals, maxvals=maxvals, seed=seed, seed2=seed2)\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">72180be03447a10810edca700cbc9af690dfeb51</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5",
            "title": "[tensorflow-gpu] TensorFlow vulnerable to `CHECK` fail in `ParameterizedTruncatedNormal`",
            "date_modified": "2022-09-16T22:30:30.000Z",
            "date_published": "2022-09-16T22:30:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>ParameterizedTruncatedNormal</code> assumes <code>shape</code> is of type <code>int32</code>. A valid <code>shape</code> of type <code>int64</code> results in a mismatched type <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nseed = 1618\nseed2 = 0\nshape = tf.random.uniform(shape=[3], minval=-10000, maxval=10000, dtype=tf.int64, seed=4894)\nmeans = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nstdevs = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nminvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nmaxvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\ntf.raw_ops.ParameterizedTruncatedNormal(shape=shape, means=means, stdevs=stdevs, minvals=minvals, maxvals=maxvals, seed=seed, seed2=seed2)\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">72180be03447a10810edca700cbc9af690dfeb51</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5",
            "title": "[tensorflow-gpu] TensorFlow vulnerable to `CHECK` fail in `ParameterizedTruncatedNormal`",
            "date_modified": "2022-09-16T22:30:30.000Z",
            "date_published": "2022-09-16T22:30:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>ParameterizedTruncatedNormal</code> assumes <code>shape</code> is of type <code>int32</code>. A valid <code>shape</code> of type <code>int64</code> results in a mismatched type <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nseed = 1618\nseed2 = 0\nshape = tf.random.uniform(shape=[3], minval=-10000, maxval=10000, dtype=tf.int64, seed=4894)\nmeans = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nstdevs = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nminvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nmaxvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\ntf.raw_ops.ParameterizedTruncatedNormal(shape=shape, means=means, stdevs=stdevs, minvals=minvals, maxvals=maxvals, seed=seed, seed2=seed2)\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">72180be03447a10810edca700cbc9af690dfeb51</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5",
            "title": "[tensorflow-gpu] TensorFlow vulnerable to `CHECK` fail in `ParameterizedTruncatedNormal`",
            "date_modified": "2022-09-16T22:30:30.000Z",
            "date_published": "2022-09-16T22:30:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>ParameterizedTruncatedNormal</code> assumes <code>shape</code> is of type <code>int32</code>. A valid <code>shape</code> of type <code>int64</code> results in a mismatched type <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nseed = 1618\nseed2 = 0\nshape = tf.random.uniform(shape=[3], minval=-10000, maxval=10000, dtype=tf.int64, seed=4894)\nmeans = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nstdevs = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nminvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nmaxvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\ntf.raw_ops.ParameterizedTruncatedNormal(shape=shape, means=means, stdevs=stdevs, minvals=minvals, maxvals=maxvals, seed=seed, seed2=seed2)\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">72180be03447a10810edca700cbc9af690dfeb51</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5",
            "title": "[tensorflow-cpu] TensorFlow vulnerable to `CHECK` fail in `ParameterizedTruncatedNormal`",
            "date_modified": "2022-09-16T22:30:30.000Z",
            "date_published": "2022-09-16T22:30:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>ParameterizedTruncatedNormal</code> assumes <code>shape</code> is of type <code>int32</code>. A valid <code>shape</code> of type <code>int64</code> results in a mismatched type <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nseed = 1618\nseed2 = 0\nshape = tf.random.uniform(shape=[3], minval=-10000, maxval=10000, dtype=tf.int64, seed=4894)\nmeans = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nstdevs = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nminvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nmaxvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\ntf.raw_ops.ParameterizedTruncatedNormal(shape=shape, means=means, stdevs=stdevs, minvals=minvals, maxvals=maxvals, seed=seed, seed2=seed2)\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">72180be03447a10810edca700cbc9af690dfeb51</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5",
            "title": "[tensorflow-cpu] TensorFlow vulnerable to `CHECK` fail in `ParameterizedTruncatedNormal`",
            "date_modified": "2022-09-16T22:30:30.000Z",
            "date_published": "2022-09-16T22:30:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>ParameterizedTruncatedNormal</code> assumes <code>shape</code> is of type <code>int32</code>. A valid <code>shape</code> of type <code>int64</code> results in a mismatched type <code>CHECK</code> fail that can be used to trigger a denial of service attack.</p>\n<pre><code class=\"language-python\">import tensorflow as tf\nseed = 1618\nseed2 = 0\nshape = tf.random.uniform(shape=[3], minval=-10000, maxval=10000, dtype=tf.int64, seed=4894)\nmeans = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nstdevs = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nminvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\nmaxvals = tf.random.uniform(shape=[3, 3, 3], minval=-10000, maxval=10000, dtype=tf.float32, seed=-2971)\ntf.raw_ops.ParameterizedTruncatedNormal(shape=shape, means=means, stdevs=stdevs, minvals=minvals, maxvals=maxvals, seed=seed, seed2=seed2)\n</code></pre>\n<h3 id=\"patches\">Patches</h3>\n<p>We have patched the issue in GitHub commit <a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">72180be03447a10810edca700cbc9af690dfeb51</a>.</p>\n<p>The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>Please consult <a href=\"https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md\">our security guide</a> for more information regarding the security model and how to contact us with issues and questions.</p>\n<h3 id=\"attribution\">Attribution</h3>\n<p>This vulnerability has been reported by Di Jin, Secure Systems Labs, Brown University</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/tensorflow/tensorflow/security/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51\">https://github.com/tensorflow/tensorflow/commit/72180be03447a10810edca700cbc9af690dfeb51</a></li>\n<li><a href=\"https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0\">https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p2xf-8hgm-hpw5\">https://github.com/advisories/GHSA-p2xf-8hgm-hpw5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5",
            "title": "[tensorflow-cpu] TensorFlow vulnerable to `CHECK` fail in `ParameterizedTruncatedNormal`",
            "date_modified": "2022-09-16T22:30:30.000Z",
            "date_published": "2022-09-16T22:30:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p2xf-8hgm-hpw5"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}