{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>pretalx 2.3.1 before 2.3.2 allows path traversal in HTML export (a non-default feature). Organizers can trigger the overwriting (with the standard pretalx 404 page content) of an arbitrary file.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-28458\">https://nvd.nist.gov/vuln/detail/CVE-2023-28458</a></li>\n<li><a href=\"https://github.com/pretalx/pretalx/commit/60722c43cf975f319e94102e6bff320723776890\">https://github.com/pretalx/pretalx/commit/60722c43cf975f319e94102e6bff320723776890</a></li>\n<li><a href=\"https://github.com/pretalx/pretalx/releases/tag/v2.3.2\">https://github.com/pretalx/pretalx/releases/tag/v2.3.2</a></li>\n<li><a href=\"https://pretalx.com/p/news/security-release-232/\">https://pretalx.com/p/news/security-release-232/</a></li>\n<li><a href=\"https://www.sonarsource.com/blog/pretalx-vulnerabilities-how-to-get-accepted-at-every-conference/\">https://www.sonarsource.com/blog/pretalx-vulnerabilities-how-to-get-accepted-at-every-conference/</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-23fx-92m6-4f2g\">https://github.com/advisories/GHSA-23fx-92m6-4f2g</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-23fx-92m6-4f2g",
            "title": "[pretalx] pretalx allows path traversal in HTML export",
            "date_modified": "2023-04-21T19:39:53.000Z",
            "date_published": "2023-04-20T21:33:27.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-23fx-92m6-4f2g"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>When saving the contents of a rich text field in the admin interface, Wagtail does not apply server-side checks to ensure that link URLs use a valid protocol. A malicious user with access to the admin interface could thus craft a POST request to publish content with <code>javascript:</code> URLs containing arbitrary code. The vulnerability is not exploitable by an ordinary site visitor without access to the Wagtail admin.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Patched versions have been released as Wagtail 2.11.7 (for the LTS 2.11 branch) and Wagtail 2.12.4 (for the current 2.12 branch).</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>For sites that cannot easily upgrade to a current supported version, the vulnerability can be patched by adding the following code to a <code>wagtail_hooks.py</code> module in any installed app:</p>\n<pre><code class=\"language-python\">from draftjs_exporter.dom import DOM\nfrom wagtail.admin.rich_text.converters.html_to_contentstate import ExternalLinkElementHandler, PageLinkElementHandler\nfrom wagtail.core import hooks\nfrom wagtail.core.whitelist import check_url\n\n\ndef link_entity(props):\n    id_ = props.get('id')\n    link_props = {}\n\n    if id_ is not None:\n        link_props['linktype'] = 'page'\n        link_props['id'] = id_\n    else:\n        link_props['href'] = check_url(props.get('url'))\n\n    return DOM.create_element('a', link_props, props['children'])\n\n\n@hooks.register('register_rich_text_features', order=1)\ndef register_link(features):\n    features.register_converter_rule('contentstate', 'link', {\n        'from_database_format': {\n            'a[href]': ExternalLinkElementHandler('LINK'),\n            'a[linktype=\"page\"]': PageLinkElementHandler('LINK'),\n        },\n        'to_database_format': {\n            'entity_decorators': {'LINK': link_entity}\n        }\n    })\n</code></pre>\n<h3 id=\"acknowledgements\">Acknowledgements</h3>\n<p>Many thanks to Kevin Breen for reporting this issue.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Visit Wagtail's <a href=\"https://docs.wagtail.io/en/stable/support.html\">support channels</a></li>\n<li>Email us at <a href=\"mailto:security@wagtail.io\">security@wagtail.io</a> (if you wish to send encrypted email, the public key ID is <code>0x6ba1e1a86e0f8ce8</code>)</li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/wagtail/wagtail/security/advisories/GHSA-wq5h-f9p5-q7fx\">https://github.com/wagtail/wagtail/security/advisories/GHSA-wq5h-f9p5-q7fx</a></li>\n<li><a href=\"https://pypi.org/project/wagtail/\">https://pypi.org/project/wagtail/</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29434\">https://nvd.nist.gov/vuln/detail/CVE-2021-29434</a></li>\n<li><a href=\"https://github.com/wagtail/wagtail/commit/5c7a60977cba478f6a35390ba98cffc2bd41c8a4\">https://github.com/wagtail/wagtail/commit/5c7a60977cba478f6a35390ba98cffc2bd41c8a4</a></li>\n<li><a href=\"https://github.com/wagtail/wagtail/commit/915f6ed2bd7d53154103cc4424a0f18695cdad6c\">https://github.com/wagtail/wagtail/commit/915f6ed2bd7d53154103cc4424a0f18695cdad6c</a></li>\n<li><a href=\"https://github.com/wagtail/wagtail/compare/v2.11.6...v2.11.7\">https://github.com/wagtail/wagtail/compare/v2.11.6...v2.11.7</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wq5h-f9p5-q7fx\">https://github.com/advisories/GHSA-wq5h-f9p5-q7fx</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wq5h-f9p5-q7fx",
            "title": "[wagtail] Improper validation of URLs ('Cross-site Scripting') in Wagtail rich text fields",
            "date_modified": "2023-04-21T15:24:44.000Z",
            "date_published": "2021-04-20T14:02:30.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wq5h-f9p5-q7fx"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>When saving the contents of a rich text field in the admin interface, Wagtail does not apply server-side checks to ensure that link URLs use a valid protocol. A malicious user with access to the admin interface could thus craft a POST request to publish content with <code>javascript:</code> URLs containing arbitrary code. The vulnerability is not exploitable by an ordinary site visitor without access to the Wagtail admin.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Patched versions have been released as Wagtail 2.11.7 (for the LTS 2.11 branch) and Wagtail 2.12.4 (for the current 2.12 branch).</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>For sites that cannot easily upgrade to a current supported version, the vulnerability can be patched by adding the following code to a <code>wagtail_hooks.py</code> module in any installed app:</p>\n<pre><code class=\"language-python\">from draftjs_exporter.dom import DOM\nfrom wagtail.admin.rich_text.converters.html_to_contentstate import ExternalLinkElementHandler, PageLinkElementHandler\nfrom wagtail.core import hooks\nfrom wagtail.core.whitelist import check_url\n\n\ndef link_entity(props):\n    id_ = props.get('id')\n    link_props = {}\n\n    if id_ is not None:\n        link_props['linktype'] = 'page'\n        link_props['id'] = id_\n    else:\n        link_props['href'] = check_url(props.get('url'))\n\n    return DOM.create_element('a', link_props, props['children'])\n\n\n@hooks.register('register_rich_text_features', order=1)\ndef register_link(features):\n    features.register_converter_rule('contentstate', 'link', {\n        'from_database_format': {\n            'a[href]': ExternalLinkElementHandler('LINK'),\n            'a[linktype=\"page\"]': PageLinkElementHandler('LINK'),\n        },\n        'to_database_format': {\n            'entity_decorators': {'LINK': link_entity}\n        }\n    })\n</code></pre>\n<h3 id=\"acknowledgements\">Acknowledgements</h3>\n<p>Many thanks to Kevin Breen for reporting this issue.</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Visit Wagtail's <a href=\"https://docs.wagtail.io/en/stable/support.html\">support channels</a></li>\n<li>Email us at <a href=\"mailto:security@wagtail.io\">security@wagtail.io</a> (if you wish to send encrypted email, the public key ID is <code>0x6ba1e1a86e0f8ce8</code>)</li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/wagtail/wagtail/security/advisories/GHSA-wq5h-f9p5-q7fx\">https://github.com/wagtail/wagtail/security/advisories/GHSA-wq5h-f9p5-q7fx</a></li>\n<li><a href=\"https://pypi.org/project/wagtail/\">https://pypi.org/project/wagtail/</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-29434\">https://nvd.nist.gov/vuln/detail/CVE-2021-29434</a></li>\n<li><a href=\"https://github.com/wagtail/wagtail/commit/5c7a60977cba478f6a35390ba98cffc2bd41c8a4\">https://github.com/wagtail/wagtail/commit/5c7a60977cba478f6a35390ba98cffc2bd41c8a4</a></li>\n<li><a href=\"https://github.com/wagtail/wagtail/commit/915f6ed2bd7d53154103cc4424a0f18695cdad6c\">https://github.com/wagtail/wagtail/commit/915f6ed2bd7d53154103cc4424a0f18695cdad6c</a></li>\n<li><a href=\"https://github.com/wagtail/wagtail/compare/v2.11.6...v2.11.7\">https://github.com/wagtail/wagtail/compare/v2.11.6...v2.11.7</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wq5h-f9p5-q7fx\">https://github.com/advisories/GHSA-wq5h-f9p5-q7fx</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wq5h-f9p5-q7fx",
            "title": "[wagtail] Improper validation of URLs ('Cross-site Scripting') in Wagtail rich text fields",
            "date_modified": "2023-04-21T15:24:44.000Z",
            "date_published": "2021-04-20T14:02:30.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wq5h-f9p5-q7fx"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django version 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-13254\">https://nvd.nist.gov/vuln/detail/CVE-2020-13254</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.0/releases/security/\">https://docs.djangoproject.com/en/3.0/releases/security/</a></li>\n<li><a href=\"https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ\">https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2020/jun/03/security-releases/\">https://www.djangoproject.com/weblog/2020/jun/03/security-releases/</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html\">https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20200611-0002/\">https://security.netapp.com/advisory/ntap-20200611-0002/</a></li>\n<li><a href=\"https://usn.ubuntu.com/4381-1/\">https://usn.ubuntu.com/4381-1/</a></li>\n<li><a href=\"https://usn.ubuntu.com/4381-2/\">https://usn.ubuntu.com/4381-2/</a></li>\n<li><a href=\"https://www.debian.org/security/2020/dsa-4705\">https://www.debian.org/security/2020/dsa-4705</a></li>\n<li><a href=\"https://www.oracle.com/security-alerts/cpujan2021.html\">https://www.oracle.com/security-alerts/cpujan2021.html</a></li>\n<li><a href=\"https://github.com/django/django/commit/07e59caa02831c4569bbebb9eb773bdd9cb4b206\">https://github.com/django/django/commit/07e59caa02831c4569bbebb9eb773bdd9cb4b206</a></li>\n<li><a href=\"https://github.com/django/django/commit/84b2da5552e100ae3294f564f6c862fef8d0e693\">https://github.com/django/django/commit/84b2da5552e100ae3294f564f6c862fef8d0e693</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wpjr-j57x-wxfw\">https://github.com/advisories/GHSA-wpjr-j57x-wxfw</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wpjr-j57x-wxfw",
            "title": "[django] Data leakage via cache key collision in Django",
            "date_modified": "2023-04-21T15:20:25.000Z",
            "date_published": "2020-06-05T16:20:44.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wpjr-j57x-wxfw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Django version 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-13254\">https://nvd.nist.gov/vuln/detail/CVE-2020-13254</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/3.0/releases/security/\">https://docs.djangoproject.com/en/3.0/releases/security/</a></li>\n<li><a href=\"https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ\">https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2020/jun/03/security-releases/\">https://www.djangoproject.com/weblog/2020/jun/03/security-releases/</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html\">https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20200611-0002/\">https://security.netapp.com/advisory/ntap-20200611-0002/</a></li>\n<li><a href=\"https://usn.ubuntu.com/4381-1/\">https://usn.ubuntu.com/4381-1/</a></li>\n<li><a href=\"https://usn.ubuntu.com/4381-2/\">https://usn.ubuntu.com/4381-2/</a></li>\n<li><a href=\"https://www.debian.org/security/2020/dsa-4705\">https://www.debian.org/security/2020/dsa-4705</a></li>\n<li><a href=\"https://www.oracle.com/security-alerts/cpujan2021.html\">https://www.oracle.com/security-alerts/cpujan2021.html</a></li>\n<li><a href=\"https://github.com/django/django/commit/07e59caa02831c4569bbebb9eb773bdd9cb4b206\">https://github.com/django/django/commit/07e59caa02831c4569bbebb9eb773bdd9cb4b206</a></li>\n<li><a href=\"https://github.com/django/django/commit/84b2da5552e100ae3294f564f6c862fef8d0e693\">https://github.com/django/django/commit/84b2da5552e100ae3294f564f6c862fef8d0e693</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wpjr-j57x-wxfw\">https://github.com/advisories/GHSA-wpjr-j57x-wxfw</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wpjr-j57x-wxfw",
            "title": "[django] Data leakage via cache key collision in Django",
            "date_modified": "2023-04-21T15:20:25.000Z",
            "date_published": "2020-06-05T16:20:44.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wpjr-j57x-wxfw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, version 4.1.0 (corresponds with OpenCV-Python version 4.1.2.30). A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-5064\">https://nvd.nist.gov/vuln/detail/CVE-2019-5064</a></li>\n<li><a href=\"https://github.com/opencv/opencv/issues/15857\">https://github.com/opencv/opencv/issues/15857</a></li>\n<li><a href=\"https://github.com/opencv/opencv-python/releases/tag/32\">https://github.com/opencv/opencv-python/releases/tag/32</a></li>\n<li><a href=\"https://github.com/opencv/opencv/releases/tag/4.2.0\">https://github.com/opencv/opencv/releases/tag/4.2.0</a></li>\n<li><a href=\"https://talosintelligence.com/vulnerability_reports/TALOS-2019-0853\">https://talosintelligence.com/vulnerability_reports/TALOS-2019-0853</a></li>\n<li><a href=\"https://www.oracle.com/security-alerts/cpuApr2021.html\">https://www.oracle.com/security-alerts/cpuApr2021.html</a></li>\n<li><a href=\"https://www.oracle.com//security-alerts/cpujul2021.html\">https://www.oracle.com//security-alerts/cpujul2021.html</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-q799-q27x-vp7w\">https://github.com/advisories/GHSA-q799-q27x-vp7w</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-q799-q27x-vp7w",
            "title": "[opencv-contrib-python-headless] Out-of-bounds Write in OpenCV",
            "date_modified": "2023-04-21T15:01:19.000Z",
            "date_published": "2021-10-12T22:23:21.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-q799-q27x-vp7w"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django 1.11.x before 1.11.19, 2.0.x before 2.0.11, and 2.1.x before 2.1.6 allows Uncontrolled Memory Consumption via a malicious attacker-supplied value to the django.utils.numberformat.format() function.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-6975\">https://nvd.nist.gov/vuln/detail/CVE-2019-6975</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security/\">https://docs.djangoproject.com/en/dev/releases/security/</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ\">https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Jul/10\">https://seclists.org/bugtraq/2019/Jul/10</a></li>\n<li><a href=\"https://usn.ubuntu.com/3890-1/\">https://usn.ubuntu.com/3890-1/</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4476\">https://www.debian.org/security/2019/dsa-4476</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/feb/11/security-releases/\">https://www.djangoproject.com/weblog/2019/feb/11/security-releases/</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2019/02/11/1\">https://www.openwall.com/lists/oss-security/2019/02/11/1</a></li>\n<li><a href=\"https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227\">https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227</a></li>\n<li><a href=\"https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676\">https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676</a></li>\n<li><a href=\"https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3\">https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3</a></li>\n<li><a href=\"https://web.archive.org/web/20200227084713/http://www.securityfocus.com/bid/106964\">https://web.archive.org/web/20200227084713/http://www.securityfocus.com/bid/106964</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wh4h-v3f2-r2pp\">https://github.com/advisories/GHSA-wh4h-v3f2-r2pp</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wh4h-v3f2-r2pp",
            "title": "[django] Uncontrolled Memory Consumption in Django",
            "date_modified": "2023-04-21T14:58:13.000Z",
            "date_published": "2019-02-12T15:36:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wh4h-v3f2-r2pp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django 1.11.x before 1.11.19, 2.0.x before 2.0.11, and 2.1.x before 2.1.6 allows Uncontrolled Memory Consumption via a malicious attacker-supplied value to the django.utils.numberformat.format() function.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-6975\">https://nvd.nist.gov/vuln/detail/CVE-2019-6975</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security/\">https://docs.djangoproject.com/en/dev/releases/security/</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ\">https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Jul/10\">https://seclists.org/bugtraq/2019/Jul/10</a></li>\n<li><a href=\"https://usn.ubuntu.com/3890-1/\">https://usn.ubuntu.com/3890-1/</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4476\">https://www.debian.org/security/2019/dsa-4476</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/feb/11/security-releases/\">https://www.djangoproject.com/weblog/2019/feb/11/security-releases/</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2019/02/11/1\">https://www.openwall.com/lists/oss-security/2019/02/11/1</a></li>\n<li><a href=\"https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227\">https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227</a></li>\n<li><a href=\"https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676\">https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676</a></li>\n<li><a href=\"https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3\">https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3</a></li>\n<li><a href=\"https://web.archive.org/web/20200227084713/http://www.securityfocus.com/bid/106964\">https://web.archive.org/web/20200227084713/http://www.securityfocus.com/bid/106964</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wh4h-v3f2-r2pp\">https://github.com/advisories/GHSA-wh4h-v3f2-r2pp</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wh4h-v3f2-r2pp",
            "title": "[django] Uncontrolled Memory Consumption in Django",
            "date_modified": "2023-04-21T14:58:13.000Z",
            "date_published": "2019-02-12T15:36:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wh4h-v3f2-r2pp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django 1.11.x before 1.11.19, 2.0.x before 2.0.11, and 2.1.x before 2.1.6 allows Uncontrolled Memory Consumption via a malicious attacker-supplied value to the django.utils.numberformat.format() function.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-6975\">https://nvd.nist.gov/vuln/detail/CVE-2019-6975</a></li>\n<li><a href=\"https://docs.djangoproject.com/en/dev/releases/security/\">https://docs.djangoproject.com/en/dev/releases/security/</a></li>\n<li><a href=\"https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ\">https://groups.google.com/forum/#!topic/django-announce/WTwEAprR0IQ</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/66WMXHGBXD7GSM3PEXVCMCAGLMQYHZCU/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVXDOVCXLD74SHR2BENGCE2OOYYYWJHZ/</a></li>\n<li><a href=\"https://seclists.org/bugtraq/2019/Jul/10\">https://seclists.org/bugtraq/2019/Jul/10</a></li>\n<li><a href=\"https://usn.ubuntu.com/3890-1/\">https://usn.ubuntu.com/3890-1/</a></li>\n<li><a href=\"https://www.debian.org/security/2019/dsa-4476\">https://www.debian.org/security/2019/dsa-4476</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2019/feb/11/security-releases/\">https://www.djangoproject.com/weblog/2019/feb/11/security-releases/</a></li>\n<li><a href=\"https://www.openwall.com/lists/oss-security/2019/02/11/1\">https://www.openwall.com/lists/oss-security/2019/02/11/1</a></li>\n<li><a href=\"https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227\">https://github.com/django/django/commit/0bbb560183fabf0533289700845dafa94951f227</a></li>\n<li><a href=\"https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676\">https://github.com/django/django/commit/1f42f82566c9d2d73aff1c42790d6b1b243f7676</a></li>\n<li><a href=\"https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3\">https://github.com/django/django/commit/40cd19055773705301c3428ed5e08a036d2091f3</a></li>\n<li><a href=\"https://web.archive.org/web/20200227084713/http://www.securityfocus.com/bid/106964\">https://web.archive.org/web/20200227084713/http://www.securityfocus.com/bid/106964</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wh4h-v3f2-r2pp\">https://github.com/advisories/GHSA-wh4h-v3f2-r2pp</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wh4h-v3f2-r2pp",
            "title": "[django] Uncontrolled Memory Consumption in Django",
            "date_modified": "2023-04-21T14:58:13.000Z",
            "date_published": "2019-02-12T15:36:37.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wh4h-v3f2-r2pp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>django-js-reverse (aka Django JS Reverse) before 0.9.1 has XSS via js_reverse_inline.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2019-15486\">https://nvd.nist.gov/vuln/detail/CVE-2019-15486</a></li>\n<li><a href=\"https://github.com/ierror/django-js-reverse/compare/v0.9.0...v0.9.1\">https://github.com/ierror/django-js-reverse/compare/v0.9.0...v0.9.1</a></li>\n<li><a href=\"https://github.com/ierror/django-js-reverse/pull/81\">https://github.com/ierror/django-js-reverse/pull/81</a></li>\n<li><a href=\"https://github.com/ierror/django-js-reverse/commit/78d6aff2276f2d341f643b095515f8aaba5e67c2\">https://github.com/ierror/django-js-reverse/commit/78d6aff2276f2d341f643b095515f8aaba5e67c2</a></li>\n<li><a href=\"https://github.com/ierror/django-js-reverse/commit/a3b57d1e4424e2fadabcd526d170c4868d55159c\">https://github.com/ierror/django-js-reverse/commit/a3b57d1e4424e2fadabcd526d170c4868d55159c</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vx6v-2rg6-865h\">https://github.com/advisories/GHSA-vx6v-2rg6-865h</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vx6v-2rg6-865h",
            "title": "[django-js-reverse] Cross-site Scripting in django-js-reverse",
            "date_modified": "2023-04-20T21:51:45.000Z",
            "date_published": "2019-08-27T17:39:33.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vx6v-2rg6-865h"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p><code>rucio-webui</code> installations of the <code>1.26</code> release line potentially leak the contents of cookies to other sessions within a wsgi container. Impact is that Rucio authentication tokens are leaked to other users accessing the <code>webui</code> within a close timeframe, thus allowing users to access the <code>webui</code> with the leaked authentication token. Privileges are therefore also escalated.</p>\n<p>Rucio server / daemons are not affected by this issue, it is isolated to the webui.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>This issue is fixed in the <code>1.26.7</code> release of the <code>rucio-webui</code>.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>Installation of the <code>1.25.7</code> <code>webui</code> release. The <code>1.25</code> and previous webui release lines are not affected by this issue.</p>\n<h3 id=\"references\">References</h3>\n<p><a href=\"https://github.com/rucio/rucio/issues/4928\">https://github.com/rucio/rucio/issues/4928</a></p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/rucio/rucio/security/advisories/GHSA-v988-828w-xvf2\">https://github.com/rucio/rucio/security/advisories/GHSA-v988-828w-xvf2</a></li>\n<li><a href=\"https://github.com/rucio/rucio/issues/4810\">https://github.com/rucio/rucio/issues/4810</a></li>\n<li><a href=\"https://github.com/rucio/rucio/issues/4928\">https://github.com/rucio/rucio/issues/4928</a></li>\n<li><a href=\"https://github.com/rucio/rucio/releases/tag/1.26.7\">https://github.com/rucio/rucio/releases/tag/1.26.7</a></li>\n<li><a href=\"https://github.com/rucio/rucio/commit/8f832404ae88d6300e17d7e706b40fe58e0df90c\">https://github.com/rucio/rucio/commit/8f832404ae88d6300e17d7e706b40fe58e0df90c</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-v988-828w-xvf2\">https://github.com/advisories/GHSA-v988-828w-xvf2</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-v988-828w-xvf2",
            "title": "[rucio-webui] Authentication Bypass Using an Alternate Path or Channel and Authentication Bypass by Primary Weakness in rucio-webui",
            "date_modified": "2023-04-20T21:43:05.000Z",
            "date_published": "2021-10-22T16:21:07.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-v988-828w-xvf2"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An issue was discovered in Mailman Core before 3.3.5. An attacker with access to the REST API could use timing attacks to determine the value of the configured REST API password and then make arbitrary REST API calls. The REST API is bound to localhost by default, limiting the ability for attackers to exploit this, but can optionally be made to listen on other interfaces.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-34337\">https://nvd.nist.gov/vuln/detail/CVE-2021-34337</a></li>\n<li><a href=\"https://gitlab.com/mailman/mailman/-/commit/e4a39488c4510fcad8851217f10e7337a196bb51\">https://gitlab.com/mailman/mailman/-/commit/e4a39488c4510fcad8851217f10e7337a196bb51</a></li>\n<li><a href=\"https://gitlab.com/mailman/mailman/-/tags\">https://gitlab.com/mailman/mailman/-/tags</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-2jg5-xgvv-4wq7\">https://github.com/advisories/GHSA-2jg5-xgvv-4wq7</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-2jg5-xgvv-4wq7",
            "title": "[mailman] Mailman Core vulnerable to timing attacks",
            "date_modified": "2023-04-18T13:05:09.000Z",
            "date_published": "2023-04-15T21:30:16.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-2jg5-xgvv-4wq7"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>membership_tool.py in Plone before 4.2.3 and 4.3 before beta 1 allows remote attackers to enumerate user account names via a crafted URL.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2012-5497\">https://nvd.nist.gov/vuln/detail/CVE-2012-5497</a></li>\n<li><a href=\"https://github.com/plone/Products.CMFPlone/blob/4.2.3/docs/CHANGES.txt\">https://github.com/plone/Products.CMFPlone/blob/4.2.3/docs/CHANGES.txt</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2014-1194.html\">http://rhn.redhat.com/errata/RHSA-2014-1194.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2012/11/10/1\">http://www.openwall.com/lists/oss-security/2012/11/10/1</a></li>\n<li><a href=\"https://access.redhat.com/errata/RHSA-2014:1194\">https://access.redhat.com/errata/RHSA-2014:1194</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/CVE-2012-5497\">https://access.redhat.com/security/cve/CVE-2012-5497</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=874681\">https://bugzilla.redhat.com/show_bug.cgi?id=874681</a></li>\n<li><a href=\"https://github.com/plone/Products.CMFPlone/commit/a9479a5b38646fe0b0a9066ee46de9c18de32bfa\">https://github.com/plone/Products.CMFPlone/commit/a9479a5b38646fe0b0a9066ee46de9c18de32bfa</a></li>\n<li><a href=\"https://github.com/plone/Products.CMFPlone/commit/c3a98f4e6cf26501485de9c8354c49afdea21df8\">https://github.com/plone/Products.CMFPlone/commit/c3a98f4e6cf26501485de9c8354c49afdea21df8</a></li>\n<li><a href=\"https://web.archive.org/web/20131103175056/https://plone.org/products/plone/security/advisories/20121106/13\">https://web.archive.org/web/20131103175056/https://plone.org/products/plone/security/advisories/20121106/13</a></li>\n<li><a href=\"https://web.archive.org/web/20131114082527/https://plone.org/products/plone-hotfix/releases/20121106\">https://web.archive.org/web/20131114082527/https://plone.org/products/plone-hotfix/releases/20121106</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-683w-84m7-p8pw\">https://github.com/advisories/GHSA-683w-84m7-p8pw</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-683w-84m7-p8pw",
            "title": "[plone] User account enumeration via crafted URL",
            "date_modified": "2023-04-17T21:56:36.000Z",
            "date_published": "2022-05-17T04:31:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-683w-84m7-p8pw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-1747\">https://nvd.nist.gov/vuln/detail/CVE-2020-1747</a></li>\n<li><a href=\"https://github.com/yaml/pyyaml/pull/386\">https://github.com/yaml/pyyaml/pull/386</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747\">https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html\">http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html\">http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html</a></li>\n<li><a href=\"https://www.oracle.com/security-alerts/cpujul2022.html\">https://www.oracle.com/security-alerts/cpujul2022.html</a></li>\n<li><a href=\"https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0\">https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-6757-jp84-gxfx\">https://github.com/advisories/GHSA-6757-jp84-gxfx</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-6757-jp84-gxfx",
            "title": "[pyyaml] Improper Input Validation in PyYAML",
            "date_modified": "2023-04-17T21:42:46.000Z",
            "date_published": "2021-04-20T16:14:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-6757-jp84-gxfx"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection') vulnerability in Apache Airflow Hive Provider, Apache Airflow allows an attacker to execute arbtrary commands in the task execution context, without write access to DAG files. This issue affects Hive Provider versions prior to 4.1.0. It also impacts any Apache Airflow versions prior to 2.3.0 in case HIve Provider is installed (Hive Provider 4.1.0 can only be installed for Airflow 2.3.0+). Note that you need to manually install the HIve Provider version 4.1.0 in order to get rid of the vulnerability on top of Airflow 2.3.0+ version that has lower version of the Hive Provider installed).</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-41131\">https://nvd.nist.gov/vuln/detail/CVE-2022-41131</a></li>\n<li><a href=\"https://github.com/apache/airflow/pull/27647\">https://github.com/apache/airflow/pull/27647</a></li>\n<li><a href=\"https://lists.apache.org/thread/wwo3qp0z8gv54yzn7hr04wy4n8gb0vhl\">https://lists.apache.org/thread/wwo3qp0z8gv54yzn7hr04wy4n8gb0vhl</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-cm43-f2pv-6v68\">https://github.com/advisories/GHSA-cm43-f2pv-6v68</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-cm43-f2pv-6v68",
            "title": "[apache-airflow-providers-apache-hive] OS Command Injection in Apache Airflow",
            "date_modified": "2023-04-14T19:28:17.000Z",
            "date_published": "2022-11-22T12:30:22.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-cm43-f2pv-6v68"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An exponential ReDoS (Regular Expression Denial of Service) can be triggered in the cleo PyPI package, when an attacker is able to supply arbitrary input to the Table.set_rows method.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-42966\">https://nvd.nist.gov/vuln/detail/CVE-2022-42966</a></li>\n<li><a href=\"https://research.jfrog.com/vulnerabilities/cleo-redos-xray-257186\">https://research.jfrog.com/vulnerabilities/cleo-redos-xray-257186</a></li>\n<li><a href=\"https://github.com/python-poetry/cleo/pull/285\">https://github.com/python-poetry/cleo/pull/285</a></li>\n<li><a href=\"https://github.com/python-poetry/cleo/commit/b5b9a04d2caf58bf7cf94eb7ae4a1ebbe60ea455\">https://github.com/python-poetry/cleo/commit/b5b9a04d2caf58bf7cf94eb7ae4a1ebbe60ea455</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-2p9h-ccw7-33gf\">https://github.com/advisories/GHSA-2p9h-ccw7-33gf</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-2p9h-ccw7-33gf",
            "title": "[cleo] cleo is vulnerable to Regular Expression Denial of Service (ReDoS)",
            "date_modified": "2023-04-14T19:23:49.000Z",
            "date_published": "2022-11-10T12:01:17.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-2p9h-ccw7-33gf"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The Pallets Project flask version Before 0.12.3 contains a CWE-20: Improper Input Validation vulnerability in flask that can result in Large amount of memory usage possibly leading to denial of service. This attack appear to be exploitable via Attacker provides JSON data in incorrect encoding. This vulnerability appears to have been fixed in 0.12.3.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2018-1000656\">https://nvd.nist.gov/vuln/detail/CVE-2018-1000656</a></li>\n<li><a href=\"https://github.com/pallets/flask/pull/2691\">https://github.com/pallets/flask/pull/2691</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-562c-5r94-xh97\">https://github.com/advisories/GHSA-562c-5r94-xh97</a></li>\n<li><a href=\"https://github.com/pallets/flask/releases/tag/0.12.3\">https://github.com/pallets/flask/releases/tag/0.12.3</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2019/08/msg00025.html\">https://lists.debian.org/debian-lts-announce/2019/08/msg00025.html</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20190221-0001/\">https://security.netapp.com/advisory/ntap-20190221-0001/</a></li>\n<li><a href=\"https://usn.ubuntu.com/4378-1/\">https://usn.ubuntu.com/4378-1/</a></li>\n<li><a href=\"https://github.com/pallets/flask/commit/b178e89e4456e777b1a7ac6d7199052d0dfdbbbe\">https://github.com/pallets/flask/commit/b178e89e4456e777b1a7ac6d7199052d0dfdbbbe</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-562c-5r94-xh97",
            "title": "[flask] The Pallets Project in flask that can result in large amount of memory usage",
            "date_modified": "2023-04-14T17:19:15.000Z",
            "date_published": "2018-08-23T19:10:40.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-562c-5r94-xh97"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>An XML external entity (XXE) injection in PyWPS before 4.5.0 allows an attacker to view files on the application server filesystem by assigning a path to the entity. OWSLib 0.24.1 may also be affected.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-39371\">https://nvd.nist.gov/vuln/detail/CVE-2021-39371</a></li>\n<li><a href=\"https://github.com/geopython/OWSLib/issues/790\">https://github.com/geopython/OWSLib/issues/790</a></li>\n<li><a href=\"https://github.com/geopython/pywps/pull/616\">https://github.com/geopython/pywps/pull/616</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2021/09/msg00001.html\">https://lists.debian.org/debian-lts-announce/2021/09/msg00001.html</a></li>\n<li><a href=\"https://github.com/geopython/pywps/commit/7d6b26a2e931df2feca0b7fb24f4d01610825aee\">https://github.com/geopython/pywps/commit/7d6b26a2e931df2feca0b7fb24f4d01610825aee</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-p9wf-3xpg-c9g5\">https://github.com/advisories/GHSA-p9wf-3xpg-c9g5</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-p9wf-3xpg-c9g5",
            "title": "[pywps] XML External Entity Injection in PyWPS",
            "date_modified": "2023-04-14T01:34:41.000Z",
            "date_published": "2021-09-02T17:11:13.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-p9wf-3xpg-c9g5"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Apache Airflow Docker's Provider prior to 3.0.0 shipped with an example DAG that was vulnerable to (authenticated) remote code exploit of code on the Airflow worker host. Disable loading of example DAGs or upgrade apache-airflow-providers-docker to 3.0.0 or above.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-38362\">https://nvd.nist.gov/vuln/detail/CVE-2022-38362</a></li>\n<li><a href=\"https://lists.apache.org/thread/614p38nf4gbk8xhvnskj9b1sqo2dknkb\">https://lists.apache.org/thread/614p38nf4gbk8xhvnskj9b1sqo2dknkb</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2022/08/16/1\">http://www.openwall.com/lists/oss-security/2022/08/16/1</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-746v-hfh2-xphm\">https://github.com/advisories/GHSA-746v-hfh2-xphm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-746v-hfh2-xphm",
            "title": "[apache-airflow-providers-docker] Remote code execution in Apache Airflow Docker's Provider",
            "date_modified": "2023-04-13T17:53:43.000Z",
            "date_published": "2022-08-17T00:00:21.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-746v-hfh2-xphm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Allegro Tech BigFlow prior to 1.6.0 is vulnerable to Missing SSL Certificate Validation.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-25392\">https://nvd.nist.gov/vuln/detail/CVE-2023-25392</a></li>\n<li><a href=\"https://github.com/allegro/bigflow/pull/357\">https://github.com/allegro/bigflow/pull/357</a></li>\n<li><a href=\"https://lutrasecurity.com/en/articles/cve-2023-25392/\">https://lutrasecurity.com/en/articles/cve-2023-25392/</a></li>\n<li><a href=\"https://github.com/allegro/bigflow/commit/4ce197ff99bd38693dea59ab5e9b781fbcef4276\">https://github.com/allegro/bigflow/commit/4ce197ff99bd38693dea59ab5e9b781fbcef4276</a></li>\n<li><a href=\"https://github.com/allegro/bigflow/commit/7e956661f76907594e8c82e8fb0af76dbea2a0fc\">https://github.com/allegro/bigflow/commit/7e956661f76907594e8c82e8fb0af76dbea2a0fc</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-w6q2-48ch-fj26\">https://github.com/advisories/GHSA-w6q2-48ch-fj26</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-w6q2-48ch-fj26",
            "title": "[bigflow] Allegro Tech BigFlow vulnerable to Missing SSL Certificate Validation",
            "date_modified": "2023-04-14T20:30:44.000Z",
            "date_published": "2023-04-10T15:30:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-w6q2-48ch-fj26"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}