{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<p>django.contrib.sessions in Django before 1.2.7 and 1.3.x before 1.3.1, when session data is stored in the cache, uses the root namespace for both session identifiers and application-data keys, which allows remote attackers to modify a session by triggering use of a key that is equal to that session's identifier.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4136\">https://nvd.nist.gov/vuln/detail/CVE-2011-4136</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-x88j-93vc-wpmp\">https://github.com/advisories/GHSA-x88j-93vc-wpmp</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/ac7c3a110f906e4dfed3a17451bf7fd9fcb81296\">https://github.com/django/django/commit/ac7c3a110f906e4dfed3a17451bf7fd9fcb81296</a></li>\n<li><a href=\"https://github.com/django/django/commit/fbe2eead2fa9d808658ca582241bcacb02618840\">https://github.com/django/django/commit/fbe2eead2fa9d808658ca582241bcacb02618840</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-1.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-1.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-x88j-93vc-wpmp",
            "title": "[Django] Session manipulation in Django",
            "date_modified": "2024-09-16T23:04:00.000Z",
            "date_published": "2018-07-23T19:52:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-x88j-93vc-wpmp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>django.contrib.sessions in Django before 1.2.7 and 1.3.x before 1.3.1, when session data is stored in the cache, uses the root namespace for both session identifiers and application-data keys, which allows remote attackers to modify a session by triggering use of a key that is equal to that session's identifier.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4136\">https://nvd.nist.gov/vuln/detail/CVE-2011-4136</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-x88j-93vc-wpmp\">https://github.com/advisories/GHSA-x88j-93vc-wpmp</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/ac7c3a110f906e4dfed3a17451bf7fd9fcb81296\">https://github.com/django/django/commit/ac7c3a110f906e4dfed3a17451bf7fd9fcb81296</a></li>\n<li><a href=\"https://github.com/django/django/commit/fbe2eead2fa9d808658ca582241bcacb02618840\">https://github.com/django/django/commit/fbe2eead2fa9d808658ca582241bcacb02618840</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-1.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-1.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-x88j-93vc-wpmp",
            "title": "[Django] Session manipulation in Django",
            "date_modified": "2024-09-16T23:04:00.000Z",
            "date_published": "2018-07-23T19:52:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-x88j-93vc-wpmp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>emitters.py in Django Piston before 0.2.3 and 0.2.x before 0.2.2.1 does not properly deserialize YAML data, which allows remote attackers to execute arbitrary Python code via vectors related to the yaml.load method.</p>\n<p>Django Tastypie has a very similar vulnerability.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4103\">https://nvd.nist.gov/vuln/detail/CVE-2011-4103</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=750658\">https://bugzilla.redhat.com/show_bug.cgi?id=750658</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-pvhp-v9qp-xf5r\">https://github.com/advisories/GHSA-pvhp-v9qp-xf5r</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2344\">http://www.debian.org/security/2011/dsa-2344</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2011/11/01/10\">http://www.openwall.com/lists/oss-security/2011/11/01/10</a></li>\n<li><a href=\"https://bitbucket.org/jespern/django-piston/commits/91bdaec89543\">https://bitbucket.org/jespern/django-piston/commits/91bdaec89543</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django-piston/PYSEC-2014-24.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django-piston/PYSEC-2014-24.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/nov/01/piston-and-tastypie-security-releases\">https://www.djangoproject.com/weblog/2011/nov/01/piston-and-tastypie-security-releases</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-pvhp-v9qp-xf5r",
            "title": "[django-piston] Django-piston and Django-tastypie do not properly deserialize YAML data",
            "date_modified": "2024-09-16T23:00:29.000Z",
            "date_published": "2018-07-23T19:50:48.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-pvhp-v9qp-xf5r"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross-site scripting (XSS) vulnerability in Django 1.2.x before 1.2.2 allows remote attackers to inject arbitrary web script or HTML via a csrfmiddlewaretoken (aka csrf_token) cookie.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2010-3082\">https://nvd.nist.gov/vuln/detail/CVE-2010-3082</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=632239\">https://bugzilla.redhat.com/show_bug.cgi?id=632239</a></li>\n<li><a href=\"https://exchange.xforce.ibmcloud.com/vulnerabilities/61729\">https://exchange.xforce.ibmcloud.com/vulnerabilities/61729</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-fxpg-gg9g-76gj\">https://github.com/advisories/GHSA-fxpg-gg9g-76gj</a></li>\n<li><a href=\"http://marc.info/?l=oss-security&amp;m=128403961700444&amp;w=2\">http://marc.info/?l=oss-security&amp;m=128403961700444&amp;w=2</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-1004-1\">http://www.ubuntu.com/usn/USN-1004-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/7f84657b6b2243cc787bdb9f296710c8d13ad0bd\">https://github.com/django/django/commit/7f84657b6b2243cc787bdb9f296710c8d13ad0bd</a></li>\n<li><a href=\"http://www.djangoproject.com/weblog/2010/sep/08/security-release\">http://www.djangoproject.com/weblog/2010/sep/08/security-release</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2010-12.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2010-12.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-fxpg-gg9g-76gj",
            "title": "[Django] Cross-site scripting in django",
            "date_modified": "2024-09-16T22:57:34.000Z",
            "date_published": "2018-07-23T19:52:42.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-fxpg-gg9g-76gj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The administrative interface in django.contrib.admin in Django before 1.1.3, 1.2.x before 1.2.4, and 1.3.x before 1.3 beta 1 does not properly restrict use of the query string to perform certain object filtering, which allows remote authenticated users to obtain sensitive information via a series of requests containing regular expressions, as demonstrated by a created_by__password__regex parameter.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2010-4534\">https://nvd.nist.gov/vuln/detail/CVE-2010-4534</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=665373\">https://bugzilla.redhat.com/show_bug.cgi?id=665373</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-fwr5-q9rx-294f\">https://github.com/advisories/GHSA-fwr5-q9rx-294f</a></li>\n<li><a href=\"http://archives.neohapsis.com/archives/fulldisclosure/2010-12/0580.html\">http://archives.neohapsis.com/archives/fulldisclosure/2010-12/0580.html</a></li>\n<li><a href=\"http://code.djangoproject.com/changeset/15031\">http://code.djangoproject.com/changeset/15031</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053041.html\">http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053041.html</a></li>\n<li><a href=\"http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053072.html\">http://lists.fedoraproject.org/pipermail/package-announce/2011-January/053072.html</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2010/12/23/4\">http://www.openwall.com/lists/oss-security/2010/12/23/4</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2011/01/03/5\">http://www.openwall.com/lists/oss-security/2011/01/03/5</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-1040-1\">http://www.ubuntu.com/usn/USN-1040-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/17084839fd7e267da5729f2a27753322b9d415a0\">https://github.com/django/django/commit/17084839fd7e267da5729f2a27753322b9d415a0</a></li>\n<li><a href=\"https://github.com/django/django/commit/85207a245bf09fdebe486b4c7bbcb65300f2a693\">https://github.com/django/django/commit/85207a245bf09fdebe486b4c7bbcb65300f2a693</a></li>\n<li><a href=\"http://evilpacket.net/2010/dec/22/information-leakage-django-administrative-interfac\">http://evilpacket.net/2010/dec/22/information-leakage-django-administrative-interfac</a></li>\n<li><a href=\"http://ngenuity-is.com/advisories/2010/dec/22/information-leakage-in-django-administrative-inter\">http://ngenuity-is.com/advisories/2010/dec/22/information-leakage-in-django-administrative-inter</a></li>\n<li><a href=\"http://www.djangoproject.com/weblog/2010/dec/22/security\">http://www.djangoproject.com/weblog/2010/dec/22/security</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-8.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-8.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-fwr5-q9rx-294f",
            "title": "[Django] Improper query string handling in Django",
            "date_modified": "2024-09-16T22:56:44.000Z",
            "date_published": "2018-07-23T19:51:40.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-fwr5-q9rx-294f"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A flaw was found in Ansible, where sensitive information stored in Ansible Vault files can be exposed in plaintext during the execution of a playbook. This occurs when using tasks such as include_vars to load vaulted variables without setting the no_log: true parameter, resulting in sensitive data being printed in the playbook output or logs. This can lead to the unintentional disclosure of secrets like passwords or API keys, compromising security and potentially allowing unauthorized access or actions.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2024-8775\">https://nvd.nist.gov/vuln/detail/CVE-2024-8775</a></li>\n<li><a href=\"https://access.redhat.com/security/cve/CVE-2024-8775\">https://access.redhat.com/security/cve/CVE-2024-8775</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=2312119\">https://bugzilla.redhat.com/show_bug.cgi?id=2312119</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-jpxc-vmjf-9fcj\">https://github.com/advisories/GHSA-jpxc-vmjf-9fcj</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-jpxc-vmjf-9fcj",
            "title": "[ansible-core] Ansible vulnerable to Insertion of Sensitive Information into Log File",
            "date_modified": "2024-09-16T22:55:01.000Z",
            "date_published": "2024-09-16T14:37:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-jpxc-vmjf-9fcj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Django before 1.2.7 and 1.3.x before 1.3.1 uses a request's HTTP Host header to construct a full URL in certain circumstances, which allows remote attackers to conduct cache poisoning attacks via a crafted request.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4139\">https://nvd.nist.gov/vuln/detail/CVE-2011-4139</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/2f7fadc38efa58ac0a8f93f936b82332a199f396\">https://github.com/django/django/commit/2f7fadc38efa58ac0a8f93f936b82332a199f396</a></li>\n<li><a href=\"https://github.com/django/django/commit/c613af4d6485586c79d692b70a9acac429f3ca9d\">https://github.com/django/django/commit/c613af4d6485586c79d692b70a9acac429f3ca9d</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-4.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-4.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rm2j-x595-q9cj\">https://github.com/advisories/GHSA-rm2j-x595-q9cj</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rm2j-x595-q9cj",
            "title": "[Django] Django Vulnerable to Cache Poisoning",
            "date_modified": "2024-09-16T22:35:48.000Z",
            "date_published": "2022-05-14T03:49:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rm2j-x595-q9cj"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4137\">https://nvd.nist.gov/vuln/detail/CVE-2011-4137</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3jqw-crqj-w8qw\">https://github.com/advisories/GHSA-3jqw-crqj-w8qw</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/15/5\">http://openwall.com/lists/oss-security/2011/09/15/5</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0\">https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0</a></li>\n<li><a href=\"https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930\">https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-2.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-2.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw",
            "title": "[Django] Denial of service in django",
            "date_modified": "2024-09-16T22:34:23.000Z",
            "date_published": "2018-07-23T19:51:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 relies on Python libraries that attempt access to an arbitrary URL with no timeout, which allows remote attackers to cause a denial of service (resource consumption) via a URL associated with (1) a slow response, (2) a completed TCP connection with no application data sent, or (3) a large amount of application data, a related issue to CVE-2011-1521.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4137\">https://nvd.nist.gov/vuln/detail/CVE-2011-4137</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3jqw-crqj-w8qw\">https://github.com/advisories/GHSA-3jqw-crqj-w8qw</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/15/5\">http://openwall.com/lists/oss-security/2011/09/15/5</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0\">https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0</a></li>\n<li><a href=\"https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930\">https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-2.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-2.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw",
            "title": "[Django] Denial of service in django",
            "date_modified": "2024-09-16T22:34:23.000Z",
            "date_published": "2018-07-23T19:51:35.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3jqw-crqj-w8qw"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The <code>verify_exists</code> functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's validity through a HEAD request, but then uses a GET request for the new target URL in the case of a redirect, which might allow remote attackers to trigger arbitrary GET requests with an unintended source IP address via a crafted Location header.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4138\">https://nvd.nist.gov/vuln/detail/CVE-2011-4138</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0\">https://github.com/django/django/commit/1a76dbefdfc60e2d5954c0ba614c3d054ba9c3f0</a></li>\n<li><a href=\"https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930\">https://github.com/django/django/commit/7268f8af86186518821d775c530d5558fd726930</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-3.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-3.yaml</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-wxg3-mfph-qg9w\">https://github.com/advisories/GHSA-wxg3-mfph-qg9w</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-wxg3-mfph-qg9w",
            "title": "[Django] Django Might Allow CSRF Requests via URL Verification",
            "date_modified": "2024-09-16T22:32:03.000Z",
            "date_published": "2022-05-14T03:49:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-wxg3-mfph-qg9w"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\"</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2014-0472\">https://nvd.nist.gov/vuln/detail/CVE-2014-0472</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html\">http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2014-0456.html\">http://rhn.redhat.com/errata/RHSA-2014-0456.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2014-0457.html\">http://rhn.redhat.com/errata/RHSA-2014-0457.html</a></li>\n<li><a href=\"http://www.debian.org/security/2014/dsa-2934\">http://www.debian.org/security/2014/dsa-2934</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2169-1\">http://www.ubuntu.com/usn/USN-2169-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/2a5bcb69f42b84464b24b5c835dca6467b6aa7f1\">https://github.com/django/django/commit/2a5bcb69f42b84464b24b5c835dca6467b6aa7f1</a></li>\n<li><a href=\"https://github.com/django/django/commit/4352a50871e239ebcdf64eee6f0b88e714015c1b\">https://github.com/django/django/commit/4352a50871e239ebcdf64eee6f0b88e714015c1b</a></li>\n<li><a href=\"https://github.com/django/django/commit/c1a8c420fe4b27fb2caf5e46d23b5712fc0ac535\">https://github.com/django/django/commit/c1a8c420fe4b27fb2caf5e46d23b5712fc0ac535</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2014/apr/21/security\">https://www.djangoproject.com/weblog/2014/apr/21/security</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-1.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-1.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rvq6-mrpv-m6rm\">https://github.com/advisories/GHSA-rvq6-mrpv-m6rm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rvq6-mrpv-m6rm",
            "title": "[Django] Code Injection in Django",
            "date_modified": "2024-09-16T22:13:38.000Z",
            "date_published": "2022-05-17T03:07:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rvq6-mrpv-m6rm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The django.core.urlresolvers.reverse function in Django before 1.4.11, 1.5.x before 1.5.6, 1.6.x before 1.6.3, and 1.7.x before 1.7 beta 2 allows remote attackers to import and execute arbitrary Python modules by leveraging a view that constructs URLs using user input and a \"dotted Python path.\"</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2014-0472\">https://nvd.nist.gov/vuln/detail/CVE-2014-0472</a></li>\n<li><a href=\"http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html\">http://lists.opensuse.org/opensuse-updates/2014-09/msg00023.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2014-0456.html\">http://rhn.redhat.com/errata/RHSA-2014-0456.html</a></li>\n<li><a href=\"http://rhn.redhat.com/errata/RHSA-2014-0457.html\">http://rhn.redhat.com/errata/RHSA-2014-0457.html</a></li>\n<li><a href=\"http://www.debian.org/security/2014/dsa-2934\">http://www.debian.org/security/2014/dsa-2934</a></li>\n<li><a href=\"http://www.ubuntu.com/usn/USN-2169-1\">http://www.ubuntu.com/usn/USN-2169-1</a></li>\n<li><a href=\"https://github.com/django/django/commit/2a5bcb69f42b84464b24b5c835dca6467b6aa7f1\">https://github.com/django/django/commit/2a5bcb69f42b84464b24b5c835dca6467b6aa7f1</a></li>\n<li><a href=\"https://github.com/django/django/commit/4352a50871e239ebcdf64eee6f0b88e714015c1b\">https://github.com/django/django/commit/4352a50871e239ebcdf64eee6f0b88e714015c1b</a></li>\n<li><a href=\"https://github.com/django/django/commit/c1a8c420fe4b27fb2caf5e46d23b5712fc0ac535\">https://github.com/django/django/commit/c1a8c420fe4b27fb2caf5e46d23b5712fc0ac535</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2014/apr/21/security\">https://www.djangoproject.com/weblog/2014/apr/21/security</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-1.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2014-1.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-rvq6-mrpv-m6rm\">https://github.com/advisories/GHSA-rvq6-mrpv-m6rm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-rvq6-mrpv-m6rm",
            "title": "[Django] Code Injection in Django",
            "date_modified": "2024-09-16T22:13:38.000Z",
            "date_published": "2022-05-17T03:07:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-rvq6-mrpv-m6rm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>django-helpdesk is vulnerable to Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting').</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2021-3945\">https://nvd.nist.gov/vuln/detail/CVE-2021-3945</a></li>\n<li><a href=\"https://github.com/django-helpdesk/django-helpdesk/commit/2c7065e0c4296e0c692fb4a7ee19c7357583af30\">https://github.com/django-helpdesk/django-helpdesk/commit/2c7065e0c4296e0c692fb4a7ee19c7357583af30</a></li>\n<li><a href=\"https://huntr.dev/bounties/745f483c-70ed-441f-ab2e-7ac1305439a4\">https://huntr.dev/bounties/745f483c-70ed-441f-ab2e-7ac1305439a4</a></li>\n<li><a href=\"https://github.com/django-helpdesk/django-helpdesk/commit/44abb197120a843cce5b5fe8276e4a44b8bb2f48\">https://github.com/django-helpdesk/django-helpdesk/commit/44abb197120a843cce5b5fe8276e4a44b8bb2f48</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vx6v-xg64-pmr8\">https://github.com/advisories/GHSA-vx6v-xg64-pmr8</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django-helpdesk/PYSEC-2021-430.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django-helpdesk/PYSEC-2021-430.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vx6v-xg64-pmr8",
            "title": "[django-helpdesk] Cross-site Scripting in django-helpdesk",
            "date_modified": "2024-09-16T22:11:52.000Z",
            "date_published": "2021-11-15T23:12:41.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vx6v-xg64-pmr8"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Automatically generated <code>NumberFilter</code> instances, whose value was later converted to an integer, were subject to potential DoS from maliciously input using exponential format with sufficiently large exponents. </p>\n<h3 id=\"patches\">Patches</h3>\n<p>Version 2.4.0+ applies a <code>MaxValueValidator</code> with a a default <code>limit_value</code> of 1e50 to the form field used by <code>NumberFilter</code> instances. </p>\n<p>In addition, <code>NumberFilter</code> implements the new <code>get_max_validator()</code> which should return a configured validator instance to customise the limit, or else <code>None</code> to disable the additional validation. </p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>Users may manually apply an equivalent validator if they are not able to upgrade.  </p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in <a href=\"https://github.com/carltongibson/django-filter\">the django-filter repo</a></li>\n</ul>\n<p>Thanks to Marcin Waraksa for the report. </p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/carltongibson/django-filter/security/advisories/GHSA-x7gm-rfgv-w973\">https://github.com/carltongibson/django-filter/security/advisories/GHSA-x7gm-rfgv-w973</a></li>\n<li><a href=\"https://github.com/carltongibson/django-filter/commit/340cf7a23a2b3dcd7183f6a0d6c383e85b130d2b\">https://github.com/carltongibson/django-filter/commit/340cf7a23a2b3dcd7183f6a0d6c383e85b130d2b</a></li>\n<li><a href=\"https://github.com/carltongibson/django-filter/releases/tag/2.4.0\">https://github.com/carltongibson/django-filter/releases/tag/2.4.0</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-15225\">https://nvd.nist.gov/vuln/detail/CVE-2020-15225</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django-filter/PYSEC-2021-64.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django-filter/PYSEC-2021-64.yaml</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DPHENTRHRAYFXYPPBT7JRHZRWILRY44S\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DPHENTRHRAYFXYPPBT7JRHZRWILRY44S</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FAT2ZAEF6DM3VFSOHKB7X3ASSHGQHJAK\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FAT2ZAEF6DM3VFSOHKB7X3ASSHGQHJAK</a></li>\n<li><a href=\"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SVJ7AYU6FUSU3F653YCGW5LFD3IULRSX\">https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SVJ7AYU6FUSU3F653YCGW5LFD3IULRSX</a></li>\n<li><a href=\"https://pypi.org/project/django-filter\">https://pypi.org/project/django-filter</a></li>\n<li><a href=\"https://security.netapp.com/advisory/ntap-20210604-0010\">https://security.netapp.com/advisory/ntap-20210604-0010</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-x7gm-rfgv-w973\">https://github.com/advisories/GHSA-x7gm-rfgv-w973</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-x7gm-rfgv-w973",
            "title": "[django-filter] Potential DoS with NumberFilter conversion to integer values.",
            "date_modified": "2024-09-16T22:10:02.000Z",
            "date_published": "2020-09-28T19:05:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-x7gm-rfgv-w973"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-42731\">https://nvd.nist.gov/vuln/detail/CVE-2022-42731</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58\">https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release\">https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release\">https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django-mfa2/PYSEC-2022-303.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django-mfa2/PYSEC-2022-303.yaml</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/commit/54db5a513bcafa97a36e9f6dfa31d3c61fa8217b\">https://github.com/mkalioby/django-mfa2/commit/54db5a513bcafa97a36e9f6dfa31d3c61fa8217b</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/commit/5fbb505e98ecdd409330a5c336ad5ec49631b0db\">https://github.com/mkalioby/django-mfa2/commit/5fbb505e98ecdd409330a5c336ad5ec49631b0db</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vw39-2wj9-4q86\">https://github.com/advisories/GHSA-vw39-2wj9-4q86</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vw39-2wj9-4q86",
            "title": "[django-mfa2] django-mfa2 vulnerable to MFA Replay attack",
            "date_modified": "2024-09-16T22:09:26.000Z",
            "date_published": "2022-10-11T19:00:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vw39-2wj9-4q86"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>mfa/FIDO2.py in django-mfa2 before 2.5.1 and 2.6.x before 2.6.1 allows a replay attack that could be used to register another device for a user. The device registration challenge is not invalidated after usage.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-42731\">https://nvd.nist.gov/vuln/detail/CVE-2022-42731</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58\">https://github.com/mkalioby/django-mfa2/blob/0936ea253354dd95cb127f09d0efa31324caef27/mfa/FIDO2.py#L58</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release\">https://github.com/mkalioby/django-mfa2/releases/tag/v2.5.1-release</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release\">https://github.com/mkalioby/django-mfa2/releases/tag/v2.6.1-release</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django-mfa2/PYSEC-2022-303.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django-mfa2/PYSEC-2022-303.yaml</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/commit/54db5a513bcafa97a36e9f6dfa31d3c61fa8217b\">https://github.com/mkalioby/django-mfa2/commit/54db5a513bcafa97a36e9f6dfa31d3c61fa8217b</a></li>\n<li><a href=\"https://github.com/mkalioby/django-mfa2/commit/5fbb505e98ecdd409330a5c336ad5ec49631b0db\">https://github.com/mkalioby/django-mfa2/commit/5fbb505e98ecdd409330a5c336ad5ec49631b0db</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vw39-2wj9-4q86\">https://github.com/advisories/GHSA-vw39-2wj9-4q86</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vw39-2wj9-4q86",
            "title": "[django-mfa2] django-mfa2 vulnerable to MFA Replay attack",
            "date_modified": "2024-09-16T22:09:26.000Z",
            "date_published": "2022-10-11T19:00:29.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vw39-2wj9-4q86"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Unrestricted Upload of File with Dangerous Type in Django-Widgy v0.8.4 allows remote attackers to execute arbitrary code via the 'image' widget in the component 'Change Widgy Page'.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-18704\">https://nvd.nist.gov/vuln/detail/CVE-2020-18704</a></li>\n<li><a href=\"https://github.com/fusionbox/django-widgy/issues/387\">https://github.com/fusionbox/django-widgy/issues/387</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-98hv-qff3-8793\">https://github.com/advisories/GHSA-98hv-qff3-8793</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django-widgy/PYSEC-2021-336.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django-widgy/PYSEC-2021-336.yaml</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-98hv-qff3-8793",
            "title": "[django-widgy] Unrestricted Upload of File with Dangerous Type in django-widgy",
            "date_modified": "2024-09-16T22:06:26.000Z",
            "date_published": "2021-08-30T16:24:08.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-98hv-qff3-8793"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The CSRF protection mechanism in Django through 1.2.7 and 1.3.x through 1.3.1 does not properly handle web-server configurations supporting arbitrary HTTP Host headers, which allows remote attackers to trigger unauthenticated forged requests via vectors involving a DNS CNAME record and a web page containing JavaScript code.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4140\">https://nvd.nist.gov/vuln/detail/CVE-2011-4140</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h95j-h2rv-qrg4\">https://github.com/advisories/GHSA-h95j-h2rv-qrg4</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-5.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-5.yaml</a></li>\n<li><a href=\"https://web.archive.org/web/20140806062902/http://secunia.com/advisories/46614\">https://web.archive.org/web/20140806062902/http://secunia.com/advisories/46614</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h95j-h2rv-qrg4",
            "title": "[Django] Django Cross-Site Request Forgery vulnerability",
            "date_modified": "2024-09-16T22:05:41.000Z",
            "date_published": "2018-07-23T19:51:19.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h95j-h2rv-qrg4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>The CSRF protection mechanism in Django through 1.2.7 and 1.3.x through 1.3.1 does not properly handle web-server configurations supporting arbitrary HTTP Host headers, which allows remote attackers to trigger unauthenticated forged requests via vectors involving a DNS CNAME record and a web page containing JavaScript code.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2011-4140\">https://nvd.nist.gov/vuln/detail/CVE-2011-4140</a></li>\n<li><a href=\"https://bugzilla.redhat.com/show_bug.cgi?id=737366\">https://bugzilla.redhat.com/show_bug.cgi?id=737366</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-h95j-h2rv-qrg4\">https://github.com/advisories/GHSA-h95j-h2rv-qrg4</a></li>\n<li><a href=\"https://hermes.opensuse.org/messages/14700881\">https://hermes.opensuse.org/messages/14700881</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/11/1\">http://openwall.com/lists/oss-security/2011/09/11/1</a></li>\n<li><a href=\"http://openwall.com/lists/oss-security/2011/09/13/2\">http://openwall.com/lists/oss-security/2011/09/13/2</a></li>\n<li><a href=\"http://www.debian.org/security/2011/dsa-2332\">http://www.debian.org/security/2011/dsa-2332</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-5.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2011-5.yaml</a></li>\n<li><a href=\"https://web.archive.org/web/20140806062902/http://secunia.com/advisories/46614\">https://web.archive.org/web/20140806062902/http://secunia.com/advisories/46614</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/09\">https://www.djangoproject.com/weblog/2011/sep/09</a></li>\n<li><a href=\"https://www.djangoproject.com/weblog/2011/sep/10/127\">https://www.djangoproject.com/weblog/2011/sep/10/127</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-h95j-h2rv-qrg4",
            "title": "[Django] Django Cross-Site Request Forgery vulnerability",
            "date_modified": "2024-09-16T22:05:41.000Z",
            "date_published": "2018-07-23T19:51:19.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-h95j-h2rv-qrg4"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>The views provided by django-user-sessions allow users to terminate specific sessions. The session key is used to identify sessions, and thus included in the rendered HTML. In itself this is not a problem. However if the website has an XSS vulnerability, the session key could be extracted by the attacker and a session takeover could happen.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Patch is under way.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>Remove the session_key from the template.</p>\n<h3 id=\"references\">References</h3>\n<p><em>None.</em></p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open an issue in <a href=\"https://github.com/Bouke/django-user-sessions/issues\">Bouke/django-user-sessions</a></li>\n<li>Email us at <a href=\"mailto:bouke@haarsma.eu\">bouke@haarsma.eu</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/Bouke/django-user-sessions/security/advisories/GHSA-5fq8-3q2f-4m5g\">https://github.com/Bouke/django-user-sessions/security/advisories/GHSA-5fq8-3q2f-4m5g</a></li>\n<li><a href=\"https://github.com/jazzband/django-user-sessions/commit/f0c4077e7d1436ba6d721af85cee89222ca5d2d9\">https://github.com/jazzband/django-user-sessions/commit/f0c4077e7d1436ba6d721af85cee89222ca5d2d9</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2020-5224\">https://nvd.nist.gov/vuln/detail/CVE-2020-5224</a></li>\n<li><a href=\"https://github.com/pypa/advisory-database/tree/main/vulns/django-user-sessions/PYSEC-2020-230.yaml\">https://github.com/pypa/advisory-database/tree/main/vulns/django-user-sessions/PYSEC-2020-230.yaml</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5fq8-3q2f-4m5g\">https://github.com/advisories/GHSA-5fq8-3q2f-4m5g</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5fq8-3q2f-4m5g",
            "title": "[django-user-sessions] Session key exposure through session list in Django User Sessions",
            "date_modified": "2024-09-16T21:59:21.000Z",
            "date_published": "2020-01-24T19:56:59.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5fq8-3q2f-4m5g"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}