{
    "version": "https://jsonfeed.org/version/1",
    "title": "Security Advisory for Python packages hosted at PyPI.org",
    "home_page_url": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip",
    "feed_url": "https://azu.github.io/github-advisory-database-rss/pip.json",
    "description": "Security Advisory for Python packages hosted at PyPI.org on GitHub",
    "items": [
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>OWSLib's XML parser (which supports both <code>lxml</code> and <code>xml.etree</code>) does not disable entity resolution, and could lead to arbitrary file reads from an attacker-controlled XML payload. This affects all XML parsing in the codebase.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>This issue is patched in 0.28.1.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>The patch approach should be:</p>\n<ul>\n<li>update all XML support as follows:<ul>\n<li>use ONLY <code>lxml.etree</code></li>\n<li>apply the patch below</li>\n</ul>\n</li>\n</ul>\n<pre><code class=\"language-python\">patch_well_known_namespaces(etree)\netree.set_default_parser(\n    parser=etree.XMLParser(resolve_entities=False)\n)\n</code></pre>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><code>GHSL-2022-131</code></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/geopython/OWSLib/security/advisories/GHSA-8h9c-r582-mggc\">https://github.com/geopython/OWSLib/security/advisories/GHSA-8h9c-r582-mggc</a></li>\n<li><a href=\"https://github.com/geopython/OWSLib/pull/863\">https://github.com/geopython/OWSLib/pull/863</a></li>\n<li><a href=\"https://github.com/geopython/OWSLib/releases/tag/0.28.1\">https://github.com/geopython/OWSLib/releases/tag/0.28.1</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-8h9c-r582-mggc\">https://github.com/advisories/GHSA-8h9c-r582-mggc</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-8h9c-r582-mggc",
            "title": "[OWSLib] OWSLib vulnerable to XML External Entity (XXE) Injection",
            "date_modified": "2023-03-07T20:41:36.000Z",
            "date_published": "2023-03-07T20:41:36.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-8h9c-r582-mggc"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like user email address in staff-authenticated requests.</p>\n<p>This issue has been patched in versions 3.1.48, 3.7.59, 3.8.30, 3.9.27, 3.10.14 and 3.11.12.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/saleor/saleor/security/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26051\">https://nvd.nist.gov/vuln/detail/CVE-2023-26051</a></li>\n<li><a href=\"https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1\">https://github.com/saleor/saleor/commit/31bce881ccccf0d79a9b14ecb6ca3138d1edeec1</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-r8qr-wwg3-2r85\">https://github.com/advisories/GHSA-r8qr-wwg3-2r85</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85",
            "title": "[Saleor] Saleor has Staff-Authenticated Error Message Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-03T22:46:06.000Z",
            "date_published": "2023-03-03T22:46:04.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-r8qr-wwg3-2r85"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Denial of service could be caused to markdown-it-py, before v2.2.0, if an attacker was allowed to force null assertions with specially crafted input.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26303\">https://nvd.nist.gov/vuln/detail/CVE-2023-26303</a></li>\n<li><a href=\"https://github.com/executablebooks/markdown-it-py/commit/ae03c6107dfa18e648f6fdd1280f5b89092d5d49\">https://github.com/executablebooks/markdown-it-py/commit/ae03c6107dfa18e648f6fdd1280f5b89092d5d49</a></li>\n<li><a href=\"https://github.com/executablebooks/markdown-it-py/pull/246\">https://github.com/executablebooks/markdown-it-py/pull/246</a></li>\n<li><a href=\"https://github.com/executablebooks/markdown-it-py/commit/53ca3e9c2b9e9b295f6abf7f4ad2730a9b70f68c\">https://github.com/executablebooks/markdown-it-py/commit/53ca3e9c2b9e9b295f6abf7f4ad2730a9b70f68c</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vrjv-mxr7-vjf8\">https://github.com/advisories/GHSA-vrjv-mxr7-vjf8</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vrjv-mxr7-vjf8",
            "title": "[markdown-it-py] markdown-it-py Denial of Service vulnerability",
            "date_modified": "2023-03-03T23:17:36.000Z",
            "date_published": "2023-02-23T00:30:39.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vrjv-mxr7-vjf8"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>Cross-site Scripting (XSS) - Reflected in GitHub repository modoboa/modoboa prior to 2.0.4. A patch is available and anticipated to be part of version 2.0.5.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-0949\">https://nvd.nist.gov/vuln/detail/CVE-2023-0949</a></li>\n<li><a href=\"https://github.com/modoboa/modoboa/commit/aa74e9a4a870162eea169e0a6a2eab841f8811b7\">https://github.com/modoboa/modoboa/commit/aa74e9a4a870162eea169e0a6a2eab841f8811b7</a></li>\n<li><a href=\"https://huntr.dev/bounties/ef87be4e-493b-4ee9-9738-44c55b8acc19\">https://huntr.dev/bounties/ef87be4e-493b-4ee9-9738-44c55b8acc19</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-mgmm-cmhj-2h5f\">https://github.com/advisories/GHSA-mgmm-cmhj-2h5f</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-mgmm-cmhj-2h5f",
            "title": "[modoboa] modoboa Cross-site Scripting vulnerability",
            "date_modified": "2023-03-03T00:15:15.000Z",
            "date_published": "2023-02-22T09:30:18.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-mgmm-cmhj-2h5f"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests.</p>\n<p>Affected versions: Saleor ≥ 2.0.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26052\">https://nvd.nist.gov/vuln/detail/CVE-2023-26052</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/advisories/GHSA-3hvj-3cg9-v242</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242",
            "title": "[saleor] Saleor Unauthenticated Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-02T23:04:11.000Z",
            "date_published": "2023-03-02T23:04:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests.</p>\n<p>Affected versions: Saleor ≥ 2.0.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26052\">https://nvd.nist.gov/vuln/detail/CVE-2023-26052</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/advisories/GHSA-3hvj-3cg9-v242</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242",
            "title": "[saleor] Saleor Unauthenticated Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-02T23:04:11.000Z",
            "date_published": "2023-03-02T23:04:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests.</p>\n<p>Affected versions: Saleor ≥ 2.0.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26052\">https://nvd.nist.gov/vuln/detail/CVE-2023-26052</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/advisories/GHSA-3hvj-3cg9-v242</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242",
            "title": "[saleor] Saleor Unauthenticated Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-02T23:04:11.000Z",
            "date_published": "2023-03-02T23:04:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests.</p>\n<p>Affected versions: Saleor ≥ 2.0.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26052\">https://nvd.nist.gov/vuln/detail/CVE-2023-26052</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/advisories/GHSA-3hvj-3cg9-v242</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242",
            "title": "[saleor] Saleor Unauthenticated Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-02T23:04:11.000Z",
            "date_published": "2023-03-02T23:04:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests.</p>\n<p>Affected versions: Saleor ≥ 2.0.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26052\">https://nvd.nist.gov/vuln/detail/CVE-2023-26052</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/advisories/GHSA-3hvj-3cg9-v242</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242",
            "title": "[saleor] Saleor Unauthenticated Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-02T23:04:11.000Z",
            "date_published": "2023-03-02T23:04:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Some internal Python exceptions are not handled properly and thus are returned in API as error messages. Some messages might contain sensitive information like infrastructure details in unauthenticated requests.</p>\n<p>Affected versions: Saleor ≥ 2.0.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Open a discussion at <a href=\"https://github.com/saleor/saleor/discussions\">https://github.com/saleor/saleor/discussions</a></li>\n<li>Email us at <a href=\"mailto:hello@saleor.io\">hello@saleor.io</a></li>\n</ul>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/saleor/saleor/security/advisories/GHSA-3hvj-3cg9-v242</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-26052\">https://nvd.nist.gov/vuln/detail/CVE-2023-26052</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.1.48\">https://github.com/saleor/saleor/releases/tag/3.1.48</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.10.14\">https://github.com/saleor/saleor/releases/tag/3.10.14</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.11.12\">https://github.com/saleor/saleor/releases/tag/3.11.12</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.7.59\">https://github.com/saleor/saleor/releases/tag/3.7.59</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.8.30\">https://github.com/saleor/saleor/releases/tag/3.8.30</a></li>\n<li><a href=\"https://github.com/saleor/saleor/releases/tag/3.9.27\">https://github.com/saleor/saleor/releases/tag/3.9.27</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-3hvj-3cg9-v242\">https://github.com/advisories/GHSA-3hvj-3cg9-v242</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242",
            "title": "[saleor] Saleor Unauthenticated Information Disclosure Vulnerability via Python Exceptions",
            "date_modified": "2023-03-02T23:04:11.000Z",
            "date_published": "2023-03-02T23:04:10.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-3hvj-3cg9-v242"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>powerline-gitstatus (aka Powerline Gitstatus) before 1.3.2 allows arbitrary code execution. git repositories can contain per-repository configuration that changes the behavior of git, including running arbitrary commands. When using powerline-gitstatus, changing to a directory automatically runs git commands in order to display information about the current repository in the prompt. If an attacker can convince a user to change their current directory to one controlled by the attacker, such as in a shared filesystem or extracted archive, powerline-gitstatus will run arbitrary commands under the attacker's control. NOTE: this is similar to CVE-2022-20001.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-42906\">https://nvd.nist.gov/vuln/detail/CVE-2022-42906</a></li>\n<li><a href=\"https://github.com/jaspernbrouwer/powerline-gitstatus/issues/45\">https://github.com/jaspernbrouwer/powerline-gitstatus/issues/45</a></li>\n<li><a href=\"https://github.com/jaspernbrouwer/powerline-gitstatus/releases/tag/v1.3.2\">https://github.com/jaspernbrouwer/powerline-gitstatus/releases/tag/v1.3.2</a></li>\n<li><a href=\"https://github.com/jaspernbrouwer/powerline-gitstatus/commit/fe8e963b3489e4cceaa2c1f26f2bcc2ef405364c\">https://github.com/jaspernbrouwer/powerline-gitstatus/commit/fe8e963b3489e4cceaa2c1f26f2bcc2ef405364c</a></li>\n<li><a href=\"https://lists.debian.org/debian-lts-announce/2023/01/msg00017.html\">https://lists.debian.org/debian-lts-announce/2023/01/msg00017.html</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-w67g-6gjv-c599\">https://github.com/advisories/GHSA-w67g-6gjv-c599</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-w67g-6gjv-c599",
            "title": "[powerline-gitstatus] Powerline Gitstatus vulnerable to arbitrary code execution",
            "date_modified": "2023-03-02T18:17:42.000Z",
            "date_published": "2022-10-13T12:00:26.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-w67g-6gjv-c599"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>A regular expression used in Apache MXNet (incubating) is vulnerable to a potential denial-of-service by excessive resource consumption. The bug could be exploited when loading a model in Apache MXNet that has a specially crafted operator name that would cause the regular expression evaluation to use excessive resources to attempt a match. This issue affects Apache MXNet versions prior to 1.9.1.</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2022-24294\">https://nvd.nist.gov/vuln/detail/CVE-2022-24294</a></li>\n<li><a href=\"https://lists.apache.org/thread/b1fbfmvzlr2bbp95lqoh3mtovclfcl3o\">https://lists.apache.org/thread/b1fbfmvzlr2bbp95lqoh3mtovclfcl3o</a></li>\n<li><a href=\"http://www.openwall.com/lists/oss-security/2022/07/24/2\">http://www.openwall.com/lists/oss-security/2022/07/24/2</a></li>\n<li><a href=\"https://github.com/apache/mxnet/releases/tag/1.9.1\">https://github.com/apache/mxnet/releases/tag/1.9.1</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-xxj3-55p6-xg3h\">https://github.com/advisories/GHSA-xxj3-55p6-xg3h</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-xxj3-55p6-xg3h",
            "title": "[mxnet] Apache MXNet vulnerable to potential denial-of-service by excessive resource consumption",
            "date_modified": "2023-03-01T20:32:46.000Z",
            "date_published": "2022-07-25T00:00:31.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-xxj3-55p6-xg3h"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"overview\">Overview</h3>\n<p>Lemur was using insecure random generation for its example configuration file, as well as for some utilities.</p>\n<h3 id=\"impact\">Impact</h3>\n<p>The potentially affected generated items include:</p>\n<table>\n<thead>\n<tr>\n<th>Configuration item</th>\n<th>Config option name (if applicable)</th>\n<th>Documentation link (if applicable)</th>\n<th>Rotation option</th>\n<th>Code reference(s)</th>\n</tr>\n</thead>\n<tbody><tr>\n<td>Flask session secret</td>\n<td><code>SECRET_KEY</code></td>\n<td><a href=\"https://flask.palletsprojects.com/en/2.2.x/config/#SECRET_KEY\">Flask documentation</a></td>\n<td>Generate a new secret and place in config; all existing sessions will be invalidated</td>\n<td>N/A, internal to Flask</td>\n</tr>\n<tr>\n<td>Lemur token secret</td>\n<td><code>LEMUR_TOKEN_SECRET</code></td>\n<td><a href=\"https://lemur.readthedocs.io/en/latest/administration.html#configuration\">Lemur's configuration documentation</a></td>\n<td>Generate a new secret and place in config; all existing JWTs will be invalidated and must be regenerated (including API keys)</td>\n<td><a href=\"https://github.com/Netflix/lemur/blob/1b61194a936240103f3c23299f9512c2b7e0fd36/lemur/auth/service.py#L79\">1</a>, <a href=\"https://github.com/Netflix/lemur/blob/1b61194a936240103f3c23299f9512c2b7e0fd36/lemur/auth/service.py#L105\">2</a></td>\n</tr>\n<tr>\n<td>Lemur database encryption key</td>\n<td><code>LEMUR_ENCRYPTION_KEYS</code></td>\n<td><a href=\"https://lemur.readthedocs.io/en/latest/administration.html#configuration\">Lemur's configuration documentation</a></td>\n<td>A new key can be generated and added to this list, but existing data encrypted with prior keys cannot be re-encrypted unless you write a custom re-encryption process</td>\n<td><a href=\"https://github.com/Netflix/lemur/blob/3783fbeaa1645bbee022827f4f53ffb12dd65a61/lemur/utils.py#L58\">1</a></td>\n</tr>\n<tr>\n<td>OAuth2 state token secret key</td>\n<td><code>OAUTH_STATE_TOKEN_SECRET</code></td>\n<td><a href=\"https://lemur.readthedocs.io/en/latest/administration.html#configuration\">Lemur's configuration documentation</a></td>\n<td>Generate a new secret and place in config</td>\n<td><a href=\"https://github.com/Netflix/lemur/blob/4b03baaf5544f167e78055bab15a903b1badf22b/lemur/auth/views.py#L267\">1</a></td>\n</tr>\n<tr>\n<td>Randomly generated passphrases for openssl keystores</td>\n<td>N/A, generated at runtime but persisted</td>\n<td>N/A</td>\n<td>Re-export all openssl keystores and replace them wherever they're in use</td>\n<td><a href=\"https://github.com/Netflix/lemur/blob/2603776e5c0ac25fa0103ff1357dea391d880160/lemur/plugins/lemur_openssl/plugin.py#L129\">1</a></td>\n</tr>\n<tr>\n<td>Initial password for LDAP users</td>\n<td>N/A, generated at runtime but persisted</td>\n<td>N/A</td>\n<td>N/A, cannot be rotated*</td>\n<td><a href=\"https://github.com/Netflix/lemur/blob/3783fbeaa1645bbee022827f4f53ffb12dd65a61/lemur/auth/ldap.py#L66\">1</a></td>\n</tr>\n<tr>\n<td>Initial password for Ping/OAuth2 users</td>\n<td>N/A, generated at runtime but persisted</td>\n<td>N/A</td>\n<td>N/A, cannot be rotated*</td>\n<td><a href=\"https://github.com/Netflix/lemur/blob/4b03baaf5544f167e78055bab15a903b1badf22b/lemur/auth/views.py#L234\">1</a></td>\n</tr>\n<tr>\n<td>Oauth2 nonce</td>\n<td>N/A, short-lived runtime secret</td>\n<td>N/A</td>\n<td>N/A, rotation is not required (these are short-lived)</td>\n<td><a href=\"https://github.com/Netflix/lemur/blob/4b03baaf5544f167e78055bab15a903b1badf22b/lemur/auth/views.py#L668\">1</a></td>\n</tr>\n<tr>\n<td>Verisign certificate enrollment challenges</td>\n<td>N/A, short-lived runtime secret</td>\n<td>N/A</td>\n<td>N/A, rotation is not required (these are short-lived)</td>\n<td><a href=\"https://github.com/Netflix/lemur/blob/d4af5af99cd51016579f015d79df649c68a6ad15/lemur/plugins/lemur_verisign/plugin.py#L107\">1</a></td>\n</tr>\n</tbody></table>\n<p>If your deployment of Lemur is using any of the above config secrets that were <em>generated by Lemur's example config</em> (i.e., generated using insecure randomness), you should rotate those config secrets. If you generated your config secrets in a more secure way, they are not known to be compromised, but you should still upgrade Lemur to ensure that you receive code fixes for the runtime-generated secrets.</p>\n<p>For general information and guidance on Lemur secret configuration, see <a href=\"https://lemur.readthedocs.io/en/latest/administration.html#configuration\">Lemur's configuration documentation</a>, which includes information on many of the configuration options listed above.</p>\n<p>*For the user passwords: Even though these users are configured to use SSO, they do get generated with valid database passwords that can be used to log in. Since Lemur doesn't have an option to change passwords (#3888), one option for rotating them would be to directly modify the value in the database to some other unguessable string (you do not need to know the plaintext password since it won't be used).</p>\n<h3 id=\"patches\">Patches</h3>\n<p>The patch is available in v1.3.2.</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>No workarounds are available.</p>\n<h3 id=\"references\">References</h3>\n<p>N/A</p>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/Netflix/lemur/security/advisories/GHSA-5fqv-mpj8-h7gm\">https://github.com/Netflix/lemur/security/advisories/GHSA-5fqv-mpj8-h7gm</a></li>\n<li><a href=\"https://github.com/Netflix/lemur/issues/3888\">https://github.com/Netflix/lemur/issues/3888</a></li>\n<li><a href=\"https://github.com/Netflix/lemur/commit/666d853212174ee7f4e6f8b3b4b389ede1872238\">https://github.com/Netflix/lemur/commit/666d853212174ee7f4e6f8b3b4b389ede1872238</a></li>\n<li><a href=\"https://github.com/Netflix/security-bulletins/blob/master/advisories/nflx-2023-001.md\">https://github.com/Netflix/security-bulletins/blob/master/advisories/nflx-2023-001.md</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-5fqv-mpj8-h7gm\">https://github.com/advisories/GHSA-5fqv-mpj8-h7gm</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-5fqv-mpj8-h7gm",
            "title": "[lemur] Lemur subject to insecure random generation",
            "date_modified": "2023-03-01T18:05:57.000Z",
            "date_published": "2023-03-01T18:05:56.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-5fqv-mpj8-h7gm"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<p>From issue: </p>\n<p>Problem description\nCurrently, the refresh token is valid indefinitely. This is bad security practice.</p>\n<p>Desired solution\nThe refresh token should get a validity of 24-48 hours.</p>\n<p>Additional context</p>\n<p>When implementing this, also check that the refresh token returns a new refresh token\nWhen implementing this, also adapt the UI so that it logs out if refresh token is no longer valid.\nWhen implementing this, ensure that nodes refresh their token periodically so that they do not have to be restarted manually.</p>\n<h3 id=\"impact\">Impact</h3>\n<h3 id=\"patches\">Patches</h3>\n<p>None available </p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None available</p>\n<h3 id=\"references\">References</h3>\n<ul>\n<li><a href=\"https://github.com/vantage6/vantage6/security/advisories/GHSA-4w59-c3gc-rrhp\">https://github.com/vantage6/vantage6/security/advisories/GHSA-4w59-c3gc-rrhp</a></li>\n<li><a href=\"https://github.com/vantage6/vantage6/commit/48ebfca42359e9a6743e9598684585e2522cdce8\">https://github.com/vantage6/vantage6/commit/48ebfca42359e9a6743e9598684585e2522cdce8</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-23929\">https://nvd.nist.gov/vuln/detail/CVE-2023-23929</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-4w59-c3gc-rrhp\">https://github.com/advisories/GHSA-4w59-c3gc-rrhp</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-4w59-c3gc-rrhp",
            "title": "[vantage6] vantage6 refresh tokens do not expire",
            "date_modified": "2023-03-06T01:43:01.000Z",
            "date_published": "2023-02-28T23:20:05.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-4w59-c3gc-rrhp"
            },
            "tags": [
                "severity"
            ]
        },
        {
            "content_html": "<h3 id=\"impact\">Impact</h3>\n<p>Assigning existing users to a different organization is currently possible. It may lead to unintended access: if a user from organization A is accidentally assigned to organization B, they will retain their permissions and therefore might be able to access stuff they should not be allowed to access.</p>\n<h3 id=\"patches\">Patches</h3>\n<p>Update to 3.8.0</p>\n<h3 id=\"workarounds\">Workarounds</h3>\n<p>None</p>\n<h3 id=\"references\">References</h3>\n<p>None</p>\n<h3 id=\"for-more-information\">For more information</h3>\n<p>If you have any questions or comments about this advisory:</p>\n<ul>\n<li>Email us at <a href=\"mailto:vantage6@iknl.nl\">vantage6@iknl.nl</a></li>\n</ul>\n<h3 id=\"references-1\">References</h3>\n<ul>\n<li><a href=\"https://github.com/vantage6/vantage6/security/advisories/GHSA-vvjv-97j8-94xh\">https://github.com/vantage6/vantage6/security/advisories/GHSA-vvjv-97j8-94xh</a></li>\n<li><a href=\"https://github.com/vantage6/vantage6/commit/798aca1de142a4eca175ef51112e2235642f4f24\">https://github.com/vantage6/vantage6/commit/798aca1de142a4eca175ef51112e2235642f4f24</a></li>\n<li><a href=\"https://nvd.nist.gov/vuln/detail/CVE-2023-22738\">https://nvd.nist.gov/vuln/detail/CVE-2023-22738</a></li>\n<li><a href=\"https://github.com/advisories/GHSA-vvjv-97j8-94xh\">https://github.com/advisories/GHSA-vvjv-97j8-94xh</a></li>\n</ul>\n",
            "url": "https://github.com/advisories/GHSA-vvjv-97j8-94xh",
            "title": "[vantage6] vantage6 vulnerable to Improper Preservation of Permissions",
            "date_modified": "2023-03-02T20:04:43.000Z",
            "date_published": "2023-02-28T23:19:24.000Z",
            "author": {
                "name": "GitHub",
                "url": "https://github.com/advisories/GHSA-vvjv-97j8-94xh"
            },
            "tags": [
                "severity"
            ]
        }
    ]
}